### ISSUE TITLE
Police Oversight form: Heroku build error

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1050]
When Eric merged his style branch into master and was trying to rebuild on production: https://dashboard.heroku.com/apps/officer-form/activity/builds/febea317-883c-4c44-ad15-8294790ed51f

**Comment by amenity** [comment]
@sergiogcx - let me know if you need more info and please size.

**Comment by sergiogcx** [comment]
This isn't a pipeline issue, it is a code issue. The reason it does not deploy on heroku is because the code fails to compile, given errors in the code.

To replicate the issue in your system, follow these steps in a clean directory:

```
# Clone master (i should be able to run it):
$ git clone https://github.com/cityofaustin/officer-complaint-form.git

$ cd officer-complaint-form

# Install all dependencies
$ yarn

# Run it
$ yarn start
```

Then I get this error (same with `yarn build`):

```
ERROR in ./css/overrides.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./css/overrides.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "node_modules/foundation-sites/scss/foundation/components/grid";
^
      File to import not found or unreadable: node_modules/foundation-sites/scss/foundation/components/grid.
      in /Users/GarciaS/Development/Deleteme/officer-complaint-form/node_modules/us-forms-system/src/scss/styles.scss (line 5, column 1)
 @ ./css/overrides.scss 2:14-121
 @ ./app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app
ℹ ｢wdm｣: Failed to compile
```

Eric has been working on the sass styling branch that is causing the problem; after speaking with him, he has now been able to replicate the issue on his computer. To fix this issue, the same steps that were used to run it locally need to be applied to master.

This issue can be closed or reassigned,

@amenity @briaguya @easherma

**Comment by amenity** [comment]
Awesome, thanks for the explanation, @sergiogcx!
