### ISSUE TITLE
Feedback Form -- Determine Workflow

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#107]
determine what should happen to user submitted data:

- [ ] quantitative data associated with emoji selection

- [ ] open-ended qualitative data

Previously: https://github.com/cityofaustin/joplin/issues/8#event-1352987861

**Comment by amenity** [comment]
When the user submits emoji data, ☹️ 🙁 😐 🙂 😄, it will be stored as a number so that it can be seen in Joplin by authors and editors in the future. 

Text feedback will create a Github issue that captures the operating system, device, emoji data, and creates a Github issue in the https://github.com/cityofaustin/alpha-feedback repo for Product manager triage.

The expectation is that this workflow will be modified once we learn more about the utility of the feedback submitted. It is possible that we will opt to send these issues to a public repo and return a link to the user once they submit the issue.

**Comment by amenity** [comment]
@ifsimicoded - can you check ☝️ and close this guy if it correctly captures the workflow we've agreed on?

**Comment by ifsimicoded** [comment]
My understanding was --
1) Emoji click data would NOT be logged in joplin. 
2) Emoji click data WILL be logged in Google Analytics as an event.
3) If a user submits further information via the open text field, that will open a github issue to store this information, along with the emoji data.
