### ISSUE TITLE
Feedback Form -- Design

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#108]
##mobile/sm
![screen shot 2018-03-09 at 3 27 07 pm](https://user-images.githubusercontent.com/20911665/37230947-d0f564f0-23ae-11e8-975c-26084c6e4d2c.png)
##tablet/med
![screen shot 2018-03-09 at 3 28 53 pm](https://user-images.githubusercontent.com/20911665/37230948-d10accf0-23ae-11e8-904a-934eacb8b233.png)
##desktop/lge
![screen shot 2018-03-09 at 3 29 49 pm](https://user-images.githubusercontent.com/20911665/37230949-d11fdd20-23ae-11e8-9a4f-2b9217b24da8.png)

sketch file, shown on homepage mocks: https://drive.google.com/open?id=1wtiU9LqpvU2KTu362bCPMfS7tfYgjyuf

**Comment by cthibaultatx** [comment]
@amenity @ifsimicoded the design and review is done for feedback form. If we decide to not go with a public forum, then we can simply remove some of the copy in the current ^ UX.

**Comment by LauraTrujillo** [comment]
@cthibaultatx Are we still telling people not to enter private information in the feedback?

**Comment by cthibaultatx** [comment]
@LauraTrujillo no because the data will be internal only, for now.

**Comment by LauraTrujillo** [comment]
@cthibaultatx Cool, thanks. Looks really great!

**Comment by courtneyjacinic** [comment]
@cthibaultatx Not sure I understand the value in saying we'll get back to them. Do we have a process set up on the back end to handle this? If including the email is the way to ensure getting a response, then users need to be made aware of that when entering the feedback instead of after. If a user wanted a response and saw they missed their chance (in screen 3), they could be pretty upset OR they could send another message that is redundant but with their email.

**Comment by cthibaultatx** [comment]
made updates based on last feedback items ^
