### ISSUE TITLE
Police Oversight form: Date and time selection should be constrained to the past.

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1086]
**Describe the bug**
User can report incidents which take place in the future.

**Comment by desigonz** [comment]
@Niicck @amenity @toribr  I'm doing QA and had more of a UX question rather than a bug to report. Nick's implementation of not picking a date works beautifully on the calendar. If you type in "2020" into the field, it reverts to 2019, but we don't have any error messaging explaining why—should we?

**Comment by easherma** [comment]
@Niicck wasn't this implemented in your component?

**Comment by Niicck** [comment]
Additional bug. When filling in the month and day, the year will autofill to 2019... even if that date is in the future. The year should be autofilled to the most recent past date- whether in this year or last year.

**Comment by Niicck** [comment]
Date selection should be constrained to the past. This has been bugging people for a little while, so I decided to fix it more thoroughly. I'd like Design's input/blessing on my approach.

Check it out. You plug it the month and day and it'll automatically plug in the nearest past year for you. A previous version autofilled the current year every time. But that led to bugs. Because if you plugged in July 11th for instance, it would autofill 2019, which is in the future. That has been fixed with this version. Demo:

![autocorrect_date.gif](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/057516be-d257-44a2-bee5-7e14141e943c)

Question 1: Per Desi's comment above, should inform people that we're autocorrecting the year? Right now everything is done silently. We can easily add a non-warning message indicating that we changed the year for them.

My current code display no validation errors, because it's impossible to enter an invalid future date. If you try to enter a year in the future (for whatever reason?) it will automatically revert back to the last valid date. Demo:

![autocorrect_date_2.gif](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/440bc0a4-c6d2-4c7e-b97a-4a5b2c29ec44)

Question 2: Is the autocorrect on the year helpful or mysterious and confusing?

A not unreasonable alternative would be to *not* automatically update the year. And we could display a warning message telling users that they have to enter a date in the past. The benefit being that users would have to consciously and explicitly set the correct year of their incident.

Let me know your thoughts. It hasn't been deployed to staging yet, but it could be if you want to play with it yourselves.

**Comment by Niicck** [comment]
My current code display no validation errors, because it's impossible to enter an invalid future date. If you try to enter a year in the future (for whatever reason?) it will automatically revert back to the last valid date. Demo:

![autocorrect_date_2.gif](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/440bc0a4-c6d2-4c7e-b97a-4a5b2c29ec44)

Question 2: Is the autocorrect on the year helpful or mysterious and confusing?

A not unreasonable alternative would be to *not* automatically update the year. And we could display a warning message telling users that they have to enter a date in the past. The benefit being that users would have to consciously and explicitly set the correct year of their incident.

Let me know your thoughts. It hasn't been deployed to staging yet, but it could be if you want to play with it yourselves.

**Comment by Niicck** [comment]
Tori's response on Slack:
To better understand this, I think we need to ask OPO what the average time frame for reporting is. Stand by.
I suspect that your implementation will work fine, but i'm assuming that the time frame for reporting is relatively short, ie, current year is a good default. But let's see what they say as one of my usability participants claimed that folks he knew waited a long time to report.

**Comment by oliver2g** [comment]
@Niicck is this fix in staging? can i verify it in QA?

**Comment by Niicck** [comment]
Hi Gerald, it's now merged into staging and ready to test.

Test Criteria (that I can think of):
- [ ] You should not be able to enter any future date
- [ ] You should not be able to enter any invalid date (eg: February 31st, 2017)
