### ISSUE TITLE
Janis 2.0: 404 page visual design update MVP

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1100]
Attach final comp of 404 page and any assets here.

See also #174

**Comment by chasechenevert** [comment]
## Resources
- Doc: [404 Page research and discovery](https://docs.google.com/document/d/1keeUmd_EpJyV7X4uJ3MpT9JRuh7q0Ha2lRM-XuucTFs/edit#heading=h.20d1cmdmna2s)

## MVP
For MVP we're going to go with a general error for now since there is going to be a lot of experimentation on Alpha (pages moving, features being added, maintenance, etc.)
- Headline
- Subhead or body text
- Austin.gov search box to bring users to Austin.gov if they reach an error on Alpha, or can't find what they're looking for

## Future release
- Page-level alerts (global, department, service, etc.)
- Emergency alerts
