### ISSUE TITLE
Police Oversight form: Tweaks to confirmation email design. 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1137]

**Comment by sergiogcx** [comment]
Ok, this is mostly done. Sorry for the delay. I had issues with Outlook being unable to render css styles. The problem is that Outlook does not use css/html, instead it uses an engine based off of Microsoft Word, and does not see styles and html objects the same way.


#### Tests:

https://app.emailonacid.com/app/acidtest/c8f3zRdLAuQvCZJFg07UJD8VIMLAXFTIJIDDv3eoZLvqz/list

Ready for Q/A Feedback @amenity @chasechenevert @toribr

**Comment by sergiogcx** [comment]
Initially Outlook was not even showing the header at all, then in no colors (all gray); then, after some effort, I managed to make Outlook look like this:

![Screen Shot 2019-02-11 at 9.18.55 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/98954db5-5b92-423a-84fe-881c6ef851ab)

This is the "responsive" version:

![Screen_Shot_2019-02-11_at_9_19_29_PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/fb9449cb-f346-4786-a5ba-724de76c9f42)

**We should be creating a new issue to dedicate more time to writing stuff specifically for the outlook engine **

**Comment by amenity** [comment]
Cool. We made #1190 yesterday, @sergiogcx. Does that cover ☝️ well enough for you?
