### ISSUE TITLE
Police Oversight form: Capitalization fixes in "Add another" buttons

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1182]
- [x] Add Another (button) → Add another (lowercase) (on [Tell us about the officer(s)](https://forms.austintexas.io/police-oversight/complaint/officer-details) and [Tell us about any witnesses](https://forms.austintexas.io/police-oversight/complaint/witness-details))
- [x] Update Page (button) → Update page (lowercase) (on [Review your answers before submitting](https://forms.austintexas.io/police-oversight/complaint/review-and-submit))

**Comment by easherma** [comment]
@amenity the 'drag and drop' text is part of the Filepond widget. So not a super easy way to override that. 

However, I'm interested in what @sergiogcx thinks of the following: 
We could use the feature you wrote for translations, since I assume we are translating this phrase, and maybe change the capitalization there? 

The other two are part of us-forms systems, so we should be able to tweak those a bit easier.

**Comment by easherma** [comment]
https://github.com/cityofaustin/officer-form-chapters/commit/8162f3b7aaa701ca509a424607cbf0e7fe9b8ddb

**Comment by amenity** [comment]
@easherma, I am still seeing:
<img width="376" alt="Screen Shot 2019-03-13 at 5 51 17 PM" src="https://user-images.githubusercontent.com/1463708/54319921-50e59400-45b9-11e9-947e-ba066c075f76.png">
<img width="362" alt="Screen Shot 2019-03-13 at 5 56 12 PM" src="https://user-images.githubusercontent.com/1463708/54319922-517e2a80-45b9-11e9-9e4c-48ffe8fa88a6.png">

Should I open a new issue?

**Comment by easherma** [comment]
Should truly be fixed on staging https://forms.austintexas.io/police-complain
