### ISSUE TITLE
Police Oversight form: Said yes for contact, but was n/a on email

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1184]
**Describe the bug**
I was filling out the OPO form during demo, I checked that I was willing to be contacted. However, in the email that option came up as N/A

**Expected behavior**
Should say True/Yes, or something

**Comment by sergiogcx** [comment]
Ah, let me look into it.

**Comment by sergiogcx** [comment]
Thanks for the catch! This problem is (or was) present in the complaint and thank you emails. I have updated the email templates and it should now work in the next PR.
https://github.com/cityofaustin/form-service-api/pull/6

The actual code is in the template:
https://github.com/cityofaustin/form-service-api/blob/f28c5c3aa9d4c81cda5279bacf4c693a0fa653c2/templates/email/officepoliceoversight/complaint/form-data.html#L103

Changed from: 

```
<p>{{t('willingcontact')}}: {{data['view:contactPreferences']['willingToBeContacted'] or 'N/A' }}</p>
```

To:

```
<p>{{t('willingcontact')}}: {{data['willingToBeContacted'] or 'N/A' }}</p>
```

Thank you @easherma
