### ISSUE TITLE
Police Oversight form: Retest for multiple simultaneous email bug

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1212]
Look at IDs in logs

Aha! Link: https://desi1.aha.io/features/RT-20

**Comment by amenity** [comment]
Couldn't reproduce, backlog for now.

**Comment by sergiogcx** [comment]
I have been testing this, and I see no signs of sending duplicates or the wrong emails to the wrong people.

When this issue was first reported, I changed the code a little bit so that the process destroys the variables first, then populates the email data and builds an email with it, in a repeated process, this would continue: first delete any data in memory, then send.

To test, I have used my personal email, and also created a couple email addresses:

```
sergio.garcia@austintexas.io
devops@austintexas.io
```

I submitted different form payloads at the same time, all arrived as expected, all created with a unique case number.

First round of tests:

```
curl -d "@test-1.json" -H "Content-Type: application/json" -X POST http://localhost:5000/form/submit &
curl -d "@test-2.json" -H "Content-Type: application/json" -X POST http://localhost:5000/form/submit &
curl -d "@test-3.json" -H "Content-Type: application/json" -X POST http://localhost:5000/form/submit &
```

The -d "@filename" shows the payload that was sent, the endpoint is the master branch running locally on my computer. The ampersand symbol at the end `&` directs the terminal to run the process in the background, and starts the next one.

The output:

```
{"case_number":"2019-0306-ed77","message":"success","status":"success"}
{"case_number":"2019-0306-5196","message":"success","status":"success"}
{"case_number":"2019-0306-5f16","message":"success","status":"success"}
```

The second round, now tested the master branch on AWS:

```
curl -d "@test-1.json" -H "Content-Type: application/json" -X POST https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/form/submit &
curl -d "@test-2.json" -H "Content-Type: application/json" -X POST https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/form/submit &
curl -d "@test-3.json" -H "Content-Type: application/json" -X POST https://6jm8rnjkxf.execute-api.us-east-1.amazonaws.com/staging/form/submit &
```

The Output:

```
{"case_number":"2019-0306-e11d","message":"success","status":"success"}
{"case_number":"2019-0306-bbd2","message":"success","status":"success"}
{"case_number":"2019-0306-a139","message":"success","status":"success"}
```

It looks like the endpoint works as expected, I do not see any reason for concern for now. I believe we could set up another test where everybody in content submits a complaint, and see if we see the same level of success or if we need to address something in the code.

**Comment by sergiogcx** [comment]
### These are the emails received from the code currently in master (aws)

![Screen Shot 2019-03-06 at 5.40.47 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/060f1210-f0bd-46bc-871b-ddf4893bbd50)

![Screen Shot 2019-03-06 at 5.43.35 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ff2f78b5-153d-4d92-8549-0a5ac1a1c2a9)

![Screen Shot 2019-03-06 at 5.43.56 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a02ddee8-c6c6-43d9-91ab-30125da26fe8)

**Comment by amenity** [comment]
@sergiogcx - I am comfortable closing this if you are.
