### ISSUE TITLE
Police Oversight form: Final pass on content

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1223]
- Issues for any content updates
- Corresponding translation items to send to translators

**Comment by desigonz** [comment]
Hi content team (@srigdon @LauraTrujillo @annieszot @JeffCopy): I'm doing a final pass on OPO content before we send last changes to the translators, and a few style questions came up. I think it would be good to get these settled once and for all, and then I can incorporate these into Sarah's style and usage guide doc. Please weigh in with your thoughts. @srigdon, there are also some questions specifically for you!

#Style questions#
- [ ] Sentence case for all headings, correct? Should we also do sentence case for buttons?
- [ ] Phone number style: use parenthetical for area code or no? Ex. “512-972-2676” vs “(512) 972-2676”
- [ ] Time style: “9  am” or “9 a.m.”?

#For @srigdon#
- [ ] Does the complaint form PDF exist already (for “by mail”)? Does it need to be translated?
- [ ] “Placeholder official details” is the heading used for the first officer details when you add another officer—is this correct, or actually just placeholder text? Same with
- [ ] “We have received your complaint.” is the only page title with a period—remove, or was this intentional?

**Comment by JeffCopy** [comment]
--I think buttons are and should be different.

--Chicago says a.m., p.m., not am, pm, and I agree, but am not a zealot about it like I am for the Oxford comma.

--For area code presentation, Chicago expresses no preference. For frame of reference,  I looked and saw that NPR is non-parenthetical, but mass.gov is parenthetical. Coin toss, imo.

**Comment by desigonz** [comment]
Thanks @JeffCopy! Thoughts from others? Re: buttons, I'm inclined to do sentence case too. I'm a fan of "9 p.m." and parenthetical area code [e.g. (512) 972-2676] but not wedded to either.

@srigdon, I added a new fact checking question for you above.

**Comment by annieszot** [comment]
Thanks @desigonz 
-Yes, sentence case for all headings and buttons (https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98) - Google design standards sets sentence case for "almost everything" 
-Parentheticals - I second use for area code
(https://developers.google.com/web/fundamentals/native-hardware/click-to-call/?hl=en#other-click-to-call-features) 
- 9 am - no periods - I'm looking for the source that verifies best practice to drop the periods on the web...

**Comment by LauraTrujillo** [comment]
- More rationale for using sentence case for all headings and buttons: http://readabilityguidelines.wikidot.com/cta-and-buttons. 
Sorry, I made my notes in Desi's original comment. 

I'm also not wedded to either using or not using periods, and will go wherever the research takes us. However, my vote is currently with no periods since that is what gov.uk's style guide recommends: https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style (look under T for time)

**Comment by desigonz** [comment]
Thanks all for your great feedback!

Okay, here's what I think we should do:

- Sentence case for all headings AND buttons, e.g. "Add another"
- Parentheticals for phone area codes, e.g. (512) 972-2676
- No periods in time, but yes a space between the number and the pm, e.g. 9 am

I changed my mind on the time thing—different offices have crazy hours (such as Monday: 8 am to 12pm and 12:30 pm to 5 pm) and add those periods means higher character count.

**Comment by desigonz** [comment]
Thanks @annieszot @JeffCopy @LauraTrujillo  for your great feedback!

Okay, here's what I think we should do:

- Sentence case for all headings AND buttons, e.g. "Add another"
- Parentheticals for phone area codes, e.g. (512) 972-2676
- No periods in time, but yes a space between the number and the pm, e.g. 9 am

I changed my mind on the time thing—different offices have crazy hours (such as Monday: 8 am to 12pm and 12:30 pm to 5 pm) and add those periods means higher character count.

**Comment by JeffCopy** [comment]
Cool with me, except: It seems clearer/better to say “noon” than 12 pm.

**Comment by LauraTrujillo** [comment]
@JeffCopy @desigonz agreed re: noon vs 12 pm

**Comment by desigonz** [comment]
@JeffCopy @LauraTrujillo Sounds good, I've added it to the style guide.

**Comment by desigonz** [comment]
@amenity @easherma I've made almost all of the content changes directly into Github (both for the pages and for translations.json). There are a few that I couldn't find; they are definitely *not* high priority for launch, but they do follow our new style guide:
- [ ] Drag & Drop your files or Browse → Drag & drop your files or browse (lowercase) (on upload features on [Share your photos or videos](https://forms.austintexas.io/police-oversight/complaint/share-evidence)
- [ ] Add Another (button) → Add another (lowercase) (on [Tell us about the officer(s](https://forms.austintexas.io/police-oversight/complaint/officer-details) and [Tell us about any witnesses](https://forms.austintexas.io/police-oversight/complaint/witness-details))
- [ ] Update Page (button) → Update page (lowercase) (on [Review your answers before submitting](https://forms.austintexas.io/police-oversight/complaint/review-and-submit))

**Comment by amenity** [comment]
@desigonz - thanks a million. 

- Drag & Drop your files or Browse → Drag & drop your files or browse (lowercase) (on upload features on [Share your photos or videos] - #1182 
- [ ] Add Another (button) → Add another (lowercase) (on [Tell us about the officer(s)](https://forms.austintexas.io/police-oversight/complaint/officer-details) and [Tell us about any witnesses](https://forms.austintexas.io/police-oversight/complaint/witness-details))
- [ ] Update Page (button) → Update page (lowercase) (on [Review your answers before submitting](https://forms.austintexas.io/police-oversight/complaint/review-and-submit))
