### ISSUE TITLE
Bug: map doesn't always load

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1261]
Sometimes map picker doesn't load; difficult to replicate

**URL tested:** https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XS&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XS |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 1125 x 2436 px |
| Screen size | 5.8 in - 2.79 x 5.65 in |
| Viewport | 375 x 812 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/83ef8828c41f6ef86a91f8f86cac4cf9495a1c7c/realios_iPhone_XS.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/83ef8828c41f6ef86a91f8f86cac4cf9495a1c7c/realios_iPhone_XS.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XS&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment]
It can take a few seconds to load a map, even in regular computers. I do not know how long we waited until this picture was captured.

**Comment by desigonz** [comment]
@sergiogcx I'll keep an eye on this while testing other devices/browsers

**Comment by sergiogcx** [comment]
I have not been able to replicate, did try with two different devices (iPhone XS, and iPhone 6). I did see this once, but that's because I left the tab unattended.

<img width="1440" alt="screen shot 2019-02-21 at 11 50 16 am" src="https://user-images.githubusercontent.com/5282430/53190404-2498b200-35cf-11e9-9c8c-4db9b29408b4.png">

<img width="1440" alt="screen shot 2019-02-21 at 12 02 30 pm" src="https://user-images.githubusercontent.com/5282430/53191169-c10f8400-35d0-11e9-8f8d-b8f7e02add81.png">

**Comment by easherma** [comment]
I'm going to close this, feel free to re-open.
