### ISSUE TITLE
Figure out what to do with the site during rebuilds

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1308]
When content editors make a change, Janis is triggered to rebuild the site. Residents should not see the site down. 

- Tell people to stop editing (zero effort)
- Turn off automatic rebuild trigger and replace with manual rebuild (minimal effort)
- Actually figure it out

**Comment by oliver2g** [comment]
@sergiogcx can you estimate this? We're going to have to have this figured out for Janis 2.0 as well since OPO forms are moving there.

**Comment by sergiogcx** [comment]
Production for now will build to a different bucket, where will test it until we feel ready to commit to alpha.austin.gov

**Comment by sergiogcx** [comment]
The plan is as follows:

![Untitled drawing (1).jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4039233c-645c-48fa-83d5-22fd875d1c40)


Joplin prod will deploy to janis staging on every publish, keeping janis alpha prod protected. The only way to deploy to production is through Travis. Once pushed to production, Travis will issue a task to invalidate the cache in production, so that there will be no down-time.

**Comment by sergiogcx** [comment]
The deployments are working and cache is being invalidated, closing for now and raising new issues as they come.
