### ISSUE TITLE
Janis 2.0 footer fixes 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1317]
- [x] [Switch out City seal](https://github.com/cityofaustin/techstack/issues/1294) - _not MVP, but sure would be_  ✨
- [x] Project site link should be `https://` and be shortened to `http://projects.austintexas.io/projects/austin-digital-services-discovery/`
- [x] All links should have :hover: color #D9E8F6

English-only
- [x] Alpha.austin.gov link should be `https://`
- [x] Extra period after external site link
- [x] Remove extra "project site" text
![notes](https://user-images.githubusercontent.com/1463708/53436868-c3ebe980-39c1-11e9-8b95-843be06d8d1b.png)

Spanish-only
- [x] Should be "Alpha.austin.gov está en proceso de desarrollo. [Aprenda más sobre el proyecto](https://projects.austintexas.io/projects/austin-digital-services-discovery/)."
- [x] Alpha.austin.gov should link to `https://alpha.austin.gov`
- [x] External site icon should be on same line as "Austintexas.gov" 
<img width="479" alt="screen shot 2019-02-26 at 10 03 29 am" src="https://user-images.githubusercontent.com/1463708/53439401-930eb300-39c7-11e9-8ddb-c90d44894b92.png">

**Comment by amenity** [comment]
@desigonz @sergiogcx 
How would you recommend we translate "Alpha.austin.gov is a work in progress. Learn more on our project site." in the footer?

**Comment by desigonz** [comment]
Two options, not crazy about how the second turned out but it's a closer translation to the original:
- Alpha.austin.gov está en proceso de desarrollo. [Aprenda más sobre el proyecto](http://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/).
- Alpha.austin.gov está en proceso de desarrollo. Aprenda más en [el sitio web del proyecto](http://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/).

Also wondering if página web is better than sitio web.
