### ISSUE TITLE
Pick :hover: color for footer links

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1318]

**Comment by chasechenevert** [comment]
Let's use #D9E8F6 for hover when background is blue. It's subtle, but still meets contrast guidelines and should be enough to signal to the user that their cursor is over the link.

Just pasting the contrast check so that it's documented with this decision.

<img width="1265" alt="screen shot 2019-02-26 at 10 47 24 am" src="https://user-images.githubusercontent.com/7027270/53430405-0b6b7900-39b4-11e9-8e91-6122398a4625.png">
