### ISSUE TITLE
Develop plan for Funshop absentees

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#136]
Wednesday, 3/7, 1.5 hours

**Comment by LauraTrujillo** [comment]
Employees can make up Funshops I and II whenever the next session is being held because they are department agnostic. Employees making up Funshop III can attend the next department's Funshop but must review their own department's slide deck beforehand. They will participate in Funshop III's group activities for the other department. If there is time for individual work, they may work on content for their own department's services, and Funshop coaches will review with them.
