### ISSUE TITLE
Update OPO paper form PDFs

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1367]
Update the printable forms:

- https://forms.austin.gov/files/OPO_complaint-form_print_English.pdf
- https://forms.austin.gov/files/OPO_complaint-form_print_Spanish.pdf
- https://forms.austin.gov/files/OPO_thanks-form_print_English.pdf
- https://forms.austin.gov/files/OPO_thanks-form_print_Spanish.pdf

### To do
- [x] Consistent placement of CoA seal in all four forms

Office hours
- [x] Space between Monday and 8
- [x] Make am and pm lowercase
- [x] Move Sunday's "closed" over to align with Saturday

Phone number
- [x] Use complaint number? If so, change to (512) 972-2676

Physical Address
- [x] Add suite: 1520 Rutherford Ln., Suite 211

Required information
- [x] Change "time" to Date and time

Tell us what happened
- [x] Remove ", if known?"
- [x] Add a period after date and time
- [x] Add helper text under Date and time: Getting as close to the date and time as you can helps us with our investigation.

Contact preferences
- [x] Use numerals (aka digits) for two to four: ... 2 to 4 business days.
Your email address
- [x] Should read "Required if you want the confirmation number sent to your email."

### Then...
- [ ] Get translations based on ☝️and update Spanish forms

- [ ] Give PDFs to @sergiogcx to replace

**Comment by amenity** [comment]
@srigdon - would you upload the Word docs here? 🙏

**Comment by srigdon** [comment]
Updates to all four Word docs: 

- Made the logo consistent across all four
- Made contact info consistent across all four, including adding the fax number (I confirmed they do accept complaints that way and that's the right number), updating the phone number, and fixing the physical address
- Fixed all the check boxes so they show up in both .doc and .pdf formats 

English thank you form: 

- Edited the required information section
- Made all of the applicable edits in the checklist above 

English complaint form: 

- Made all of the applicable edits in the checklist above 

Not updated: Spanish translations unless stated above. 

[OPO_thanks-form_print_Spanish.docx](https://github.com/cityofaustin/techstack/files/2964670/OPO_thanks-form_print_Spanish.docx)
[OPO_thanks-form_print_English.docx](https://github.com/cityofaustin/techstack/files/2964671/OPO_thanks-form_print_English.docx)
[OPO_complaint-form_print_Spanish.docx](https://github.com/cityofaustin/techstack/files/2964672/OPO_complaint-form_print_Spanish.docx)
[OPO_complaint-form_print_English.docx](https://github.com/cityofaustin/techstack/files/2964673/OPO_complaint-form_print_English.docx)

**Comment by amenity** [comment]
Thanks, @srigdon!
As far as the Spanish translations, what still needs to be done?

**Comment by srigdon** [comment]
[OPO_thanks-form_print_Spanish_needs-translation_3-14-19.docx](https://github.com/cityofaustin/techstack/files/2967641/OPO_thanks-form_print_Spanish_needs-translation_3-14-19.docx)
[OPO_thanks-form_print_English_3-14-19.docx](https://github.com/cityofaustin/techstack/files/2967643/OPO_thanks-form_print_English_3-14-19.docx)

@amenity ^ I deleted both the English and Spanish thanks docs that I posted yesterday because I found another error in the English one (it mentioned complaint, just needed a quick edit). The Spanish thanks form needs translation everywhere I highlighted text. I think the only thing the Spanish complaint form needs is a translator to check it against the English complaint form for anything I might have missed, general QA.
