### ISSUE TITLE
Police Oversight form: Complaint form review and submit page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1386]
- [x] Close all accordions by default.
- [x] Remove ", if known?"
- [ ] Remove/hide "Describe your experience with the Austin Police Department."
- [ ] Remove/hide "Type in the location or drag the map to the location." - should only be shown if if the user clicks edit.

**Comment by amenity** [comment]
@easherma - what size should this be?

**Comment by easherma** [comment]
I’d say this is an L

**Comment by easherma** [comment]
So accordions are closed by default now, but this other stuff is going to require some more thought/coding. Because what is showing are the titles, by default. I'm not sure that default behavior that is good to remove because there are a variety of contexts in which something may not make sense otherwise...

**Comment by easherma** [comment]
@briaguya i'd be interested in your take on this

**Comment by easherma** [comment]
Good enough for now! @toribr approved!
