### ISSUE TITLE
Schedule rest of rubric run throughs 

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#139]
Remaining departments (not including first 4)
Equity+CPIO consultants+content team
2hr sessions each

**Comment by LauraTrujillo** [comment]
We pivoted on this- scoring departments w/ Equity and then having Jessica King review our rubrics. Instead of having meetings with Equity, each department, and their consultants, we are sharing the scored rubric with the departments (via an email from Adam) and letting them know we are happy to discuss it if they have any questions.
