### ISSUE TITLE
Design "An official website" mobile header

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1443]

**Comment by chasechenevert** [comment]
## VisDesign: Security Banner MVP
- XD Prototype: https://xd.adobe.com/view/ee85fa55-9fa0-4d0d-6800-fee0d2d6e33c-98b4/
- XD Spec: https://xd.adobe.com/spec/45d349f3-c18d-4231-6789-0b069cfaf74c-33e2/

<img width="878" alt="screen shot 2019-03-07 at 11 20 53 am" src="https://user-images.githubusercontent.com/7027270/53975701-18325000-40cb-11e9-9e2b-be210b1630c4.png">

### There have been a few slight changes to create parity. 
- Removed the "Here's how you know" link because we already use the "plus" "minus" UI metaphor for expanding and contracting accordions. Additionally, that extra "Here's how we know" text has to break to another line and I don't want this banner take up so much height
- Vertical height for mobile and desktop is: 40px
- I've kept type sizes the same across both formats as well
