### ISSUE TITLE
Discuss Process Page content type

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1445]

**Comment by toribr** [comment]
Prior to this meeting, let me get some things together that will help facilitate discussion. In order to do that, it would be ideal if a content person could pull together a set of pages (ideally from content currently being worked with) that might comprise, or nearly so, our concept of a "collection". @LauraTrujillo ?

**Comment by LauraTrujillo** [comment]
@toribr I can do that. Do we want to stay in Public Health, or revisit the ole residential permitting process?
