### ISSUE TITLE
## How we store and use your data- Check for Spanish translation

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1539]
@desigonz I made this change in Joplin (in English.) Can you make sure that the Spanish translations are still true?

## How we store and use your data
- [ ] Remove "department" in the first line, to read: "When you file a complaint against an Austin Police officer..."

_Originally posted by @LauraTrujillo in https://github.com/cityofaustin/techstack/issues/1342#issuecomment-470271353_

**Comment by desigonz** [comment]
@LauraTrujillo What's your rationale for taking out "Department"? Not sure it'll read correctly without it because "officer" goes first in Spanish, so I vote for keeping it en español. 

"Cuando usted presenta una queja contra un oficial del Departamento de Policía de Austin"
vs
"Cuando usted presenta una queja contra un oficial de Policía de Austin"

**Comment by LauraTrujillo** [comment]
@desigonz that was a request from the OPO team for the English translation, so if it works better in Spanish, I say keep it!

**Comment by desigonz** [comment]
great, closing this one!
