### ISSUE TITLE
Design System Super Issue

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1628]
Using this to braindump/prep for making a design system

First and foremost I think it makes sense to implement this as a storybook with stateless react components, as well as non-react html using the same styles.

For purely display components the big difference will be actually using properties on the react components, and instead putting placeholder text in the html.

For Example:

SCSS/CSS:
```
.example-text-div {
  background: red;
}
```

HTML:
```
<div class="example-text-div">
  Example Text
</div>
```

React:
```
const ExampleText = ({text}) => (
<div className="example-text-div">
  {text}
</div>
)

<ExampleText text="Example Text" />
```

Things will get a little more complex when we're dealing with components that we need to get data _out_ of as well, and I think is best handled on a case by case basis.

The next big thing is to actually break down and figure out what components belong in the design system. By going through Janis page by page we can figure out what makes sense to keep in Janis specifically, and what makes sense to bring out into a design system.

**Comment by easherma** [comment]
@pibemillo do you have any thoughts on this to add?

**Comment by easherma** [comment]
Related: https://github.com/cityofaustin/techstack/issues/870

**Comment by pibemillo** [comment]
@easherma I adopted this approach with the `ContextualNav`, styling and authoring it in storybook first before abstracting it and wiring up with data. Moving forward, this can help inform and drive the creation of a design system.

Since most of Janis 2.0 has consisted in refactoring existing components and applying evolving MVP designs to what was already there, it is hard to retroactively apply this to rest of our components. IMO it would require lots of refactoring work which would include updating design/dev naming of components (i.e. Tiles, also commonly referred to as Cards) and establishing an inventory — this should eventually be reflected in storybook, at the very least legacy components should no longer be there.

**Comment by desigonz** [comment]
I'm closing this unless y'all have any objections?
