### ISSUE TITLE
Change email "required if you want the confirmation number" language 

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1688]
Assigning to @srigdon since you're the OPO content queen, but maybe this is something to scope out with @oliver2g.

On the [OPO form review page](https://forms.austintexas.io/police-complain/about-you), we have language under the "Email address" field that says "Required if you want the confirmation number sent to your email." This is actually no longer true! They can have a confirmation email sent to them after the fact. 

Do we want to:
- delete this here
- add "(Optional)" to "contact preferences"
- add language on the confirmation page that says that if you enter your email here, we won't record it anywhere?

![opo-required-email.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/30c6bffb-b875-46a5-9f99-dbd961b07d5e)

![opo-required-email-2.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/4c06c410-25ab-44e9-baf2-adc8a6809f2a)

**Comment by sergiogcx** [comment]
What should the language be?

**Comment by oliver2g** [comment]
@sergiogcx it was decided at Content backlog grooming to remove that sentence ("Required if you want...") on both the English and Spanish form.

**Comment by srigdon** [comment]
After discussing with @oliver2g and @desigonz, we've decided to: 
- Delete the line, "Required if you want the confirmation number sent to your email," in English and Spanish. @sergiogcx 
- Add language spelling out for this section that all contact preferences are optional. (creating a separate issue) 
- Add to the confirmation page language explaining that we do not store your email address at this. (creating a separate issue)

**Comment by sergiogcx** [comment]
Thanks for looking into this, but not clear to me what the final action will be. Are we going to replace that text with something else, or are we going to remove it altogether without replacement?

Cheers,

**Comment by oliver2g** [comment]
@sergiogcx the decision is to just remove the wording in both English and Spanish. That will be sufficient to close this issue. 1695 and 1696 will address other related changes.

**Comment by srigdon** [comment]
Sorry for creating confusion on this. @oliver2g just as you were commenting here I was closing #1695, because it's basically a duplicate. I also talked to @sergiogcx and clarified that the user can't really submit their email address and remain totally anonymous, even if just on the confirmation page. They can copy down the confirmation number and track their complaint that way, or ask someone to call the office and track it for them, but we do store logs of the email addresses entered on that page on AWS. We don't share these logs with other offices, but even just a few people at the ODD having the ability to view that info breaks the privacy of the user. I'll add copy to clarify this to users in #1696. 

Here's my copy change for the "Contact preferences" section of the "Tell us about you" page: 

- Keep the text next to the checkbox the same. 
- On the next line underneath the checkbox text, add this helper text: "Optional. If you enter your contact information here, it will be shared with the Office of Police Oversight and you will no longer be anonymous. If you want to remain anonymous and track your complaint, skip this section and write down the confirmation number on the last page of this form." 
- Delete "Required if you want the confirmation number sent to your email." under "Your email address". 
^ @sergiogcx 

Related considerations: 

- This would likely benefit from a design review, as it's a lot of text, and I'm not sure how it should stand out. That's related to the larger question of when we'll be able to address form improvements overall -- @oliver2g, should we create an issue for this? 
- @oliver2g @LauraTrujillo How should we handle Spanish translation for this and any other copy changes going forward?

**Comment by oliver2g** [comment]
@srigdon the copy changes and any associated design changes would need approval from OPO first. I think the best thing is to:
1. Remove the line "required if you want the confirmation number sent to your email" (both English and Spanish forms). Then close this issue (1688).
2. Put the other copy changes mentioned by @srigdon in 1696, and move that issue to the backlog. Also assign to Team: Design for UX input.
3. If we feel strongly enough about the copy changes, we can escalate it to OPO

**Comment by oliver2g** [comment]
@sergiogcx i estimated this as a small and added it to the next sprint. Let me know if you have any issues with this

**Comment by sergiogcx** [comment]
Splendid,

Is this what we are looking for?

Complaint Form:
(eng) https://opo.austintexas.io/police-complain/1688-sg-removerequired/about-you
(spa) https://opo.austintexas.io/policia-queja/1688-sg-removerequired/acerca-de-usted

Thank-you Form:
(eng) https://opo.austintexas.io/police-thank/1688-sg-removerequired/about-you
(spa) https://opo.austintexas.io/policia-agradezca/1688-sg-removerequired/acerca-de-usted

Review so I can have this merged as soon as possible ... 

@oliver2g @srigdon

**Comment by sergiogcx** [comment]
Merged to master, needs review.
