### ISSUE TITLE
ODD Newsletter - July

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1689]
Create a draft of the ODD Newsletter for April or May. 

- - - 
Notes from meeting with Shannon and Jeff, 4/10/19: 

What’s the ideal form and timing of the newsletter? 
- SDL - what’s been done, what’s coming up (snapshot of 2 wks back and 2 wks forward or so)
- Austin.gov - same as above
- Special culture news that comes out of ODD, discussion of our philosophies 
- Events and training we’re running 
- Education about what we do and our approach: acronym explanations, what is UCD, equity, accessibility, etc. 
- Here’s what we’re reading. 

Who’s our audience? 
- People at the City who are tasked at their department with digital transformation. Also, people who see the need for process change and/or digital transformation. 

Who does what? 
- We produce the content and do an editing pass. 
- Then and we lob it over to Shannon and Sara for polish and distribution. 

What’s the purpose? 
- educate/communicate about our work (past, current, future), 
- spread ideas and culture change, 
- connect with interested parties across the City

**Comment by wilhitem** [comment]
Do y'alls have an approval process for the newsletter? No big deal if its not formal yet...but just want to make sure you schedule time for me to review and get it set on my calendar since i am hard to nail down :)

**Comment by shandoaustintexas** [comment]
Not formal yet, but you are one of the steps for sure. Do you have a preference on how you like to get these kinds of items and how much lead time we should typically account for?

**Comment by wilhitem** [comment]
oh something to also think about...and don't slow down this edition for it. Is there a highlight section on something one of our partners is doing or other city staff whether working with us on it or completely separate? I think people will be excited to be highlighted and more likely to share. Maybe can be part of the culture news section? Thinking it will be helpful if we can point out others at the city doing amazing things so they feel a connection with us.

I'm sure y'alls have heard stories...ones off the top of my head:  ATD's vendor intake process. Or Clary's team's work around scooter data/etc. Or Kymberlie from the history center and her work highlighting people of color. Or the puppeteers upstairs! Or APL's director, Roosevelt, and his decision to turn wifi back on at libraries at night because that's the only access some community members have (sitting in parking lots after school/work to use the free wifi). Or equity office's grant work prototyping more equitable access to grants. 

Also, totes ok to say not a good idea for any reason :)

**Comment by desigonz** [comment]
By sprint 35:
- [ ] @srigdon  review for timeliness
