### ISSUE TITLE
Create a plan for publicizing the user testing sign-up form

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1702]
Before we can successfully promote the user testing sign-up form for alpha.austin.gov and any other projects, we need to know which audiences we want to target. From which groups of people do we want feedback on the website? We could focus on a handful of user journeys we've already identified and spell out the audiences for each of them. From there we can answer questions such as, when and how often do we publicize the sign-up form, and what channels do we use to publicize it?

**Comment by kriskristin** [comment]
This is a great question and I'm glad y'al brought it up. 

Within the screener we ask a question "Do any of the following questions describe you?"
And the list looks like this:
![Screen Shot 2019-04-25 at 3.50.43 PM.png](https://images.zenhubusercontent.com/5c7d9d4fd74bd07972c5327e/df06473e-70cb-4f15-ac29-842346a352ad)

This list is based on the personal types that are identified in this document:
https://docs.google.com/document/d/1pI2vdbAC4gpupVU02GLo6qGr6nsEJGuEORnVHJqs6JM/edit?usp=sharing

This list may change as the city and its residents change. 

We also ask the current zip code, age, gender and how long they have lived in Austin. 

The form is translated into Spanish and we should get the ball rolling on other languages. But I am reluctant to do that without the capability to test in those languages. 

##### That being said, we would like the people we recruit to be from all types of residents in Austin. I would say that we try to engage in diverse manners and locations so that we can try and capture all residents. 

We have and or will conduct the following types of user research with residents:

Usability tests
Tree tests (online)
User Interviews 
Card Sorting
Translation content testing

This list might grow as the needs of our work changes.

**Comment by kriskristin** [comment]
@srigdon I added some notes here. I would be interested understanding other points of view about how we should tackle this. I'm super grateful for any type of help that goes towards publicizing the our user research needs.

**Comment by kriskristin** [comment]
Met with @srigdon and @sarafperalta about this issue on 6/27/19

Notes are typed up here: https://docs.google.com/document/d/1_9Th_SxRe9ZVNZAcaR9ujOcBOZxhKirvF4TdIrierso/edit?usp=sharing

We are still needing to strategize possibly getting some graphics and going out to community events that the city puts on. Getting a lit of community events that they city is involved in and targeted demographics of those events would be great. Is there an office that handles that?

**Comment by kriskristin** [comment]
We published a post on medium about user research in our office. 

Current work done on this is:
1. Gathering busy times and events at local libraries.
2. Working with community engagement to get out to events in the community.
3. Producing marketing materials for recruitment. This could be posters, stickers (like I voted), etc.
4. Turning the medium post into a page on Alpha. :)

Also, want to look at replacing google forms with mail chimp. It seems to have more marketing type controls available.

**Comment by kriskristin** [comment]
Week of 7/22/19 - Single social media blast with the help of Sarah Peralta - very successful

7/24 - Met with CPIO team to discuss a plan to fill in the perceived gaps of the participant database 
*Action plan from them*
Tasks for me:
Identify how our office is determining the targeted participants and what the persona traits are.
Questions to ask: 
Who will be most impacted?
What voices need to be elevated?
Assess my sign up form based on targeted residents
Identify gaps in my user pool based on targeted residents

Future things to do: 
Y'all: Send me to resources that can fill the gaps identified in our user pool
Me: Create a packet to send out to tabling events around the city

7/30 - Recruitment table at Manchaca Library

**Comment by kriskristin** [comment]
After first pass at recruitment we have reached a pool of 700 participants that have signed up to participate in research. 

We will recruit via social media again and then assess the participants based on the meeting with CPIO.

**Comment by kriskristin** [comment]
#### Next steps: 

- [ ] Make some adjustments to the screener

- [ ] Posters for foundation communities, libraries, etc

- [ ] Research mail chimp

- [ ] Translate all social media recruitment into spanish and push to a spanish speaking population.
