### ISSUE TITLE
Begin conversation around testing navigation

### ISSUE THREAD

**Issue by kriskristin** [cityofaustin/techstack#1761]
##### To ensure empirical navigational structure we should begin testing the navigation early so that we have time to work through needed changes.
I recommend using tree jack 

##### Tasks:
- More fully understand the card sorting exercise that led to the current nav.
- Determine if we want to run a baseline tree test (we should) on Austintexas.gov in order to have some thing to measure against?
- Present recommendations to at sprint review.

##### Questions:
- Is the current nav proposal, the only one that came from the card sort study?
- Do we have a complete content audit? @LauraTrujillo

**Comment by LauraTrujillo** [comment]
@kriskristin Essentially, yes- the current nav proposal is the only one that came out of that card sort study. Partially because we were only working with one department at the time. 

We don't have a complete content audit for the entire austintexas.gov website (shudders) but I do have audits for public health and resource recovery. Let me know if those would help.
