### ISSUE TITLE
Janis/Joplin - approve/verify Spanish translations currently in Joplin

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1842]
I used google translate to fill these in, they need to be updated/approved:

For any of the ones that can be updated in Joplin, please just go ahead and update it there and then change the checkmark to approved.

For anything that can't, we'll need to make some quick changes to the locale files in Janis. If you create an issue in the form: "Janis - translation update: oldText -> newText," it will be really easy for a dev to address with a quick ctrl-f

| English  | Español | Approved | Can be updated in Joplin? |
| ------------- | ------------- | ------------- | ------------- |
| Get a birth or death certificate  | Obtener un certificado de nacimiento o defunción  | ❌| ✅|
| Find free condoms and learn other ways to prevent HIV | Encuentra condones gratis y aprende otras formas de prevenir el VIH. | ❌|✅|
| Health Records & Certificates | Registros y certificados de salud | ❌|✅|
| Healthcare & prevention | Cuidado de la salud y la prevención | ❌|✅|
| Disaster & safety relief | Ayuda para desastres y seguridad | ❌|✅|
| Coming soon | Próximamente | ❌| ❌ |
| Visit austintexas.gov for the current city website. | Visita austintexas.gov para el sitio web actual de la ciudad. | ❌| ❌|
| More about the alpha.austin.gov project. | Más sobre el proyecto alpha.austin.gov. | ❌| ❌|
| Departments | Departamentos | ❌| ❌|
| Birth and death certificates | Certificados de nacimiento y de defunción | ❌| ✅|
| Learn more | Aprende más | ❌| ❌|
| Get immunizations for you and your family | Recibir las vacunas para usted y su familia | ❌| ✅ |
| Household waste | Desechos domésticos | ❌| ✅|
| Top services | Servicios principales | ❌| ❌|
| All services | Todos los servicios | ❌| ❌|
| Related to (contextual nav, the related links here are topics) | Temas relacionados | ❌| ❌|
| Offered by (contextual nav, it's a dept) | Presentado por | ❌| ❌|

this is @desigonz throwing in an error message for OPO (low priority): let's get an official translation for the below.
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/b892703d-6315-44de-990b-7a708fda8a4e)

**Comment by desigonz** [comment]
Related: #1496 on translating the privacy page

**Comment by chocomochi** [comment]
- Overall it's a nice translation with some rough edges. I deleted all the periods, double check if you need them back.
- It's a bit ambiguous whether you're using some impersonal *visit X place* (like a button to click) or *you there, go visit X place* (telling readers to do something). Both versions are provided with minor grammar changes, so pick one set for a consistent translation.
> Obtener un certificado de nacimiento o defunción OR Obtenga un certificado de nacimiento o defunción
> Encontrar condones gratis y aprender otras formas de prevenir el VIH OR Encuentre condones gratis y aprenda otras formas de prevenir el VIH
> Registros y certificados sanitarios:x:
- A bit nitpicky, I would use these words.
> Asistencia sanitaria y prevención:x:
- It sounded a bit like self-care instead of doctor related care, unless that was the point?
> Ayuda para desastres y seguridad:heavy_check_mark:
> Próximamente:heavy_check_mark:
> Visitar austintexas.gov para ver la página web de la ciudad OR Visite austintexas.gov para ver la página web de la ciudad
- I took away the *current* part when translating, unless you're running a legacy website at the same time, you're telling people to visit the one and only city site.
> Más sobre el proyecto alpha.austin.gov:heavy_check_mark:
> Departamentos:heavy_check_mark:
> Certificados de nacimiento y defunción:x:
- Same as the first line, it's (birth or death) certificate.
> Saber más OR Aprenda más
> Conseguir vacunas para usted y su familia OR Consiga vacunas para usted y su familia

**Comment by easherma** [comment]
@desigonz I see your note above, but didn't we address that OPO translation? It seems like a bad place to have this in a Janis/Joplin thing since the translation is in a different project.

**Comment by desigonz** [comment]
@easherma That's more of a note to myself/other content folks to include it for an official translation when we send in all the things to the translators. I would then make an issue to update that separately in OPO. 

I saw this issue as "content team to compile all of the things we need in Spanish (and update in Joplin when possible)," not "devs implement all the things in Spanish." I could be reading this wrong. Content is meeting with @oliver2g tomorrow to chat out all of the things we need to complete for the Janis 2.1 milestone, which will include all of the translations to-dos, so we'll have more issues hashed out then.

**Comment by briaguya** [comment]
@desigonz I was kinda seeing this as a both thing, originally intended to be for janis/joplin stuff but if we don't have a good source of truth for OPO form stuff that needs translations too we can pull that in here. Just a decent source of truth for three questions:
1. Do we have a spanish translation for the thing? (Content)
2. Is that spanish translation in our app? (Devs)
3. Is it working for residents? In prod? (Both, QA teamwork ftw!)

**Comment by desigonz** [comment]
Hey @briaguya—I threw all of your notes into a [Google spreadsheet](https://docs.google.com/spreadsheets/d/1HnKT-FnLAeLc9YT__pUAk2UdMEI1opwfPuzVFxct8NI/edit?usp=sharing) and added a lot more. 

I did an audit of all content on staging. For pages, I'm just including page title, but will later add links to the full, finalized content (as it gets approved). I'm using this as our source of truth to document where we are in terms of approve English copy and Spanish copy for the Janis 2.1 release. Your table above is amazing but it was starting to become unwieldy, plus I think this will be easier to turn into something we can send to the translators. 

Related: [#1884](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1884)

**Comment by desigonz** [comment]
@briaguya Thanks for pointing me to the .yaml files with the translations. I've added in missing translations for about 5 pages; for the others, I didn't find translations there.  

- In the [Google doc](https://docs.google.com/spreadsheets/d/1HnKT-FnLAeLc9YT__pUAk2UdMEI1opwfPuzVFxct8NI/edit?usp=sharing), I've written up placeholder translations for those hardcoded fields where we don't have any translations yet. You can use them in the interim for now if you'd like, and then we can update them when we get the official ones.
- In the Google doc, the pages missing translations entirely are highlighted in pink. I'll unpublish those pages before Janis 2.0 MVP goes live (want to just double check with Laura next week that we really truly don't have those translations). 
- All of the pages now have a new description field, which means we're missing Spanish-translated descriptions for those 5 or so pages that are otherwise translated. I can work on coming up with placeholder translations tomorrow and then the content team can update those when the translations come in. That way, we don't have to unpublish _all_ of the content for the release.
- Same goes with any missing topic collection/topic titles. I'll work on placeholder translations and update in English. 

Also, for all of those hardcoded translation copy changes—if you show me where the translations live in the repo, I can make the changes on a branch and have y'all review and merge my PR.
