### ISSUE TITLE
Staff friendly name for Janis/Joplin 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#1860]
While editing Content Governance doc, noodled on Eric's suggestion from Slack: 
https://docs.google.com/document/d/1RTj0nrl5xufueC8fjoktPy_GwBKdICYD4ecI04CBaMQ/edit

"random thought: as we get closer to wider city adoption of janis and joplin....we should probably stop calling them janis and joplin. Or rather, janis and joplin are the open source projects that power the resident-facing site and the authoring interface, respectively."

Source of Truth (thanks @desigonz!)
"Wagtail is the open source project that underlies Joplin" 
"Janis is the open source project that powers the resident-facing site"
"Joplin is the open source project that powers the authoring interface." 

Our task, come up with a staff-friendly name. 
Assigning me, @desigonz and @easherma

**Comment by easherma** [comment]
Yes! 

FYI, the model in my mind is something like what Mapzen did: 

https://www.mapzen.com/products/

Mapzen had many products, like Mapzen Search. Mapzen Search relies primarily on their open source geocoder, called pelias. The product is their customer-facing implementation of their open source project. Anyone can use, contribute to, or improve Pelias, since it is open source. Hope that helps! Happy to discuss more in person. 

This might be something to ping Marni on too at some point, as some it ties into organizational strategy.

**Comment by annieszot** [comment]
Thanks, @easherma ! Meeting proposed/sent to regroup/next steps Monday, May 13 before Odd Flock sync where we can ping Marni
