### ISSUE TITLE
Navigation is not intuitive; going "back" to pages I never visited

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#1873]
The navigation in from the home page to services and back is not intuitive. Example:
1. navigate to https://janis.austintexas.io/
2. Click the "Get a birth or death certificate" tile under Check out City of Austin Services.
3. On the "Get a birth or death certificate" page, there is a navigation arrow that goes "back" to Birth and death certificates which in turn goes "back" to Health records and certificates. However, I never visited either of those pages, so it seems strange to go back to them. This would only make sense if I navigated to the "Get a birth or death certificate" page through the hierarchy instead of jumping directly there from the home page. The only way to get back to the home page is to use the browsers back button.

**Comment by chasechenevert** [comment]
I think the left-facing arrow icon is signaling to the user that they’re going “back” to a previous page they were on (re: browser back/forward buttons) as opposed to traveling through the IA to the parent topic via this contextual navigation structure (our goal).

### **Idea 1** orient arrow upwards to imply traveling “up”
this probably doesn’t solve the issue though since chevrons and arrows usually imply progress or motion, which we are not doing in this particular context

<img width="879" alt="Screen Shot 2019-05-15 at 1 11 32 PM" src="https://user-images.githubusercontent.com/7027270/57799929-cb47a700-7715-11e9-9e7d-c844193d6ffa.png">

### *Idea 2* remove the arrow icon 
i think it’s stronger this way; one less icon for the user to interpret. I don’t think we lose any valuable information by removing it either

<img width="880" alt="Screen Shot 2019-05-15 at 1 12 39 PM" src="https://user-images.githubusercontent.com/7027270/57799922-c682f300-7715-11e9-868e-f5515710f00a.png">

**Comment by easherma** [comment]
+ 1 to Idea 2

**Comment by chasechenevert** [comment]
@toribr and I both agree to remove the arrow
