### ISSUE TITLE
As a content manager, I want to be able to share a draft from Wagtail so that I can get approval from depts.

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1930]
The "share" link within wagtail should create a viewable link that can be emailed to others, which will show them what that page looks like on Janis, prior to being published.

**Comment by easherma** [comment]
It looks like the current behavior is to copy a link of a preview build which could then be sent along. 

Two things I noticed: 
* It's really easy to miss that this happens from a UX perspective. 
* The builds being linked to are the old alpha builds, I think we'll need to wire up to the new build preview process(pending).

**Comment by briaguya** [comment]
@easherma re: your two things.
1. The preview button opens a preview link in a new tab. The share button copies the preview link to the clipboard.

2. Having production joplin create links using production janis makes perfect sense. There shouldn't be any new wiring required, we just need to update prod janis.

**Comment by toribr** [comment]
@easherma There is a UX design that was created but not faithfully implemented regarding the share link. 
![Screen Shot 2019-05-15 at 7 28 48 AM](https://user-images.githubusercontent.com/3790067/57775646-1d230980-76e3-11e9-8e59-0a6518ef7097.png)

**Comment by briaguya** [comment]
@toribr I remember running into issues implementing that UX due to a couple issues:
* When generating the link we wanted to make sure any changes that weren't saved in the latest draft were saved first.
* When saving a draft, it forces a page reload.
* When reloading a page, it's quite difficult to make the popup look decent.

@easherma I'm pretty sure there's some code hanging around in joplin (possibly just commented out) implementing the "url copied" popup, but it definitely doesn't look close to as nice as the design

**Comment by toribr** [comment]
Perhaps we can work out some timing issues, like let the page reload before showing the popup? Or something to that effect. Might require a loading notification and then popup?

**Comment by easherma** [comment]
Misc notes:
Mobile Preview, Share Draft, and Preview button all show the same link/build. It might be kinda confusing since they all show the same thing in different ways. 

Share Draft just copies the URL to clipboard
Preview opens a build with the draft data put into production janis
Mobile Preview shows this same build, but just in a smaller iframe instead of new tab. 

TODOS:
* Adjust the timeout animations to make the share notification more obvious
* Explore ways to make this url constantly visible (@briaguya and I were thinking right in the mobile preview might be a good spot)
* Maybe play around with having a desktop preview side by side (basically make mobile preview responsive/dragable instead of fixed, or maybe on another tab)

**Comment by easherma** [comment]
@toribr the current behavior is to show the popup after page reload, just FYI

**Comment by toribr** [comment]
While I appreciate brainstorming what is possible, dev should not be exploring design solutions that have not been designed:
- Explore ways to make this url constantly visible (@briaguya and I were thinking right in the mobile preview might be a good spot)
- Maybe play around with having a desktop preview side by side (basically make mobile preview responsive/dragable instead of fixed, or maybe on another tab)

**Comment by easherma** [comment]
https://github.com/cityofaustin/techstack/issues/1957 helps make this a little more obvious
But we could: 
   * tweak the pop-up design to match spec
   * play with the timing of the url copied animation so that it fades out after the banner fades out

**Comment by easherma** [comment]
@toribr this is kinda random, but re-reading your initial description makes me think eventually we should explore making a button that sends an email with the draft url in the body

**Comment by toribr** [comment]
We do need to better understand how this gets used. A URL allows the author to use the tool of their choice to share - it might not always be email. Pasting a URL was the easiest thing to implement and had the least ramifications. I feel like once you attach it to an email, then you have to start managing email addresses, and I didn't want us to get into that.
