### ISSUE TITLE
Joplin - Functionality - Tables in rich text blocks

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1935]
As a content editor, I need to be able to add basic tables to a service or info page, so that I can sensibly display fees charts or similar content.

Adding the table component to service and/or info pages. May require additional design issue?

**Comment by easherma** [comment]
A barebones table shouldn't be too hard to implement as an MVP. It just won't be pretty.

**Comment by briaguya** [comment]
@easherma I don't think it'll be easy to implement even in a not pretty way. I think our best bet would be to try to extend the rich text editor instead of switching out all of those into streamfields and needing to split up our text blocks every time we want to add a table. http://docs.wagtail.io/en/v2.5.1/advanced_topics/customisation/extending_draftail.html

I also found: https://docs.wagtail.io/en/v2.5.1/advanced_topics/customisation/rich_text_internals.html
where it's mentioned:
For example, a third-party Wagtail extension might introduce table as a new rich text feature, and provide implementations for the Draftail and Hallo editors (which both provide a plugin mechanism).

I did a bit of googling but couldn't find any third party extensions that introduce tables for richtextfields.

**Comment by briaguya** [comment]
![May-15-2019 09-24-13](https://user-images.githubusercontent.com/6384156/57783261-7004bd00-76f3-11e9-8075-239b4e4d2a13.gif)

I am quite opposed to trying to switch to streamfields to handle tables instead of implementing it into our richtextfield

**Comment by oliver2g** [comment]
@toribr can you add some acceptance criteria to clarify what a "basic" table is from a content editor perspective?

**Comment by easherma** [comment]
@briaguya this thread might not be the best place, but I'd really appreciate hearing more about your opposition to using StreamFields.

**Comment by briaguya** [comment]
@easherma using streamfields causes multiple issues:
1. Lots of dev work, everywhere we want tables to be allowed we need to change our models to support them. Then we'd need to update all of the queries in Janis. Overall just a lot of code that we'd need to change.
2. It would change the flow for editing what most users would want to be a fairly simple text box (with some rich text features). I don't like the idea of replacing any wysiwyg editors we have with a stream field whenever we need to add a feature to the editor, which is mostly because...
3. I'm just overall not a fan of using streamfields from a UX stand point. They make sense for certain data types but my general attitude has been to use them sparingly.

**Comment by briaguya** [comment]
I've deployed some POC stuff so Janis is building tables against a PR app of joplin:

Joplin pr app content with tables in it: https://joplin-staging-pr-234.herokuapp.com/admin/pages/7/edit/

Janis PR app page with tables in it: https://deploy-preview-406--janis.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/find-free-condoms

Janis PR: https://github.com/cityofaustin/janis/pull/406
Joplin PR: https://github.com/cityofaustin/joplin/pull/234

Screenshot of using markdown in the Joplin rich text editor:
<img width="1123" alt="Screen Shot 2019-05-17 at 4 57 33 AM" src="https://user-images.githubusercontent.com/6384156/57920306-5fbe2080-7860-11e9-8936-8cbef6ee712a.png">

**Comment by briaguya** [comment]
Closing this because I've split it into a few more issues:
* Implement basic functionality in Joplin so tables can exist at all: This issue.
* Implement tables in Janis that work with Joplin changes from this issue: https://github.com/cityofaustin/techstack/issues/2064
* Implement table editing in a way that matches design goals: https://github.com/cityofaustin/techstack/issues/2063

**Comment by desigonz** [comment]
When adding a markdown table to Joplin, use this tool to generate table markdown.

When entering into Joplin, use Shift+Return (on the keyboard) so the markdown stays as all one block.
