### ISSUE TITLE
Design - "Meet our director(s) gendered localization

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1941]
- [x] design to deliver mocks for how content editors choose gendered language in Joplin

----

On the department pages:

Right now we just have "Meet our director," and "Meet our directors."

To properly handle this we should have "Meet our director (masc)," "Meet our director (fem)," and "Meet our directors"

**Comment by desigonz** [comment]
- [ ] @toribr to work with content team to decide what the UX of selecting masc/fem looks like on Joplin

**Comment by toribr** [comment]
![Screen Shot 2019-09-26 at 11 37 59 AM](https://user-images.githubusercontent.com/3790067/65719820-3ada8500-e06c-11e9-8514-8c4923fd166c.png)
I'm thinking the simplest solution would be to add a female/male radio on *the spanish* version only, because it's not needed anywhere but there. Presumably then, the author that was cutting/pasting the spanish translation would also need to make this selection so that the system would know which labels to render on Janis. Note that Joplin would need three different spanish labels: one for a female director (fem); one for a male director (masc); and one for when there is more than one director (masculine plural).
