### ISSUE TITLE
Revision history call to action buttons

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1963]
**Describe the bug**
When reviewing an old version of the page via the revision history tool, all of the action buttons have the same text.

**URL**

**To Reproduce**

1. Go to Joplin and edit a page
2. Select "all revisions"
3. Pick an older version and select "review this revision"

**Current behavior**
all three call to actions say "Replace current draft"

**Expected behavior**
Each button has distinct, accurate call to action

**Screenshots**
![image](https://user-images.githubusercontent.com/5839508/57957066-ab081b80-78c0-11e9-9b00-01d2478bdaba.png)

**Comment by toribr** [comment]
These buttons should say "Share current draft" "Preview current draft" and "Replace Current Draft" or maybe "Use this draft" or "Update with this draft". Not sure design is really needed here, but some consensus about word smithing the replace button would be needed.

**Comment by easherma** [comment]
I will update the copy, but I think we need to think this through further from a UX perspective when we have a moment.

Clicking any of those buttons _will_ replace the current draft. Without making that clear to the user I think there will be many confusing side-effects.

An intermediate step might be to show a single button that just says 'replace current draft'. 

The scenario I am most worried about:
* user clicks to see all revisions
* they see an older revision and are curious as to what that looks like 
* they click 'review' 
* while there, they click preview or share draft, thinking that will let them see what that revsion looked like on the site
* that actually also saves the OLD revision and now makes it the LATEST revision, muddying up the history in some potentially confusing ways. 

Hope that makes sense!

P.S. Another thing I noticed is that the 'preview' button on the revisions page seems to have archived versions of each of those revisions that would be able to be viewed without replacing anything. It might be a long shot, but perhaps we can adjust the revision template to use that existing preview link instead of making a new one/replacing the current one.

**Comment by toribr** [comment]
Great points. I think maybe the whole flow needs to be reviewed with content. It's pretty confusing, as wagtail allows a lot of room for errors. I think maybe restricting revisions to "compare" only might be worth discussing. In this case, there would be no preview or review from the revisions page. Users would compare, and either restore or go back to all revisions.

Or we could allow compare and review. Review would only allow "replace current draft" as you suggested above. (Question: the mobile preview updates to whatever revision, doesn't it, essentially showing a preview?)

Additionally, revisions stores updates even when there are no changes. It's possible to get "there is no difference between these two revisions" messages. In my book, that's not a revision.

**Comment by toribr** [comment]
@easherma FYI, we're going to discuss this issue on Monday but also how wagtail manages states and creates duplicates, because related. :)
