### ISSUE TITLE
General: Increase spacing between footer and page body content

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2009]
## Visual design change
Increase spacing between the page body content and the footer to `80px`. 

### USWDS 2.0 resource
- [Spacing units](https://v2.designsystem.digital.gov/design-tokens/spacing-units/)
- For the `80px` specified here the correlating token is `'10'`

### Current
![Screen Shot 2019-05-20 at 11 30 55 AM](https://user-images.githubusercontent.com/7027270/58037314-c3f81300-7af2-11e9-8a2d-a5289318b0e1.png)

### With 80px spacing added 
![Screen Shot 2019-05-20 at 11 32 52 AM](https://user-images.githubusercontent.com/7027270/58037634-7039f980-7af3-11e9-8950-13f5264df2ec.png)

**Comment by sergiogcx** [comment]
This gets resolved in PR:

https://github.com/cityofaustin/janis/pull/422

https://janis-pr.austintexas.io/422/



Issues fixed by this branch:

https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2097
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2088
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2011
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2084
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2009

**Comment by sergiogcx** [comment]
Tested in IE11:

![Screen Shot 2019-05-24 at 5.48.39 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/db308d07-ea9c-4a2b-8373-771ca391fcd9)
