### ISSUE TITLE
Navigation: change "AIRPORT" to title case in all languages

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2011]
## Visual design change 
Change text styling of "AIRPORT" to title case "Airport" in all languages.

### Current
Airport is in all caps in the global nav

![Screen Shot 2019-05-20 at 11 40 47 AM](https://user-images.githubusercontent.com/7027270/58038017-74b2e200-7af4-11e9-8796-40c4a772df9a.png)

### With change
The styling here should be
- text-color: #FFFFFF
- Default opacity: 75%
- Mouse-in opacity: 100%
- Remove underline style
- Material Icon that should trail the link is named "open_in_new" in the Material icon font

![Screen Shot 2019-05-20 at 11 52 51 AM](https://user-images.githubusercontent.com/7027270/58038542-cf990900-7af5-11e9-838d-aae5bc901d9e.png)

**Comment by sergiogcx** [comment]
This gets resolved in PR:

https://github.com/cityofaustin/janis/pull/422

https://janis-pr.austintexas.io/422/



Issues fixed by this branch:

https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2097
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2088
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2011
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2084
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2009
