### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2077]
### As a resident, I want to learn about events the City offers that are relevant to me, so that I can find one to attend.

MVP will include:
- An aggregate/list/calendar view 
  - Basic filters (we'll want to scope this—date range, time, department?) 
  - How residents get to aggregate view
- A single event page
  - Connects to locations

Post-MVP
- Let's develop a resident-friendly taxonomy to filter events. (Maybe persona-based)
- Adding events to related content pages (such as departments, services, information, location pages)

Where to start?
- Research needs across departments (pull in SDL for this one)
- Develop requirements
- Explore integrations/plugins that might do this well

------------

**Some old notes from the original issue, before it was rewritten** 
Community garden scope deliverable but epic will serve Austin Public Health projects, too. 

https://docs.google.com/document/d/1NVNrS0FIfef1G5dxM8-u7Bvs7F_j3S5gQJjkcavpmWI/edit#

**Comment by toribr** [comment]
From slack: 
Where’s the boundary between a time-boxed service and an event? Currently I’m thinking that anything that requires registering for might qualify as an event, but a walk-in service would not. But it might be more than that.
Currently all sorts of things are being used as events, like this: https://dev.austintx.gov/event/neighborhood-services-north-austin-ymca-1  I’m not sure that something that happens everyday ought to be an event; it’ll clutter up the events listings, even if sorting were available. It seems like it may be being used as a way to get more visibility on the home page and elsewhere, but it doesn’t really provide much information on the surface of things, so it’s unlikely that anyone will actually click on it. What does “neighborhood services” mean? In fact, it almost implies that these services are only available on that day, rather than every day.
