### ISSUE TITLE
Redundant info about alpha project on home page

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2084]
There are links to alpha projects and austintexas.gov at the bottom of the home page as well as the footer. Since the footer is on every page, why do we need it on the home page too?

**URL tested:** https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fprojects.austintexas.io%2Fprojects%2Faustin-digital-services-discovery%2Fabout%2Fwhat-we-are-doing%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1440x788 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5311f8883449f9825cc9ac02508e25af46ff513e/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/5311f8883449f9825cc9ac02508e25af46ff513e/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fprojects.austintexas.io%2Fprojects%2Faustin-digital-services-discovery%2Fabout%2Fwhat-we-are-doing%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://projects.austintexas.io/projects/austin-digital-services-discovery/about/what-we-are-doing/) to reproduce the issue on Browserstack**

**Comment by briaguya** [comment]
I know the actual plan is to have it match this: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9489fed6-9eac-42a2-8516-af855c6e9042/Homepage-MVP-Desktop/

In order to implement that, @pibemillo is building the Navigation Footer (https://github.com/cityofaustin/techstack/issues/1903)

@chasechenevert @toribr Is there anything you'd like in the interim?

**Comment by desigonz** [comment]
Relatedly, see @chasechenevert's brilliant "Messaging about Alpha on Alpha" doc

**Comment by briaguya** [comment]
@desigonz link?

**Comment by oliver2g** [comment]
Link to @chasechenevert 's "Messaging about Alpha on Alpha" doc
https://docs.google.com/document/d/166m6BCBPKa6Uyms1wArxAaFO4n-ubhgJtxTy9EHfcXc/edit?usp=sharing

**Comment by chasechenevert** [comment]
I'm going to send over a modification for this as an interim solution to a bigger reconsideration of the home page.

**Comment by chasechenevert** [comment]
So we still aren't ready for a full redesign of the homepage just yet (with static content, or any other site content). As with the change to the way service tiles are displayed on the Department page, this change will move us closer to a design refactor of service/guide tiles that will be coming soon, so the work here isn't just a one-off change.

- [ ] Remove the redundant copy circled in red in Gerald's post above
- [ ] "Check out city of Austin services" block should no longer overlay on the banner image
- [ ] Change background color to white
- [ ] Container extends to 100% screen width 

### Proposed design changes

<img width="895" alt="Screen Shot 2019-05-23 at 3 11 38 PM" src="https://user-images.githubusercontent.com/7027270/58283120-2a886580-7d6d-11e9-871f-4754769e3498.png">

**Comment by sergiogcx** [comment]
This gets resolved in PR:

https://github.com/cityofaustin/janis/pull/422

https://janis-pr.austintexas.io/422/



Issues fixed by this branch:

https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2097
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2088
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2011
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2084
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2009

**Comment by sergiogcx** [comment]
Tested on IE11:

![Screen_Shot_2019-05-24_at_5_53_34_AM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/17e4601a-ade5-4108-a692-6b786843dadc)
