### ISSUE TITLE
Department page: Banner and Top Services tweak

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2097]
We're having some issues with the way IE is displaying the top services, so I'm proposing two tweaks to try and avoid this issue in general. These changes will move us closer to a refactor of the service/guide tile design that will be coming down the road.

### Design changes
- [x] Reduce banner height to 300px
- [x] Top services container extends 100% width, and no longer overlays banner image

**Reference spec:** https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9055635c-de21-497d-b8fb-631c3e39c802/Department-MVP-Desktop/

### Current design
<img width="1439" alt="Screen Shot 2019-05-23 at 12 27 49 PM" src="https://user-images.githubusercontent.com/7027270/58274790-39651d00-7d59-11e9-874b-fea7bf923f47.png">

### Proposed changes
<img width="1119" alt="Screen Shot 2019-05-23 at 12 51 23 PM" src="https://user-images.githubusercontent.com/7027270/58274937-8cd76b00-7d59-11e9-86b1-61fcbe9fe9a7.png">

**Comment by sergiogcx** [comment]
This gets resolved in PR:

https://github.com/cityofaustin/janis/pull/422

https://janis-pr.austintexas.io/422/



Issues fixed by this branch:

https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2097
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2088
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2011
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2084
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2009

**Comment by sergiogcx** [comment]
Fixed mobile issues, this is what it looks like now:

![Screen Shot 2019-05-25 at 2.07.02 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ab56be86-4c2a-4cee-a050-fc1a675f4c3d)
