### ISSUE TITLE
Fact check: Battery Drop-Off locations

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2107]
http://austintexas.gov/page/battery-drop-locations

Then draft information page?

**Comment by desigonz** [comment]
@LauraTrujillo @annieszot should this be part of the ARR info page content release?

**Comment by annieszot** [comment]
@lauratrujillo @desigonz Also see #2121

**Comment by annieszot** [comment]
@desigonz @LauraTrujillo Proposing to just include library locations on the info page. 
Per APL "All Austin Public Library Branches, including the Austin History Center and Recycled Reads, have buckets for used household battery collection."
Let's ask APL to remove "Dozens of other drop-off sites are also listed on this page" instead of directing residents to call the sites. 
https://library.austintexas.libguides.com/recycling
I speculate the public libraries will indefinitely have battery collection buckets versus the businesses 
Here's the draft: https://docs.google.com/document/d/1jGglqH2Kyd6LSZjYOAb8PczO8ImZ_flQy9LKsZpHdts/edit#

**Comment by desigonz** [comment]
+1 on ditching links to businesses instead of directing residents to call the sites.

Instead of linking to each individual branch, I think it would be cleaner to have a link that says "You can drop off your batteries at [any Austin Public Library branch](https://library.austintexas.gov/locations), including the Austin History Center and Recycled Reads."

Also...thoughts on this being a service page? If the library participates, it's kind of a City service, no?

**Comment by desigonz** [comment]
Also also: this would be a SUPER interesting one to content test somehow, especially if we get pushback from ARR from taking out locations. Could do a bit of comparative testing. Might want to get people from geographically dispersed parts of Austin and get them to locate a place to drop off batteries.

**Comment by LauraTrujillo** [comment]
@annieszot @desigonz I agree with y'all! Desi, I really like that suggested language.

**Comment by annieszot** [comment]
Great! Unassigning @LauraTrujillo and will turn page into a service page with steps once I talk with APL. Then will brainstorm testing/strategize possible pushback. Thanks!

**Comment by desigonz** [comment]
Sounds good! I think testing can wait until later down the line (like, we could even wait until after we get pushback), but would be good to put it @kriskristin's radar.

**Comment by annieszot** [comment]
Draft updated. Closing
