### ISSUE TITLE
Compare alpha.austin.gov content to our drafts and make sure everything is there

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#213]
Be sure to check all links. 

Laura
- [x] Drop off hazardous waste

Courtney
- [ ] Get ready for curbside pickup
- [ ] Look up trash, etc. pickup days

Ashlee
- [x] Pickup free paint
- [x] Get ready for curbside compost pickup (specifically look at the steps)

**Comment by ashleecoa** [comment]
Get ready for curbside compost pickup http://alpha.austin.gov/services/compost-pickup

- missing the What do I do with tool
- contact has "default" in it which looks strange
- country looks strange UNITED_STATES
-should 311 have dashes? 

Pickup free paint

- at the bottom of the page "Need to drop off items to be recycled? See how to drop off at the Recycle and ReUse Center." the link is broken. And this is new and needs to be translated.

**Comment by cthibaultatx** [comment]
@ashleecoa @courtneyjacinic @LauraTrujillo I imagine you'll include translated content review in this issue the next go around?

I have already pointed out some of the above ^ in issue #211. Just want to make sure there's no doublework since I started the documentation this round.

@ashleecoa in slack..somewhere, we landed on 311 not having dashes, the same way 911 does not have dashes

**Comment by LauraTrujillo** [comment]
Closing- see #211
