### ISSUE TITLE
Department page: issues on display if no service/info page block at top

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/techstack#2214]
Problem:
Right now when I visit the ARR department page, the image overlaps with text making it difficult to read. I assume this is because of the addition on the OPO page for the block we added for the service and information pages.
Seen in chrome on a MAC OSX

Steps to recreate:
1. go to https://alpha.austin.gov/en/learn-more-about-austin-resource-recovery

Expected results:
What we do section is easily read.

Actual results:
ARR image overlaps with What we do section and is difficult to read.

![Screen Shot 2019-05-29 at 6.09.06 PM.png](https://images.zenhubusercontent.com/5a971d9c4b5806bc2bc8db22/117d0f3a-adf6-4fe7-b936-7c0ae0010b33)

**Comment by desigonz** [comment]
@easherma I think this happened because we published out the ARR department page now that we got the translations back, and at some point a long time ago someone had added an image in Joplin...but we haven't really dealt with images on Janis yet. Maybe the easiest thing for now is to remove the image from this page, and later design/dev can work out how images should work. cc @LauraTrujillo

**Comment by briaguya** [comment]
Noticed a few other things:
* It looks like we're missing the related information in our preview at the moment (probably because of weird logic around relations within previews, should be able to come up with a quick dummy data fix for now and then figure out all the preview relation oddities in the future)
* It looks like without related information we're not setting the right classes on the top services part (with related information we're getting `coa-TopServicesRelatedContent` and within that div we're getting `coa-TopServices coa-TopServicesDepartment`. Without it we're just getting `coa-TopServices__container`.

**Comment by LauraTrujillo** [comment]
@desigonz @easherma I agree- let's remove the image and give design/dev time to work on this. Thanks!

**Comment by LauraTrujillo** [comment]
@briaguya Good point. I'll defer to you.

**Comment by desigonz** [comment]
Okay I tested removing the image and publishing the page to funny results, documented in #2237. I've unpublished the ARR page for today's demo.

**Comment by easherma** [comment]
@desigonz is this page actually unpublished? It looks like its still in alpha.gov:
https://alpha.austin.gov/en/learn-more-about-austin-resource-recovery/

But it isn't live in staging:
https://janis.austintexas.io/en/learn-more-about-austin-resource-recovery/

Tagging @sergiogcx and @briaguya for debug/sanity check

**Comment by desigonz** [comment]
@easherma !! Says it's in draft on Joplin
![image](https://user-images.githubusercontent.com/5839508/58670622-596e8080-8305-11e9-939d-c84016b2eadb.png)

**Comment by desigonz** [comment]
Also it's not appearing on the "departments" page, even though the page is still live https://alpha.austin.gov/en/departments/

**Comment by briaguya** [comment]
@easherma @desigonz Re: inconsistent page deletion on unpublish. I think that has something to do with our aws configuration, it's got to be falling back to an old version. This is definitely not an ideal way for this to work. That's definitely a different issue.
