### ISSUE TITLE
Previews don't work in PR builds

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2296]
Only the loading screen shows up, but not an actual page build

![Screen Shot 2019-06-04 at 4.47.00 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/beebc31f-7c56-4324-a242-f616f1a8006a)

**Comment by desigonz** [comment]
Probably related to #2311

**Comment by briaguya** [comment]
We've got a lot of messy stuff to dive into around how we're dealing with deployments (especially PRs).

Another complication here involves having a janis deployment pointing to the PR app for Joplin. Trying to get that hooked up nicely could add another layer of complication to the deployment.

Diving down the rabbit hole of trying to fix all of this could be quite intense, and there may be a better way (https://github.com/cityofaustin/techstack/issues/2415)

**Comment by briaguya** [comment]
If we do #2415 this should be fixed

**Comment by briaguya** [comment]
Even if we don't do https://github.com/cityofaustin/techstack/issues/2415, there are ways we could improve this.

One option would be to update our CMSPreview component in Janis to support rendering from different endpoints, possibly by passing something in a querystring.

ex.
Instead of https://alpha.austin.gov/en/preview/services/revisionID
we could have https://alpha.austin.gov/en/preview/services/revisionID?prURL

**Comment by easherma** [comment]
Also, pivoting to using: https://github.com/torchbox/wagtail-headless-preview
to manage headless previews can probably simply this and reduce our code maintenance burden, using this library it looks like it would be pretty easy to set HEADLESS_PREVIEW_CLIENT_URLS dynamically
