### ISSUE TITLE
Contact information on service and info pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2316]
Contact info on service (and info?) pages in desktop view currently appears below all of the rest of the content. It should appear on the right side, as in on department pages.

Acceptance criteria
- [x] Service pages: In desktop, contact information appears on the right side 
- [x] Information pages: In desktop, contact information appears on the right side 

service page
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/4da5a481-7a3d-414e-b1f3-dd34e1d8b45c)
dept page
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/164bfd4d-78a1-4786-8642-a556818b4c90)

**Comment by briaguya** [comment]
@desigonz re: info pages
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/6cb0a2ed-679d-489c-b6c1-bf8b2022d3bb/Information-MVP-web/ (no contact info)
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/56e816e8-c8da-4ad1-affd-aa864bf6b457/Information-MVP-mobile/ (no contact info)

I'm cool with making sure info pages behave just like service pages when it comes to contact info, just want to confirm that the fix for info pages should be that instead of updating the data model so info pages don't have contact info

**Comment by briaguya** [comment]
looks like we don't have a design for contact info on the side in service pages either: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ce9e7492-b75b-472c-9dab-98d7bd1843ba/Service-MVP-Web/

I'm going to move this issue back to on deck until we have updated designs that include contact info if that's cool.

**Comment by chasechenevert** [comment]
I've updated the mocks and pushed the update to include contact info on info pages; they behave and appear just as they do on department pages. 

<img width="1153" alt="Screen Shot 2019-06-28 at 10 32 02 AM" src="https://user-images.githubusercontent.com/7027270/60353653-1b11c300-9990-11e9-85cd-793d8d6bc6ae.png">

**Comment by desigonz** [comment]
Thanks @chasechenevert! @briaguya, these are good to go to you. Let us know if you have more questions.

**Comment by briaguya** [comment]
https://deploy-preview-453--janis.netlify.com/

**Comment by desigonz** [comment]
@briaguya looks great!
