### ISSUE TITLE
Incorporate guide testing insights into design

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2318]
This list covers the improvements to be made to the guide document type as a result of user testing:
- [x] Add search to the document
- [x] Add friendly intro (images?) to the beginning
- [x] Remove stars
- [x] Keep checkboxes but only as static bullets
- [x] Re-assess how documents are structured in that tab. Don't use same structure as guide.
- [x] Make access to contacts global and more visible
- [x] Remove contacts & documents link from each page
- [x] Download guide link (downloads entire thing)

**Comment by chasechenevert** [comment]
# Notes from Sprint 33 pin up 2
- [XD prototype with notes](https://xd.adobe.com/view/dad1e5da-e1c6-4ae9-546d-42034ac63459-ace0/screen/5190703d-1a61-4b46-80ee-8f30288132fc/Guide-round-2-intro-2)

### Page heading
- Based on group discussion we don't need these buttons anymore
- Replace "Download guide" and "Print guide" buttons with "Download checklist" and "Print application" buttons

### Photo selection guidance
- Wondering if we should be sensitive to featuring a branded food trucks as it might be perceived as promoting a business / advertising. I realize the context is different, but i'm not sure how politically challenging choices like this can be

### Introduction section
- Feature related guides here(as buttons? links?). The current thinking is to divorce these guides based on the primary 2 user goals (new permit, vs renew)

**Table of contents** 
- Users might be confused about the order of information when trying to scan, let's try a more reliable pattern 

### Left-hand page navigation
- Search likely won't be part of MVP, but we should still consider the interaction and ensure the messaging is clear so that a user understands what this search does as opposed to the global search that will appear in the primary site nav
- What is the user searching? Text, docs, "find in page"?

### Mobile navigation
- How might we reconcile global vs page-level navigation on mobile where these elements may appear close to each other, and/or use similar iconography (hamburger menu)
- What about floating action buttons (FABs)? Will users understand this functionality?

**Checklist**
- Let's try a link to the checklist here as user testing revealed that users find the checklist valuable

### Section headings
- Consider the size of the background layer compared to the global nav size
- Let's make the vertical height shorter so that it's within proportion to the global/primary nav

### Contacts
- How might we surface contacts so that they're more visible to the user?
- Let's make it easier for users to find and get help. One option is to include the contact info as a link within the lefthand page level nav

### Documents
- Include checklist in download section

**Comment by chasechenevert** [comment]
### Guide UI next steps
Not sure if we push this out to a separate issue for sprint 34, but I wanted to pull out the action items for clarity

- [ ] Page heading: replace "Download guide" and "Print guide" buttons with "Download checklist" and "Print application" buttons
- [ ] Intro: feature related guides (as buttons? links?) between "new permit" and "renew"
- [ ] Intro, table of contents: try a different scanning pattern, or potentially 1 column
- [ ] Left-hand page nav: include checklist
- [ ] Mobile: start mocking up mobile, paying attention to mobile global nav vs. page-level nav
- [ ] Section headings: shorten height to make it proportional to global site nav
- [ ] Contacts: make contacts easier to find

**Comment by toribr** [comment]
Perhaps "Print application documents" rather than "Print application"

**Comment by chasechenevert** [comment]
Feedback: Guide UI sprint 34 pin-up 1 
- [ ] Heading: add document size and type to the "Print application" button 
- [ ] Dev question: how might we include page detection (in left hand menu) with sticky navigation?
- [ ] Body: remove introduction block and TOC
- [ ] Contact: try FAB, 
- [ ] Left-hand Navigation: move documents back to the bottom
- [ ] Contact (page body): remove contact info drop down for now, but keep idea around
- [ ] "Documents" -> "Application Documents

**Comment by chasechenevert** [comment]
# Feedback: sprint 34 pin-up 2
- [ ] Illustrate page scroll styling to address this user story: "I know where I am within the guide".
- [ ] Nav (left-hand): drop icon from download since the action is different than the "download" button
- [ ] Body: drop icon from download
- [ ] Contact: remove `hours`, `address`, and `map image`
- [ ] Nav (left-hand): Check spacing for list items

**Comment by chasechenevert** [comment]
- MVP mocks from the presentation today which includes some extra boards to show the fixed left nav, and the mobile menu: https://xd.adobe.com/spec/3cd2740c-6a05-45fc-6e6e-e1cf885acaca-4ae3/
- MVP of desktop in the master design spec: https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/
