### ISSUE TITLE
Visual design for Joplin login page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2334]
Let's make the login page friendly for our first round of ARR, APH, and OPO users.

**Comment by chasechenevert** [comment]
# Joplin login visual design pin-up
Here's what was shared at pin-up. I've got more ideas about this since presenting, so I'm going to iterate in sprint 34.

## Notes
- Got a little more clarity on whether or not we'd want to include information like feature updates here. The consensus is that most employees who will be using this don't necessarily interact with Joplin as a regular part of their job--they'll just want to get in, author content, and be done.
- Need to illustrate error states for fields with validation

![Joplin login – 1@2x](https://user-images.githubusercontent.com/7027270/60358028-cfb0e200-999a-11e9-82b8-74b2f1f5b576.png)
![Joplin login@2x](https://user-images.githubusercontent.com/7027270/60358030-d0497880-999a-11e9-9296-08da96e10379.png)
![unnamed](https://user-images.githubusercontent.com/7027270/60358032-d0497880-999a-11e9-9d9b-d74ba56d4e69.png)
