### ISSUE TITLE
Surface map snippets page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2367]
### As a content editor, I want to be able to create a map on Joplin so that I can add it to a page I'm editing.

**Acceptance criteria**
- [ ] Link to [map snippets](https://joplin.herokuapp.com/admin/snippets/base/map/) page from Joplin left nav

**Describe the bug**
Can't access map snippets (https://joplin.herokuapp.com/admin/snippets/base/map/) from Joplin nav, and the map snippet page is the only place you can add a new map.

**URL**
https://joplin.herokuapp.com/admin/

**Related**
#2510

**Comment by easherma** [comment]
https://github.com/cityofaustin/joplin/pull/297

**Comment by easherma** [comment]
https://joplin-pr-add-maps-snippet.herokuapp.com

**Comment by easherma** [comment]
Like I mentioned in the PR:
the whole way we make the menu is pretty borked and flies in the face of the recommended way in the wagtail docs.

Also the way we are slowly adding back in elements from the default menu is not great. I recommend us reconsidering using the default menu, especially since it is mobile friendly and doesn't require a dev to make a change every time we want to add something. It is also set up to easily nest objects in the admin menu, which I think we're seeing we're going to want to do.

**Comment by desigonz** [comment]
@easherma Thoughts on swapping to the "site" world icon instead ([from this list](https://s3.amazonaws.com/kave-dump/StreamField+Icons.png)]. I think it would be more readable as "maps" for content editors if it takes us a bit of time to get to #2510. 

![image](https://user-images.githubusercontent.com/5839508/61131509-08fb4e80-a47f-11e9-8d23-eca906998e08.png)

**Comment by easherma** [comment]
I'm thinking lets this is superceded by https://github.com/cityofaustin/joplin/pull/298

**Comment by briaguya** [comment]
Just merged to prod, this is working there now.
