### ISSUE TITLE
Research hosting other content types on department pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2403]

**Comment by chasechenevert** [comment]
# How are other governments utilizing department pages for various content types
Examples:
>Mass.gov Public Health: https://www.mass.gov/orgs/department-of-public-health
>GOV.UK Department of Health and Social Care: https://www.gov.uk/government/organisations/department-of-health-and-social-care

Both sites are somewhat similar in that they all share a few basic content types:
> - Contact
> - Mission
> - Services
> - Featured content (news, topics, services)

<img width="1648" alt="Screen Shot 2019-06-20 at 12 20 36 PM" src="https://user-images.githubusercontent.com/7027270/60357618-c115fb00-9999-11e9-8583-efb03b86ea7f.png">

GOV.UK has a standardized format (*all* department pages contain the same content structure, order, and components), whereas Mass.gov seems to leave things optional but the result is that you don’t always know what to expect on other department pages. I wonder if something like what GOV.UK has for this block would take care of a wider variety of department needs; it’s basically just a short list of curated links with a “see all” link that takes the user to a pre-populated filtered search.

Curious about GOV.UK’s metadata tagging is because nearly everything is labeled
