### ISSUE TITLE
Implement OPO anonymous complaint fix

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2411]
### As an OPO complaint form user, I want to know what information OPO will need from me to be able to give me details about my case when I call to follow-up in the future, so that I am able to weigh whether I submit my complaint anonymously or not.

**Acceptance criteria**
- [x] Demographic information on its own page (see mock below)
- [x] New "follow up" page (see mock below)
  - [x] User can select between two radio button options: "Follow up with me" or "Remain anonymous"
  - [x] If a user selects "Follow up with me," contact preferences questions appear and the following fields:
    - [x] "Your name" is required
    - [x] "Your phone number" is required
    - [x] "Email address" remains optional, but field name and helper text is updated to match new mocks
    - [x] Required fields under "follow up" don't impede a user from submitting anonymously
    - [ ] ~~Interpreter question remains optional, but helper text is updated to match new mocks~~
  - [x] If a user select "Remain anonymous," text in the mock below appears.
- [x] Review page reflects the new split up "demographic information" and "follow up" pages as two separate sections
- [x] On the confirmation page, no confirmation number shows up for ANY user (whether anonymous or identified)
- [x] On confirmation page, remove the option to add an email if you hadn't previously entered it 
- [x] On confirmation page, we have some copy changes; ~~should match mocks~~
- [ ] Confirmation emails
  - [ ] remove confirmation number
  - [ ] otherwise, email copy remains the same
  

**Is your feature request related to a problem? Please describe.**
See #2409 for context.

**Describe the solution you'd like**
TBD—we'll be updating copy on the [Tell us about you](https://forms.austintexas.io/police-complain/about-you) and [confirmation](https://forms.austintexas.io/police-complain/confirmation) pages, and possibly adding conditional logic that makes the confirmation number appear for users who have submitted the needed information and those who have not.

Might also add new copy to the email.

**Describe alternatives you've considered**

**Additional context**

**Comment by desigonz** [comment]
Mocks: 
![6 1](https://user-images.githubusercontent.com/3790067/60993926-0bda3000-a315-11e9-8083-2b2f7c3e4460.png)
![6 2 Follow UP](https://user-images.githubusercontent.com/3790067/60993927-0bda3000-a315-11e9-9964-e31549cef748.png)
![6 2 1 Follow UP](https://user-images.githubusercontent.com/3790067/60993928-0bda3000-a315-11e9-8ab4-62e9027f7571.png)
![6 3 Review](https://user-images.githubusercontent.com/3790067/60993929-0c72c680-a315-11e9-977f-ed64c5ed65da.png)
![6 4 Universal Confirmation](https://user-images.githubusercontent.com/3790067/60993930-0c72c680-a315-11e9-8b94-511d2f2421f2.png)

**Comment by desigonz** [comment]
@easherma there are updated mocks above with the correct language.
@srigdon, Tori removed mentions of confirmation number above. It's looking good right now, so I don't think you need to review at the moment. I'll have you QA Eric has a staging branch and make sure copy is 100%, among other things.

**Comment by desigonz** [comment]
Per slack conversation: Keep interpreter checkbox as is.

**Comment by desigonz** [comment]
@easherma updated mock above

**Comment by easherma** [comment]
Got it in https://github.com/cityofaustin/coa-forms/pull/44
QA at https://opo.austintexas.io/police-complain/2411-OPO-anon/introduction

**Comment by desigonz** [comment]
@srigdon Thanks for QAing this, and please check against the acceptance criteria above! I'd also like @toribr to take a look at the design implementation, especially on the review page. 

Copy edit question: in the parenthetical "(optional)" we're lowercasing the "o", but we capitalize "(Required)." Let's make a style decision on that.

**Comment by desigonz** [comment]
@easherma Moved back to "in progress" and added acceptance criteria "Required fields under "follow up" don't impede a user from submitting anonymously."

**Comment by desigonz** [comment]
assigning @srigdon to QA

**Comment by srigdon** [comment]
I checked off all the things that look good in the acceptance criteria above. 

Edits to make: 

- On the Share media page, make the hyperlink say "data" not "information", because that's what its URL and page title says. "Information" is more approachable, though! That's another issue for later. 
- On the Demographic info page, make all instances of "(optional)" uppercase [so, "(Optional)"]. 
- On the Follow up page, when you select "Follow up with me", make the "Your email address" copy conform to the mock above (https://user-images.githubusercontent.com/3790067/61145626-8c2b9d00-a49d-11e9-8138-d999afef9676.png). So, 
-- Change the "Your email address" field to: "Your email address (Optional)". 
-- And add the helper text: "We need your email address to send you a copy of the complaint, but this is optional."
- On the Follow up page, when you select "Remain anonymous", make the helper text left aligned. 
- On the confirmation page, input the following text:
[title] We have received your complaint. 
[body] 
Our job is to make sure all complaints are thoroughly reviewed. Thank you for sharing your experience with us. This helps us better serve you and your community. 

If you provided your contact information, a staff person from the Office of Police Oversight will contact you within 2 to 4 business days. If you provided your email, you will receive a copy of your complaint. You can email us at policeoversight@austintexas.gov or call us at (512) 972-2676 to check on the status of your complaint. 

If you submitted your complaint anonymously, we will not be able to contact you with any potential follow-up questions or give you any information about the case.

What happens next [this entire line is a link to https://alpha.austin.gov/police-oversight/complaint-investigation-process/]

(Note: the mock (https://user-images.githubusercontent.com/3790067/61140309-db1f0580-a490-11e9-8325-e20b2e6494ab.png) doesn't contain this text, which is in the copy doc.) 

- Update the copy in the confirmation email to what's in this copy doc: https://docs.google.com/document/d/1DdsA5TJhEQMGTufpE1x3vABgxHtfUbRerxbQAqisnw4/edit#heading=h.bqosmaakkkuj 

Style notes: 

We want title case for form fields of all kinds (imperative sentence, question, or phrase), except in the case of parenthetical text indicating whether that field is required or optional. Examples: 
- Describe your experience with the Austin Police Department. (*Required)
- Your name (*Required) 
- Your email address (Optional) 

Rationale: We want to make required fields as clear as possible. Hence the asterisk, capitalization, and red color. "(Optional)" may look worse than "(optional)" in context, but inconsistency bewteen required and optional indicators looks even less good. 
 
Acceptance criteria: 

1. When we use "(*Required)" next to a field, check the following: 
- Make the text red, including the parentheses. Hex code: 
- Capitalize "required." 
- Put an asterisk between the first parenthesis and the word "required," no spaces. 

2. When we use "(Optional)" next to a field, check the following: 
- Capitalize "optional." 
- Keep text the same color as the rest of that field text. 

Options to consider as we try to make required and optional fields in forms even clearer include: 

- Anu's idea: put a button that says "Skip" instead of "Continue", or perhaps in addition to "Continue." We haven't tested this out, but a good idea for the next form. 
- We could also put parenthetical text indicating whether that page is required or optional after the page title, as we've done before, but that makes the page titles on the review page look inconsistent. 

Any other options we haven't considered?

**Comment by easherma** [comment]
@srigdon all those changes should be incorporated
I haven't updated email confirmation content since that is in a different repo

**Comment by desigonz** [comment]
Thanks team! Just reviewed the branch and it's looking good, but found a number of outstanding things. @srigdon, please jump in if you disagree with any of these or see anything else that's missing.

- [ ] On confirmation page: Add a period after "You will receive an email with a copy of your complaint at <email address>" (see screenshot below)
- [ ] On confirmation page: policeoversight@austintexas.gov should be a `mailto:` hyperlink ([as it currently is](https://forms.austintexas.io/police-complain/confirmation))
- [ ] Confirmation email needs to reflect Sarah's edits in [this doc](https://docs.google.com/document/d/1DdsA5TJhEQMGTufpE1x3vABgxHtfUbRerxbQAqisnw4/edit?usp=sharing)
  - [ ] remove confirmation number 
  - [ ] change "You can email us or call us at (512) 972-2676 any time with your confirmation number to check the status of your complaint." to "You can email us at policeoversight@austintexas.gov or call us at (512) 972-2676 to check the status of your complaint." (and hyperlink the email address) (@srigdon, can you confirm this?)

![image](https://user-images.githubusercontent.com/5839508/61721322-e8a87b00-ad2d-11e9-935f-9b1ceb80b8fd.png)

Also @srigdon let's touch base today re: translations.

**Comment by srigdon** [comment]
@desigonz Agree with all of those points. 
@easherma Which repo is the email content in?

**Comment by desigonz** [comment]
Email content lives in this repo: https://github.com/cityofaustin/form-service-api/pull/31
Per @easherma, we might not be able to QA the email confirmation til everything is merged.

**Comment by desigonz** [comment]
Assigning to myself to input translations and make copy edits

**Comment by desigonz** [comment]
This should be "How we store and use your information." Once we have that copy fixed, the translation should work.

![image](https://user-images.githubusercontent.com/5839508/61749995-c3396280-ad69-11e9-8e61-d06f15f91f29.png)
![image](https://user-images.githubusercontent.com/5839508/61750027-dfd59a80-ad69-11e9-8b51-4dc173f91227.png)

**Comment by desigonz** [comment]
- [ ] @Niicck is looking into confirmation email not sending when submitting the form on the PR branch app
- [ ] @desigonz to review confirmation email—do the fields match the form as expected?
- [ ] Once that's done, @Niicck will merge to master
- [ ] and then we will do the following QA on master:
  - [ ] Complaint form English
  - [ ] Complaint form Spanish
  - [ ] Thanks form English
  - [ ] Thanks form Spanish

**Comment by desigonz** [comment]
Hi @Niicck—I QA'd the confirmation email. Here's what needs to be changed; also see screenshot below.
@srigdon, I believe this is all but let me know if you see anything missing. The goal is to make sure the confirmation email fields for the last two pages match new form layout. 

- [ ] Demographic information section: only keep the following responses:
  - [ ] Gender
  - [ ] Race
  - [ ] Zip code
- [ ] New section titled "Follow up." Should include the following responses:
  - [ ] Name
  - [ ] Phone
  - [ ] Email
  - [ ] Needs interpreter


![image](https://user-images.githubusercontent.com/5839508/61964263-10e4e380-af93-11e9-8f6d-c53919592682.png)

**Comment by easherma** [comment]
- [ ] remove unwanted fields: Referrer, Has officer details, Has Witness information
- [ ] move gender, race, zip code to be right under demographic information but with no other bold title
- [ ] add Follow up title with contact information below that

**Comment by desigonz** [comment]
Moving this back to QA because @srigdon is going to QA the form on master. Sarah, let me know if you need help with QA—I can take on some of it today!

**Comment by srigdon** [comment]
✅ English complaint form looks good.  

🚫 English complaint confirmation email needs these edits: 

- [ ] Remove the confirmation number and conform to the copy in [this doc](https://docs.google.com/document/d/1DdsA5TJhEQMGTufpE1x3vABgxHtfUbRerxbQAqisnw4/edit#). 
![OPO-eng-complaint-email_7-31](https://user-images.githubusercontent.com/5445796/62240956-c520a880-b39d-11e9-898a-9d6370c8baa4.png)

- [ ] Make the "Follow up" section title match the rest. 
![OPO-eng-complaint-email-2_7-31](https://user-images.githubusercontent.com/5445796/62240973-cce04d00-b39d-11e9-8eaa-47e0fa5aa4cc.png)

🚫 Spanish complaint form needs these edits: 

- [ ] https://forms.austintexas.io/policia-queja/compartir-archivos - On this page the link to "Cómo guardamos y usamos su información" sends you to the [English URL](https://alpha.austin.gov/es/police-oversight/how-we-store-and-use-your-data/) but the page is in Spanish. Also the title on that page ("Cómo almacenamos y usamos su información") doesn't match the hyperlink text on the form page. 

- [ ] Also on that page, the slug (/compartir-archivos) and the page title (Comparta sus archivos) don't quite match, but I'm not sure how big of a deal that is. 

- [ ] This page URL still has the English slug: https://forms.austintexas.io/policia-queja/demographic-information 

- [ ] Same here: https://forms.austintexas.io/policia-queja/follow-up 

- [ ] Confirmation page needs a Spanish slug and the text in one of the lines is English, needs Spanish. 
![OPO-span-complaint-conf_7-31](https://user-images.githubusercontent.com/5445796/62242309-7e807d80-b3a0-11e9-8e73-dba57e190e23.png)

🚫 Spanish complaint confirmation email needs these edits:

- [ ] Same issue is happening in the Spanish confirmation email as the one in English above. Take out the confirmation number, lower case the P in the "Proceso de investigación de quejas" link, and make the section titles style match. 

✅ English thanks form looks good. 

🚫 English thanks confirmation email needs these edits: 
![OPO-Eng-thanks-conf-email_7-31](https://user-images.githubusercontent.com/5445796/62243231-76c1d880-b3a2-11e9-9b20-9f32d8b86bd3.png)

🚫 Spanish thanks form needs a Spanish slug on the confirmation page. https://forms.austintexas.io/policia-agradezca/confirmation 

🚫 Spanish thanks confirmation email needs these edits: 
![OPO-Span-thanks-conf-email](https://user-images.githubusercontent.com/5445796/62243710-7d048480-b3a3-11e9-8314-e55745810cfe.png)

**Comment by desigonz** [comment]
thanks a million to @srigdon for your wonderful QA work!

@easherma, onto you to implement these changes.
