### ISSUE TITLE
Look into samsung internet language persistence bug

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#245]
Using a Samsung phone (unfortunately could not get model number) and Samsung internet, user pulled up alpha.austin.gov and switched into Spanish. She then let the phone go to sleep and when she brought the site up again- half the page was in English (tile content and service content), half in Spanish (headers).

**Comment by mateoclarke** [comment]
I tried to reproduce this in BrowserStack but its not possible to put the virtualized device into sleep and wake it back up. I'm thinking that a lot about fixing this bug might be beyond our control. Maybe Samsung Internet wipes the cookie cache (where we store language settings) when the phone falls asleep.

Samsung Internet is not a browser that gets more than 2% traffic currently so [we're not committing to support](https://github.com/cityofaustin/janis#browser-compatibility) all features on the site for this browser at this time. Our goal is that content is available on devices like this but we expect visual and UX bugs we can't fix. We'll provide progressive enhancements to supported as many browsers as we can but focus on the 98% most traffic browsers first. 

There definitely is some funky styling going on here that I think must be due to a lack of flexbox support.

![screen shot 2018-04-25 at 11 45 37 pm](https://user-images.githubusercontent.com/5697474/39286397-40da3a08-48e3-11e8-8035-bab4571ffcf6.png)
