### ISSUE TITLE
Small and minority business content audit

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#2549]
home page: https://www.austintexas.gov/department/small-and-minority-business

**Comment by anukandimalla** [comment]
@desigonz Ready to review and Link for the Audit:
https://docs.google.com/spreadsheets/d/1YGLpfLh75XDnYIzO3A1O0pTf7xiJI3S0RENPKr5_rXE/edit?usp=sharing

**Comment by desigonz** [comment]
assigned to @Jo-Dwyer for review

**Comment by Jo-Dwyer** [comment]
@desigonz I left very few notes on this document for @anukandimalla  and spoke to her before she left on Thursday. I don't have much constructive feedback yet since it's so thoroughly documented, though I do have a few questions:

-[] who is the audience for this document? Are stakeholders able to view this document?
     -[] If this is a client-facing document, where is the best place to communicate feedback on the audit?
-[] It would be helpful to link to the "How to read a content audit document" sheet won the first page of the workbook https://docs.google.com/document/d/1r6Sv3WXoPzd906S2xCVYVHhEeSHQjI_4cDYfME_-O6A/edit?usp=sharing

-[] I'd recommend that @ablangworthy27 take a look at this audit as well

**Comment by desigonz** [comment]
It's primarily a document for the ODD team, although we're always happy to share with stakeholders if they're interested. I would put primary effort in making it work for our team.

**Comment by Jo-Dwyer** [comment]
@desigonz Agreed re: usability for our team. I want to make sure that it's appropriate to leave critical feedback on the document.

**Comment by Jo-Dwyer** [comment]
Is this ready to close? @desigonz

**Comment by desigonz** [comment]
@Jo-Dwyer If there are no things that Anu needs to update, then yes!
