### ISSUE TITLE
Choosing a topic button label

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2604]
- [ ] talk to devs during dev/design sync about what generic chooser could do for situations like this
- [ ] Tori's been rethinking page pickers in general (#2746). Whatever we decide for this should be looped in what that issue.

-------

**Describe the bug**
When you're editing a service or information page, you can select a topic. Some of the buttons say "page" instead of "topic."

**Acceptance criteria**
- [ ] the first button (circled below) says "Choose another topic"
- [ ] the second button (circled below) says "Edit this topic"

**URL**
https://joplin.herokuapp.com/admin/pages/53/edit/

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/322512b5-f426-42d4-8577-a77f2ecec694)![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/730e79ef-b6ae-4845-8714-bdf37083d127)

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
This is because what you are choosing is the actual topic page that you are associating it with.

**Comment by desigonz** [comment]
@easherma But that's not a user's mental model. We're going to keep this acceptance criteria.

**Comment by briaguya** [comment]
This involves breaking default wagtail behavior http://docs.wagtail.io/en/v2.5.1/reference/pages/panels.html?highlight=pagechooser#wagtail.admin.edit_handlers.PageChooserPanel.

I think we could put something hacky together with a 3, or we could switch these to be snippets instead of pages for a more "wagtaily" solution.

Depending on how we manage https://github.com/cityofaustin/techstack/issues/2513 this could magically fix itself if we wait until after that.

**Comment by toribr** [comment]
Eventually, we should also remove the ability to edit a topic from a content page. Select a different topic, yes. Edit the actual topic name, no.

**Comment by briaguya** [comment]
@toribr even with the current implementation topics cannot be edited from the content page, the edit button is just a link to the edit page for the topic.

**Comment by toribr** [comment]
We must be having a language issue... because "edit this page" leads to a page where i can change the topic name, which is what I mean by "edit topic name." 

So not sure what you mean, but we can work it out next week.

**Comment by briaguya** [comment]
@toribr definitely a few wording issues:

On the "edit topic page", one of the things you can do is edit the topic name. If that's an issue we should change that.

If we also want to remove the link to the "edit topic page" from the other pages, we should do that too.

I was thinking you were assuming one could edit the name of a topic from the "edit service page," which I was saying was not the case

**Comment by easherma** [comment]
https://github.com/wagtail/wagtail-generic-chooser/blob/master/generic_chooser/widgets.py

Implementing this library, we could write admin choosers specifically for topics or departments and customize the template + language of the chooser modal that pops up

**Comment by briaguya** [comment]
@easherma since you've been playing with the generic chooser, any chance you could try replacing the topic chooser with a generic chooser somewhere?

@desigonz ideally by adding genericchooser we'll have an easier time customizing how we choose things (and hopefully better control over the button text too)

**Comment by easherma** [comment]
+1 to what Brian said, using the generic chooser allows for custom button copy.

**Comment by desigonz** [comment]
@desigonz to review and reprioritize

**Comment by chiaberry** [comment]
more broad version of issue in #3016
