### ISSUE TITLE
Center expanded blocks

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2607]
**Describe the bug**
When you create a new contact or edit an existing contact, you have the option to add a social media URL. The button for that is weirdly off-center.

This is also happening for options on information pages, as in #2637

**Acceptance criteria**
- [ ] For expanded blocks like social media and options, the blocks should be centered.

**URL**
https://joplin.herokuapp.com/admin/snippets/base/contact/add/
https://joplin.herokuapp.com/admin/snippets/base/contact/3/

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/35a6b3f6-85a3-4368-b7ad-9a4caec22852)

**Comment by briaguya** [comment]
This might get magically fixed by #2606

**Comment by briaguya** [comment]
This one seems like it's a little wonky.

It looks like something we're doing to force the blocks to always being expanded is getting in the way of the logic that exists within them.

When you don't auto expand, once it's loaded it automatically picks the url field

![Aug-06-2019 20-40-52](https://user-images.githubusercontent.com/6384156/62588255-bc8f0d00-b88a-11e9-9848-2107d9d8ea96.gif)

It'd be great to get it so we auto expand into the URL entry instead of the picker.

@desigonz I put a 5 on this to represent the "don't make the author click on the button" option instead of the "try to center it" option

**Comment by briaguya** [comment]
@desigonz I think it might be worth considering putting this off and working to implement a better UX for snippets in general.

**Comment by desigonz** [comment]
Let's quickly review Brian's rationale at dev/design sync. Assigning to @toribr to think up a better UX for snippets in general.

**Comment by toribr** [comment]
I'm working on a plan where map/location/contact is rolled up into a single component.

**Comment by desigonz** [comment]
This is fixed with new streamfield design
