### ISSUE TITLE
Janis nav footer improvements

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2619]
In #1903, @briaguya implemented topics and topic collections in nav footer. We need to the seal/contact/links/social part and redo the blue bottom to remove the white seal and make it skinnier.

**Acceptance criteria**
- [ ] TBD—@desigonz to develop w/ @chasechenevert

**Comment by chasechenevert** [comment]
**Links currently in dev.austintx.gov:** 
- Translate
- Get information or assistance
- Give feedback on our website
- Sitemap
- Visit Austin
- City directory
- Jobs
- Legal notices
- Privacy policy

**Social links**
- facebook
- Twitter
- Linkedin
- Instagram
- Youtube
- RSS feed

**Comment by desigonz** [comment]
@srigdon and @LauraTrujillo  see above re: social and footer links

**Comment by desigonz** [comment]
From Julia re: the page we're legally supposed to link to from the homepage.

> the Council Message Board: http://austincouncilforum.org/
>  
> Here is the Clerk’s reasoning: House Bill 2414 states that the online message board must be prominently displayed on our primary webpage and no more than only click away from the main page. You can read the section of the bill at the attached link, Section 551.006 (B)
> https://capitol.texas.gov/tlodocs/83R/billtext/html/HB02414F.htm

**Comment by desigonz** [comment]
@srigdon to review the links during sprint 37.

**Comment by srigdon** [comment]
- [ ] Research: 

- Which links should be in the footer? 
- For the full site, and the interim? 
- For the interim, which details should we include in a short (1-2 sentences) description? 
- Which links or info should appear in both the top nav and footer? 
- Check with Aly about social links: are any of these required? Which ones get the most traffic? 

- [ ] Talk to @kriskristin about testing. Questions: why do people go to the footer? Which links or info are they looking for?

**Comment by chasechenevert** [comment]
# Footer use cases  
NN/Group Footers 101: [Design patterns and when to use](https://www.nngroup.com/articles/footers/)

### Most common use cases for footers
1. Users scan or read the page and either don't find what they want or need more information. They scroll to the bottom of a page and use the footer as: 
a. A second chance to be convinced
b. a last resort for hard-to-find content
2. Users intentionally scroll to the footer to find information they expect to appear there, such as contact information, details about the company, social media posts or links, or even to discover new or related content on the site.

**Comment by desigonz** [comment]
@desigonz to work with Chase after pinup on 8/20/19 to develop acceptance criteria

**Comment by desigonz** [comment]
Moving this to next sprint; by end of sprint 38, let's have mocks and acceptance criteria ready to go to dev

**Comment by chasechenevert** [comment]
# Proposal
- **Dark version.** Clearer distinction between body and footer sections. Links are blue (as opposed to changing them to a white color) so that it's consistent with link color elsewhere. Contrast between foreground and background is accessible with a ratio of 8:1. 
- **Content is reorganized.** Content is clustered by related utility: about the project, social links, legal information are all grouped into sections.
- **Logo is centered, and full color.** Centered position gives the logo more prominence and acts as a dividing element between doormat navigation and utility links. The CoA logo is difficult to recognize at small sizes when used in the reverse (white) version. The full-color version has more variation and therefore sticks out in the design more than a reverse logo will, making much more recognizable.

![Sprint 38 pin-up #1_social link color modification@2x](https://user-images.githubusercontent.com/7027270/64188148-74d2b580-ce37-11e9-8855-1fe4acf0e94a.png)

## Accessibility check: color contrast
Targets: AA = 3:1, AAA = 4.5:1
<img width="777" alt="Screen Shot 2019-09-03 at 10 17 30 AM" src="https://user-images.githubusercontent.com/7027270/64186542-a302c600-ce34-11e9-9a83-ab07dec06c22.png">

**Comment by desigonz** [comment]
Visual design is done, @desigonz to review and write up acceptance criteria. Question on how the footer links (privacy policy, legal note) are managed.

**Comment by desigonz** [comment]
Acceptance criteria captured in #2948 (Janis) and #2950 (Joplin). The latter will need some work/fleshing out further.
