### ISSUE TITLE
Topic/topic collection mental model

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2645]
Issue for managing topics/topic collection outside of the page—both in and out of the content creation flow 

-------
**Objective** 
Dev and design need to sync on topic/topic collections mental models.

**Participants**
@toribr 
@desigonz 
@briaguya 

**Agenda**
Discuss how topic/topic collections appear and are managed in JOPLIN only. Sure they are pages, but from an author standpoint, don't have the same mental model as pages with content, but are instead containers which form the IA. I'd like to see if we can figure out a way to create/manage them that reflects them as IA. As part of this discussion, roles should be discussed as well, as control of topics/tc's would fall to an editor role, and remain largely invisible to authors.

------
- [x] Schedule meeting
- [x] Meet during dev/design sync 7/30
- [ ] Create resulting issues

**Comment by toribr** [comment]
![image](https://user-images.githubusercontent.com/3790067/61956943-c90a9000-af83-11e9-96e7-df5b43701238.png)
Above is for reference for topic selection v topic creation.

**Comment by easherma** [comment]
Brain dump of questions:
What are the working definition of topic & topic collection?
What are the attributes of a topic? I.E. does it differ greatly from what would be considered a tag in most models? And a topic collection is a collection of tags?
Topic collections are represented as pages, do topics also have a page representation(both currently do, but the distinction doesn't make much sense to me)?
Can we have a working, fleshed out example of this relationship to point to as a test example? 
What are the rules regarding topics and topic collection? Can one topic belong to multiple collections?

**Comment by toribr** [comment]
Topic and topic collection are very nearly the same - here's how I've been thinking about them from a *content* point of view. (there may be no distinction from a dev point of view. Study mass.gov for a robust working example, since it's largely served as our inspiration.)

Brain dump of explanations:
Topic collections and topics are both nodes in the hierarchy. The difference between them is that topic collections contain groups of topics. Topics contain groups of pages.  Topics are essentially the next to last node before pages, whereas topic collections may (though, not yet) have several levels, ie, tc > tc> topic > page. Both topic collections and topics are landing pages. I would not consider TC or topics to be related to tags at all. As for whether topics can belong to more than one TC, probably yes, but I don't know that we have a good example for that yet.

**Comment by desigonz** [comment]
@easherma Is the info in #2575 helpful in explaining some of this?

**Comment by easherma** [comment]
Desi looked for a page and ended up at a topic instead of the right page she wanted
IA pages separate from other kinds of pages

**Comment by desigonz** [comment]
### As a content editor, I want to see content pages (department, info, service, guide, and official docs) separately from IA pages (TCs and topics) because I conceptualize content and IA separately.

Nearer-term solution: 
- Use search page as main content page.
- Update filters for our needs 
- Set default to filter out TCs and topics.

Longer-term: fancy create content modal that allows users to choose and create new TCs and topics.

![image](https://user-images.githubusercontent.com/5839508/62577116-d5d09300-b863-11e9-9be4-5205a5cfaf0d.png)

**Comment by easherma** [comment]
@desigonz we can implement separate views based on page type pretty easily in Joplin. This doesn't have to be pushed out.

**Comment by desigonz** [comment]
assigned to @desigonz to check if we have issue for longerterm then close
