### ISSUE TITLE
Test out Generic Chooser

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2678]
For possible use in Joplin.

From @easherma:
> Pros:
> It was pretty quick and seems pretty extensible
> You can see the default flow from the model, You get a search tab and then another tab to create a new item if you dont find one you like
> 
> Cons:
> We hide tabs with our template overrides so my quick fix was nuking our template customizations. Obviously I could take a more nuanced approach but I just wanted to make the thing show up.

![image](https://user-images.githubusercontent.com/5839508/62498255-37312d00-b7a4-11e9-9c5f-2cd1051721ca.png)

**Documentation**
https://github.com/wagtail/wagtail-generic-chooser

from @easherma:
> the docs for the DRF version seem to imply sending POST requests to existing api endpoints in order to create new items which is kinda interesting

**Comment by easherma** [comment]
can be tried here:
https://joplin-pr-try-generic-chooser.herokuapp.com/

I set it up so that, for service pages, you can now choose a theme (just as an example)
I also have it so that choosing departments uses a generic chooser widget

**Comment by toribr** [comment]
This doesn't seem that different than what's already implemented. Is it the "new" tab that I should be looking at? With a new UI on it, something like this would work, but in general I want to move away from making this selection (by default) AFTER page creation, but instead support the author making these choices prior to page creation.

**Comment by desigonz** [comment]
@easherma I'm not seeing the generic chooser for themes or topics, only departments. (Not seeing themes at all.)

**Comment by easherma** [comment]
@desigonz I removed the theme selection from a service page since service pages can't actually pick themes and I didn't want to confuse anyone. So its true, it's only implemented for departments. 

The main difference is built in search of available models and the ability to create a new one if you didn't find what you are looking for. 

The good news is the generic chooser splits up the functionality choosing the related stuff with how it actually looks, so we can override this template and make it work however we want. 

For example, we could (and probably should) refactor our create content modal to use the generic chooser under the hood, which should be better to maintain/extend over time and more in line with future Wagtail stuff.

**Comment by desigonz** [comment]
Very cool, thanks @easherma!
