### ISSUE TITLE
AAC Foster Form transitioning to alpha

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#269]
I think there will be some accompanying design work and product decisions that may be blocking this, but here are some rough thoughts/vague ideas for paths forward for adding AAC foster forms to alpha from a technical perspective.

What Julia has designed and built uses Bootstrap and jQuery. We decided to do this as a team because it is relatively easy for non-devs to learn and prototype quickly. It is different from the React/component based front-end architecture we are using for the rest of alpha. Which leaves us with some questions about how to move forward...

- (Most importantly) Is AAC bought into using this form going forward? Do they even want this on alpha?
- Should we keep building on the prototype as is (in Bootstrap + jQuery) and just try to re-skin the front end to look more like the rest of alpha? If so, what domain would it live at? Would we continue to use Jekyll and gh-pages for hosting?
- Or, should we take the learnings from the prototype and rewrite it using React components? I see this as taking one step back and two steps forward since it would be more work but set us up to build more custom forms in React.
- Does the form need to living within alpha? Or could the application form be linked from a service page? Back to the question of hosting. 
- Where does the user's data go? Right now, none of the data is persisting. We know AAC currently just gets the data as an email. Do we want to kick off an email job with the data? Or should we set up a proper datastore? Or is there a hosted service we'd send the data to? This also breaks new ground for us around how do we handle PII responsibly. 

This is probably worth an IRL discussion but I just wanted to put some of my thoughts together to kick things off. cc/ @benweatherman @ifsimicoded @juliazbyron @MireyaGalarza @amenity

**Comment by amenity** [comment]
>(Most importantly) Is AAC bought into using this form going forward? Do they even want this on alpha?

I believe that if we got V1 (below) implemented, they would be willing to change over to our service page being what shows up when you click the red "FOSTER" button [in their menu](http://www.austintexas.gov/department/aac). The look and feel shift will be quite jarring to the user, however, so we will need to think about what that flow would look like — text that tells them they are moving to alpha? An invitation to try out the new form or continue with the old form? Retention/replication of the AAC menu at the top of the page if they come to the form from the current Austintexas.gov? 

>Or, should we take the learnings from the prototype and rewrite it using React components?

Yup! Definitely want this to be the next step. Forms will be coming fast and furious as we get services transitioned. 

>Does the form need to living within alpha? Or could the application form be linked from a service page? Back to the question of hosting.

I think it could be linked to from a service page for the time being, if @juliazbyron & @cthibaultatx agree.  Long-term, I would like to see longer forms like this retain the menu/header/footer of the main site, [à la Indy.gov](https://my.indy.gov/activity/property-tax-deductions-for-disabled-veterans-and-surviving-spouses)*. Given that, @mateoclarke - does it make sense to get the form living in alpha sooner rather than later? Another one-step-back two-steps-forward question. 

> Where does the user's data go? Right now, none of the data is persisting. We know AAC currently just gets the data as an email. Do we want to kick off an email job with the data? Or should we set up a proper datastore? Or is there a hosted service we'd send the data to? This also breaks new ground for us around how do we handle PII responsibly.

*V1* just needs to kick off two emails:
- A confirmation email to the applicant with the information they submitted in addition to thanks & next steps text. 
- An email to AAC with the information submitted so that they can manually enter it into their shelter management software. 

Here is what both of those emails look like today:
![fostercareapplicationconfirmation](https://user-images.githubusercontent.com/1463708/38657329-30b7998a-3de5-11e8-9fdb-bc2c96c50460.png)

As you can see, there are gains to be made in both applicant and staff UX simply by improving the formatting — and, in the case of the applicant, explanatory content — of the email.

*V2* should handle data storage. Initially, we were hoping that the data would be able to sent directly to AAC's new shelter management software, [Vestafy](https://www.clarisoft.com/portfolio/vestafy/). However, they have delayed procurement of this tool and the truth is that we don't even know a) what their API looks like and b)whether this is even the most useful place for the data to live. SO, @MireyaGalarza is working on #206. As you can see, that's a big ball of wax to look into.  

_*They're using Screendoor FWIW._

**Comment by juliazbyron** [comment]
I made a separate task for creating the service page that includes me, @cthibaultatx and @courtneyjacinic but I'll leave you guys in this for now because there may be more tasks that come out of this, like working on the email messaging for @courtneyjacinic . But I don't think the email task or all of these tasks need to happen in the upcoming sprint.

**Comment by mateoclarke** [comment]
**Notes from impromptu meeting**

## Next Steps:
- Julia wants to:
    - synthesis results from usability testing
    - copy edits changed in the prototype
    - UX and visual design updates  in Sketch
    - draft proposal/presentation for AAC
        - Create proposal that we add the form with service page alpha to AAC with usability test result & insights. Tuesday after next.
        - show an existing service page that would link to the form
    - work with Courtney on content for emails
    - work on Service Page with Celine
        - move some of the start page text to the service page
    - [backlog] For redirecting, figure out the places the ppl are coming from
       - High level look at workflow, entry point in Google Analytics.
       - are people coming from searches or from the existing service pages or from Facebook
     - add feedback component to form. tbd on what pages.
- Devs 
    - could start building form components in React
    - create a schema JSON static file that Janis turns into the form
    - use Matt’s email micro service or build our own emailing service
    - come for persisting the data, loop in Mireya
        - DB
        - temporary alternative way to look at data
        - check for an existing record?

cc/ @juliazbyron @amenity @ifsimicoded @MireyaGalarza

**Comment by juliazbyron** [comment]
![image](https://user-images.githubusercontent.com/13106016/38705874-bd282872-3e70-11e8-95d6-b492386a64f9.jpg)
This image shows our proposed path for getting the form on alpha on the top, and the options for getting the data into AAC’s dB on the bottom.

**Comment by mateoclarke** [comment]
I logged the dev tasks that came from this. We can close this issue whenever y'all are ready to.

**Comment by juliazbyron** [comment]
Cool, it's on my to-do list to log the design tasks today.

________________________________

**Comment by juliazbyron** [comment]
I logged all the tasks from the 'Julia wants to' list. @amenity are you ready to close this?
