### ISSUE TITLE
Make it so phone numbers don't break builds

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2702]
#2408 will make it so that adding multiple phone numbers doesn't require JSON, and therefore won't break builds every time phone numbers get added incorrectly.

In the interim, let's make the model support multiple phone numbers and get that working through and through.

**Comment by easherma** [comment]
Copying from #2039 
As a content editor, I want to be able to add multiple phone numbers for a contact and be able to indicate what each number is for, so that end users can know which is the right number to call.
Acceptance criteria

  A content editor can add more than one phone number
  A content editor can add a description for each phone number (ex. "Appointments" vs "Breastfeeding hotline" on the breastfeeding support information page)
Additional context
As an example, see the contact section for the breastfeeding support information page

Figure out a good way to handle multiple phone numbers for contacts (both in Joplin and Janis)

Before #1950 we tried handling this with JSON.

In Joplin:
We should update the contacts data model to support multiple phone numbers

In Janis:
We should work with design to make sure we know how to display multiple phone numbers.

**Comment by easherma** [comment]
I got an initial stab up here: https://github.com/cityofaustin/joplin/pull/330/

# What this does
Makes a new field like so: 
![phone](https://user-images.githubusercontent.com/10539855/62891999-c8f0eb00-bd0c-11e9-9e3b-3ac43335d6e8.png)

As an orderable so it can be moved around, each one added or removed, etc. 

This also brings in a django library for formatting, storing phone numbers. With I set it up to follow this format: 
![phoneformat](https://user-images.githubusercontent.com/10539855/62892049-eaea6d80-bd0c-11e9-9ce6-633834373119.png)

Reason being, if the phone number being passed to janis is, for example, `'tel:+1-512-974-9090'`, that should make it fairly trivial to parse phone numbers in janis and also make sure they are links that open to dial in mobile. 

## TODOs:

- Expose this new snippet item in our graphqlapi
    - this is annoying because we currently have __PageContact blocks for each kind of page to add contacts, lots of places to go change this code
- see how phone numbers are parse on Janis, what needs to be tweaked there
- someone (ideally content) can copy the old phone numbers into the new fields and add new/additional numbers as needed
- Although you can basically enter the phone number in common formats, it will parse and store it according to our settings. It would be nice to display those back in a friendly manner, however. 

## questions

Are there any any page types that would **not** have contacts associated with them?
We currently allow multiple contacts to be associated with a page. Any examples of this IRL? This is probably a larger question we should explore, because you could have multiple locations and/or contact phone numbers for a single contact, and then also multiple contacts for a single page, and that could get super complex and confusing. 
( In the OPO example, does multiple phone numbers for the OPO Contact snippet make sense, or would it be better to have two separate snippets for each phone number? What about variable locations? )

**Comment by easherma** [comment]
upped to 5, cause we're gonna need to write a new Janis component

**Comment by toribr** [comment]
Answers?

> Are there any any page types that would not have any contacts associated with them?
I don't see how this matters, but it's unlikely.

> We currently allow multiple contacts to be associated with a page. Any examples of this IRL/as a theoretical that we can have for testing?
Check the example that Desi gives above. It looks essentially like:

Appointments: (512) 972-6700
Breastfeeding hotline: 1 (800) 514-6667

**Comment by desigonz** [comment]
We're also currently using multiple phone numbers on the OPO pages: https://alpha.austin.gov/police-oversight/

**Comment by desigonz** [comment]
And for your longer-term question, it does look like we have the ability to add multiple contacts, but we haven't chosen to do so. I think let's keep as is now and we'll pose that as a content governance question, then build that into the content model for Joplin 3.0.

**Comment by desigonz** [comment]
- [ ] Make phone description field not required
- [ ] Reverse order: phone number first, then description

We also have issue #2408, in which @chasechenevert and @toribr and content folks will design ideal front and back end experience, as well as microcopy and style guide needs.
