### ISSUE TITLE
Watershed report design

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2713]

**Comment by chasechenevert** [comment]
## Update
We're going to push this back to next sprint since it's increasingly likely that they won't end up delivering the final report this sprint. Just FYI that I'll also be out next Thursday, August 29 and Friday, August 30.

## Draft content

[IHEMP Report aodraft 2 _JB_TC (1).docx](https://github.com/cityofaustin/techstack/files/3517014/IHEMP.Report.aodraft.2._JB_TC.1.docx)

## Preliminary questions for Watershed: 
- [ ] Will they be printing locally in an office, or using an external vendor? This helps me know how the final should be delivered (crops/bleeds, embedded assets, paper specifications, margin, and binding), or whether to be conservative with colored ink, and pagination.
- [ ]  Do they have any images they want to incorporate? If they do, and this report will be public, I'd like to make sure we capture the photographer credits. For print production we'd need any image assets in high res (300 PPI). 
- [ ] Do they want to visualize any data in the report (charts, etc.)?
- [ ] Will they need an interactive PDF (live links embedded in the digital file)?

**Comment by desigonz** [comment]
@chasechenevert I cleared this milestone but let's add it back if we get word from Watershed.

**Comment by chasechenevert** [comment]
[report_watershed_201917_final.pdf](https://github.com/cityofaustin/techstack/files/3622144/report_watershed_201917_final.pdf)
