### ISSUE TITLE
Revise compost form copy

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2787]
- [x] @annieszot to review compost form copy
- [x] @annieszot to send to Vince for revisions/approval
- [x] check new copy against translations—do we need to send out for new translation?
- [x] follow up with Houma on CPIO forms for funding interpreters  - email sent 8/22

**Comment by annieszot** [comment]
Language access support to departments from CPIO: 
CPIO has the funds to support departments with interpretation services. The process is fairly simple. Because our funding is on a first come first serve basis, we ask that you let me know before you reach out to an interpreter to make sure CPIO can cover the services.

-           Contact interpreters directly and request their services for your event. CC’ me on the email with the interpreters.

-          If the interpreter accept the request, ask for a quote to be sent to you and me.

-          After the event, the interpreter(s) will send an invoice to us and I will take care of the payment.

**Comment by annieszot** [comment]
Next steps - ARR internal project communications - new issue #2865
