### ISSUE TITLE
Janis - ContextualNav leftmost link not vertically centered when related to: takes multiple lines 

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2843]
**Acceptance criteria**
- [ ] Leftmost link top aligned when "related to" wraps to multiple lines

## Good
<img width="786" alt="Screen Shot 2019-08-28 at 8 29 24 AM" src="https://user-images.githubusercontent.com/6384156/63860226-5d468900-c96e-11e9-8209-9a51e78fbfb0.png">

## Bad
<img width="779" alt="Screen Shot 2019-08-28 at 8 29 33 AM" src="https://user-images.githubusercontent.com/6384156/63860242-659ec400-c96e-11e9-831b-b8edee04dd1e.png">

**Comment by chasechenevert** [comment]
The second screenshot was a change that I input. I want the leftmost link to be top-aligned rather than centered vertically when "related to" breaks to multiple lines so that as the user is scanning left-to-right, I want that line to be relatively flush to better support scanning.

This is really just an MVP until we have better understanding of how many "related to" links the average page will have, and how long the link titles are so that this doesn't become to heavy above-the-fold.
