### ISSUE TITLE
Research forms to prep for forms transitions

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2849]
With Formstack, we'll now have the capability to transition forms more rapidly. But we want to make sure we're bringing our service design ethos to all forms, working with stakeholders and equipping them with the tools to design resident-focused forms.

## Digital forms guide
CTM has a team that's been working on a digital forms guide: https://city-of-austin.gitbook.io/digital-forms-guide/

Lots of overlap with the kind of work and thinking we do! How might we be able to collaborate with them? We've established some of our own form conventions. How might we be able to come to common conventions? How can we leverage the design principles here as we work with CoA stakeholders?

## Orlando Service Design Academy
Orlando has a great model for transition forms in which they workshop and test with stakeholders. Let's review their approach and see how we might be able to incorporate this into ours.
https://drive.google.com/drive/folders/1tFuiH5FQ9S4tNSjvt-82KYqtjyxg1Jeb

## Start looking at forms
We're going to start by transitioning Austin Public Health forms. Let's take a look at existing APH digital forms that live on Drupal.

**Comment by desigonz** [comment]
- [ ] @ablangworthy27 to add documentation and then close issue

**Comment by ablangworthy27** [comment]
## Digital forms guide

- This guide is more theoretical/best practice than instructional. I have started to think about ways to use this in conjunction with Joplin instructions (for the far future when we have users)

## Orlando Service Design Academy - important takeaways that are currently not being practiced by COA in drupal or PDF forms

- Create intentional dead ends for users who do not qualify AND clearly explain why

- Ask only what is necessary and skip what doesn't apply (use logic)

- Ask for contact info only when necessary

- Have the end of the form set expectations for future

## Start looking at APH Drupal forms
***One thing that hindered my ability to look at some of these was that they are live and I don't want to mess anything up for APH
- I was able to look at first steps of the forms, and the entirety of the simple forms, and establish where they fall in terms of currently living up to standards set both in the Forms Guide and by Orlando Service Design Academy.

- currently trying to track down/contact individual stakeholders for each of the 5 forms

## Etc...

- Found this resource, and think the visuals are helpful
[https://uxdesign.cc/design-better-forms-96fadca0f49c](https://uxdesign.cc/design-better-forms-96fadca0f49c)
