### ISSUE TITLE
"Forgotten it?" to "Forgot it?" on Joplin sign-in 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2861]
Technically "Forgotten it?" is okay (past participle) but "Forgot it?" is simpler (past tense). ![Screen Shot 2019-08-29 at 2.42.52 PM.png](https://images.zenhubusercontent.com/5c4b52abd709c56fe9edad32/cb1a11c9-06ea-4707-921e-10df7806788f)

**Comment by easherma** [comment]
@desigonz One thing to consider for QA is that resetting the PW dosen't even work/do anything atm. It might be better to just hide the copy rather than adjust the copy while still linking to something that doesn't functionally do anything, and we should probably make an issue for setting up email stuff and handling password resets if that is in scope for Joplin.

**Comment by desigonz** [comment]
QA passed, but also I think this is already in staging?
