### ISSUE TITLE
"View live" immediately after publishing

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2872]
**Describe the bug**
As a content editor, I want to click the "view live" link immediately after publishing a page and open up the published page, because that's my mental model and because the Joplin dashboard tells me it's publish. However, there is a 6ish minute delay between when a user publishes a page and when the Janis build deploys. 

**URL**

**To Reproduce**

1. Go to Joplin staging
2. Create a new page
3. Publish the page
4. On the "Pages" listing, click "view live"
5. See error

**Current behavior**
Opens the Joplin pages page

**Expected behavior**
Not sure. As a user, I would expect the page to immediately publish and then to be able to view it. Considering our constraints, maybe the dashboard can indicate that the page is pending?? 

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by easherma** [comment]
It's especially confusing because the draft/preview will work but 'view live' won't show the latest changes.  
Easy fix would be to remove 'view live' in the understood sense, and have joplin just show a preview of the latest published draft.

**Comment by desigonz** [comment]
User clicks button, opens in new page with copy explaining that it takes a while to build, please reload in X minutes, button to reload.

Goal: set a reasonable/fair expectation for user.

**Comment by toribr** [comment]
![2872](https://user-images.githubusercontent.com/3790067/64996623-087a9c00-d8a4-11e9-8abc-5b33f56bcc43.png)

This version for discusson purposes. Exact language and design tbd.
Questions for discuss

:

- [ ] can we set a timer to show the user how long until it'll be published?
- [ ] can we refresh the page WHEN the page is published? (so that if the author leaves the tab open they can return to view the page without further action?)
- [ ] since we know who the user is, is there any benefit to allowing them to click a button that says "send me an email when this page is published"? In this way they can have more trust that the system will actually publish their page.

**Comment by easherma** [comment]
What I was trying to ask during sync is what is the value of this button for the user? Is it to see what _is_ live on Janis, or is it to see the most recently published changes for that page in Joplin? 'View Live' is probably confusing in this context cause it can mean a couple different things.

**Comment by desigonz** [comment]
@easherma The purpose of the button is to see what is live, but also they would expect to see what they just published because that's their mental model. But as we discussed in dev/design sync, we're backlogging this until we work on incremental builds.

**Comment by desigonz** [comment]
Taking care of this in #4061
