### ISSUE TITLE
The Top Banner needs to be aligned with the Main Nav, Secondary Nav and Top dropdown

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2895]
The Top Banner needs to be aligned with the Main Nav, Secondary Nav, and Top dropdown.

URL: https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

To Reproduce:
1. Open the link URL above
2.Notice the Top Banner

Current behavior: Please refer to the attached screenshot.![Banner.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/513011e6-d740-44c9-91a2-1832022c2a6e)

Expected behavior: The banner Max width needs to be 1160px, refer to the 
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/58cef195-a92f-450c-ba2e-4124f44b9469/Template-Guide-desktop/

**Comment by desigonz** [comment]
Also:

The Top Banner needs to be aligned with the Main Nav, Secondary Nav, and Top dropdown.

URL: https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

To Reproduce:
1. Open the link URL above
2.Notice the Top Banner

Current behavior: Please refer to the attached screenshot.![Banner.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/513011e6-d740-44c9-91a2-1832022c2a6e)

Expected behavior: The banner Max width needs to be 1160px, refer to the 
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/58cef195-a92f-450c-ba2e-4124f44b9469/Template-Guide-desktop/
