### ISSUE TITLE
Global nav hamburger menu

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2899]
**Describe the bug**
Hamburger Menu Icon Is different from the Mobile design Guide

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**
1. Go to the above URL
2. Notice Hamburger Menu at the top

**Current behavior**
Refer to the attached screenshot
<img width="418" alt="Menuscreenshot" src="https://user-images.githubusercontent.com/52670306/64287589-b5a8f800-cf25-11e9-9c8b-d547019b4330.png">

**Expected behavior**
<img width="106" alt="Expected Menu Icon" src="https://user-images.githubusercontent.com/52670306/64287720-10daea80-cf26-11e9-93d2-92e4d24f9c14.png">

**Screenshots**

**Device**
Phone: Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2

**Browser**
Chrome 71.0

**Additional context**

**Comment by chasechenevert** [comment]
This is intentional to distinguish the `Table of Contents` from the `Primary Navigation`.

**Comment by desigonz** [comment]
Relatedly: 

**Describe the bug**
The Hamburger "Menu" text at the top corner is  not following the style

**URL**
https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

**To Reproduce**
1. Go to the above URL 
2. Check the "Menu" right next to the Hamburger Menu.

**Current behavior**
<img width="392" alt="Menutext" src="https://user-images.githubusercontent.com/52670306/64288560-0c173600-cf28-11e9-9904-3f64bb56cd9c.png">

**Expected behavior**
top: 106px;
left: 49px;
width: 40px;
height: 20px;
text-align: left;
font: Regular 16px/29px IBM Plex Sans;
letter-spacing: 0.01px;
color: #FFFFFF;
opacity: 0.75;

**Screenshots**


**Device**
Phone: Galaxy s9,Pixel 3XL,Nexus 7,LG G5,Moto x Gen2

**Browser**
Chrome 71.0

**Additional context**

**Comment by chasechenevert** [comment]
Good catch, this is a mistake. The implementation of the icon is correct. Updated the spec to reflect this.
