### ISSUE TITLE
Fix font style implementation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2908]
@chasechenevert went through how fonts have been implemented across Janis and has a few fixes for ya:

**Acceptance criteria**
- [ ] `li` list items need `1em` of bottom margin [example](https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/household-waste/compost-pickup). 
- [ ] Information page: heading weight should be `500`(medium weight), matching H1s elsewhere.
- [ ] H2s on Department pages should be 3.2rems. [Department page](https://janis.austintexas.io/en/police-oversight) H2s are being overridden and displaying as 2.4rems, making them consistent with H2s on [service pages](https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup/).

**Comment by desigonz** [comment]
@briaguya to work with @chasechenevert on figuring out full specs

**Comment by chasechenevert** [comment]
More examples: 
- https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/compost-food-waste/compost-pickup
- https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/trash-recycling-pickup
- https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse/pickup-free-paint

**Comment by briaguya** [comment]
@chasechenevert so for the `<li>` part:

Just make sure we have space below any list items in "Write any additional content describing the service" on service pages.

So we don't run into:
<img width="583" alt="Screen Shot 2019-10-03 at 1 13 32 PM" src="https://user-images.githubusercontent.com/6384156/66152933-26543a80-e5e0-11e9-8ce7-ba25e21c79d1.png">

At this point since we're using lists all over the place and styles are fighting each other, I'd like to define the scope of this entirely.

so far we have:
* Service page - additional content

**Comment by desigonz** [comment]
@briaguya I believe this needs to be across the board for any content from a rich text block— @chasechenevert would you agree? If so, Brian, how would you estimate refactoring those styles?

**Comment by briaguya** [comment]
![Screen Shot 2019-10-03 at 5.04.10 PM.png](https://images.zenhubusercontent.com/5afb42ab4b5806bc2bd34c32/794db188-d892-42f4-97a9-489af9565b23)

another spacing thing

**Comment by briaguya** [comment]
Test data up here: http://joplin-pr-2908-test-data.herokuapp.com/admin/pages/3/

**Comment by briaguya** [comment]
Made a janis build against test data to make this easier to parse.

**Comment by desigonz** [comment]
@chasechenevert, @briaguya, and I met today and broke this into these issues: #3183 #3182 #3184 #3186
