### ISSUE TITLE
Make Staging Joplin look different from prod

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2963]
People accidentally log onto staging thinking its production and vis versa. We could change the background color in staging to clearly indicate which site people are on.

**Acceptance criteria**
- [ ] Change background color to `#3f5880`

**Comment by toribr** [comment]
May I suggest #3f5880. @desigonz We should move this up. A little dev time in the short run could save a lot of redoing in the long run. :)

**Comment by desigonz** [comment]
@toribr do you mean move up this issue? or a different one? there's a typo in your issue number above

**Comment by toribr** [comment]
@desigonz #3f5880 is my suggestion for color to change it to. :)

**Comment by desigonz** [comment]
lol duh got it! thanks @toribr

**Comment by desigonz** [comment]
@toribr added the acceptance criteria and assigned for dev.

**Comment by easherma** [comment]
Where do we want this background color to show up? There are lots of background colors set at various levels in Joplin/Wagtail, not as simple as changing a single value.

**Comment by toribr** [comment]
![staging_color](https://user-images.githubusercontent.com/3790067/67576936-28a04500-f705-11e9-9a5a-00eb97a19b01.png)

@easherma Good question. It doesn't need to be propogated everywhere, since really what we're wanting is simply a way to signal the different server. If we can change it in the header and side bar as shown here, as well as on the log-in screen, i think that'll be sufficient.

**Comment by easherma** [comment]
Changes live at: https://joplin-pr-2963-themes.herokuapp.com/admin/login/

**Comment by desigonz** [comment]
Looks good! QA done.

**Comment by easherma** [comment]
QA passed

**Comment by easherma** [comment]
QA passed
