### ISSUE TITLE
Document management UX

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2973]
### As a content editor, I want to be able to upload and manage documents in Joplin, so that I can easily add documents to the pages I'm publishing.

**Is your feature request related to a problem? Please describe.**
We're already uploading docs for OPO official document list pages, and soon we'll want to upload documents for guides.

**Describe the solution you'd like**
@briaguya stood up a proof of concept of document management on this branch: http://joplin-pr-2811-play-with-docum.herokuapp.com/admin/documents/
Let's review the user experience. What works for MVP? What doesn't?

**Describe alternatives you've considered**

**Additional context**

**Comment by toribr** [comment]
The big issue with wagtail is that images and documents should be able to be added within page templates, and not require first adding them to the image/document library. 

Additionally, folders are going to be need pretty quickly for documents and images. 

But before that even, because documents don't have any visual affordance, we should at least add a column for who uploaded it. That way i can search for my own docs without having to remember the name of the document.

**Comment by desigonz** [comment]
These acceptance criteria are taken care of in #2991 and #3032. Closing this issue!
