### ISSUE TITLE
Look into sketch + code integration tools

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#3]

**Comment by ifsimicoded** [comment]
@toribr posted this medium post on [sketch+code integration](https://medium.com/seek-blog/sketching-in-the-browser-33a7b7aa0526?ref=uxdesignweekly)  in slack which may be a better solution.
I wouldn't spend too much time troubleshooting sketch-react just yet since we haven't made a real decision on this.

**Comment by amenity** [comment]
@cthibaultatx - is this related to a particular design phase or other feature?

**Comment by amenity** [comment]
@cthibaultatx is this guy still in the backlog?

**Comment by amenity** [comment]
@cthibaultatx Gotcha. When would you like to do this?

**Comment by cthibaultatx** [comment]
too early for this

**Comment by amenity** [comment]
https://blog.zeplin.io/introducing-zeplin-2-0-components-and-a-ton-more-goodies-7c09dacc1f48

**Comment by amenity** [comment]
no longer relevant
