### ISSUE TITLE
Formstack for reusing applications year after year

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3004]
Sara Smith in CTM is working on the Universal Recycling Ordinance with Austin Resource Recovery. In the next 18 months, they want to switch to a new system, and are looking for a solution that solves this user need:

### As a business, I want to be able to reuse the same Universal Recycling Ordinance application every year with the fields pre-populated with last year's answers, so that I can save time in getting my application in.

How might CTM be able to use Formstack to enable this? Would Formstack work out-of-the-box, or would CTM have to extend Formstack functionality via the API?

Let's spend a little bit of time looking at this and then share our knowledge back to Sara, but let's time box this to 2 hours.

**Comment by Niicck** [comment]
What we're looking to do is pre-populate a form using data from a past submission.

We would have to work some magic with the API in order to do this.

Here's a blog detailing how to do it manually:
https://www.formstack.com/blog/2016/set-up-pre-populating-fields/

The relevant details begin at "If you want to autofill form data by pulling information from a completed form, it’s a bit more complicated." The blog describes kind of a weird manual process for extracting the field ID with the data you want. Some of that could be automated by a program that we'd have to build.

The end result would look like this. Basically you'd plug in the pre-filled values as query strings on a URL link to the form page.
<img width="452" alt="Screen Shot 2019-09-18 at 2 29 05 PM" src="https://user-images.githubusercontent.com/14187277/65179599-b1e69c80-da20-11e9-810e-24854b41c173.png">

And it would pre-populate like this:
<img width="718" alt="Screen Shot 2019-09-18 at 1 58 51 PM" src="https://user-images.githubusercontent.com/14187277/65178459-616e3f80-da1e-11e9-9487-f79049d8ca66.png">

An important question to ask is *how* would the business like to reuse applications? What does that look like to them? In Formstack's world, the specific recipient gets a custom URL that has form fields filled out already. There aren't users in Formstack, so a form-user couldn't log in anywhere and click "resubmit" on a past form. Things for them to think about.

**Comment by desigonz** [comment]
great! I'll share this with Sara in CTM and cc you.
