### ISSUE TITLE
Step number display in IE 11

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3039]
**Describe the bug**
In IE 11, step numbers aren't displaying as expected. Should have a circular light blue background.

**URL**
![image](https://user-images.githubusercontent.com/5839508/65534195-966a0e80-dec4-11e9-9686-4a3292e82165.png)

**Current behavior**
Step numbers have weird oval backgrounds
![image](https://user-images.githubusercontent.com/5839508/65534195-966a0e80-dec4-11e9-9686-4a3292e82165.png)

**Expected behavior**
Step numbers should have a circular background
![image](https://user-images.githubusercontent.com/5839508/65534204-9bc75900-dec4-11e9-95d6-f16aaa7706ba.png)

**Screenshots**

**Device and browser**
WIndows 7, IE 11

**Additional context**

**Comment by briaguya** [comment]
put a 5 on this because it looks like they are getting the blue background but IE is terrible with CSS always and it'll possibly lead to a large css refactor job.

**Comment by robbobfrh84** [comment]
I'm actually not able to replicate this error. I've tested on a couple different guides with IE 11... If y'all could check again and see if it's not just me...
-
It's possible that this was a "collateral-fix" from one of the guide issues I've worked on since then.
-
![Screen Shot 2019-10-15 at 2.28.21 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/4885fdf4-3551-4b38-819c-223bb0a9bf93)

**Comment by desigonz** [comment]
I see it on Browserstack when using IE11 on Windows 7. But also I'm cool to close this.
