### ISSUE TITLE
Make it so timeouts don't break builds

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3047]
Timeouts broke builds when we added a lot of pages at a time on Joplin staging. This is going to get worse as we have more data. Let's fix it.

There is a specific page that seems to have broken data that's causing timeouts (https://github.com/cityofaustin/techstack/issues/3048). This will also happen once we have lots of pages. 

We should investigate ways in which we can clean up inefficiencies in our build process/api

**Comment by briaguya** [comment]
I'm closing this one, I'm not sure if timeouts are causing the issue, and it could be a giant timesink.  I think instead of doin a directionless dive into it, we should just focus on https://github.com/cityofaustin/techstack/issues/3048 and make new issues for anything root-causy that we find that could blow the scope on it.
