### ISSUE TITLE
Janis/Joplin - Internal links in rich text fields don't work

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3053]
Joplin PR: https://github.com/cityofaustin/joplin/pull/408

Acceptance criteria
- [ ] link works
- [ ] link still works even if you change the topic the page is set to

**Describe the bug**
If we use the link option in a rich text field and set an internal link, the link doesn't work in Janis.

**To Reproduce**
1. Add a link to another page in a rich text field somewhere in Joplin.
2. Build janis against it and the link doesn't work.

**Current behavior**
the link looks something like:
```
<a id="11" linktype="page">drop off at the Recycle and ReUse Center</a>
```

**Expected behavior**
the link looks something like:
```
<a href="/housing-utilities/recycling-trash-and-compost/household-waste/hazardous-waste-dropoff">drop off at the Recycle and ReUse Center</a>
```

**Additional context**
We might find some things when fixing this that could help https://github.com/cityofaustin/techstack/issues/2942 happen

**Comment by briaguya** [comment]
seems like we should probably be using https://docs.wagtail.io/en/v2.6.2/advanced_topics/customisation/rich_text_internals.html#rewrite-handlers for this, but I haven't figured out how to get that working nicely with graphene (it seems like it's not being used at all, although it's possible I just haven't figured out how to make it work yet)

**Comment by briaguya** [comment]
gave this an 8 because:
<img width="796" alt="Screen Shot 2019-09-30 at 4 27 42 PM" src="https://user-images.githubusercontent.com/6384156/65918436-447f2800-e39f-11e9-9226-cbd8e93c1021.png">

**Comment by briaguya** [comment]
looks like we might be able to override this in drafttail http://docs.wagtail.io/en/v2.6.2/advanced_topics/customisation/extending_draftail.html

**Comment by easherma** [comment]
Janis: https://deploy-preview-556--janis.netlify.com/
Joplin: https://joplin-pr-3053-recursive-objec.herokuapp.com/


To test:
I added two links to this page:
https://joplin-pr-3053-recursive-objec.herokuapp.com/admin/pages/91/
See that they appear in Janis
To test end to end:
Add an internal link on a page in the above joplin 
Tell a dev to trigger a build of the above branch of janis
See that it all works

**Comment by desigonz** [comment]
### Test plan 
1. Make some links at PR app for Joplin: https://joplin-pr-3053-recursive-objec.herokuapp.com/admin/
2. ask @easherma to trigger a build
3. Test these:
- [ ] Internal link within service page basic step: does it work in Janis?
- [ ] Internal link within service page step option: does it work in Janis?
- [ ] Internal link on a department page rich text block: does it work in Janis?
- [ ] Internal link on an information page rich text block: does it work in Janis?
4. Then for those pages we've linked to, change the topic they're associated with. 
5. Ask @easherma to trigger another build
6. Test these:
- [ ] Internal link within service page basic step: does it work in Janis, even with new topic?
- [ ] Internal link within service page step option: does it work in Janis, even with new topic?
- [ ] Internal link on a department page rich text block: does it work in Janis, even with new topic?
- [ ] Internal link on an information page rich text block: does it work in Janis, even with new topic?

**Comment by desigonz** [comment]
- [ ] On Janis, the link didn't work within a **basic** step (but it did work in a regular rich text field and in a step with options.)
![3053-basic-step](https://user-images.githubusercontent.com/5839508/66612702-54112480-eb88-11e9-9993-3abe6f1c4cf5.gif)


**ALSO:** In this one, I changed the topic for the first link (should be the "File a complaint" page) but it 404s. The URL it goes to is https://janis.austintexas.io/en/housing-utilities/recycling-trash-and-compost/compost-food-waste/file-a-complaint-about-an-austin-police-officer. I think the problem here is that the URLs use https://janis.austintexas.io, so we can't actually text step 6 til we go to staging.
![3053-changed-topic](https://user-images.githubusercontent.com/5839508/66612766-9470a280-eb88-11e9-881e-658c849e6c0e.gif)

**Comment by easherma** [comment]
@desigonz the basic steps issue should be addressed

**Comment by desigonz** [comment]
@easherma Great, it works! Whenever you're ready, you can push to staging and I'll do QA step 6.

**Comment by desigonz** [comment]
1. @Niicck will finish out staging-style testing on PR apps
2. Then we'll test this one fully

**Comment by easherma** [comment]
@desigonz 

You should be able to test/preview/publish to your heart's content using the following:
https://janis-3053-test.netlify.com/
https://joplin-pr-3053-recursive-objec.herokuapp.com/

Publishing is still gonna take awhile, and unfortunately we don't have build notifications populating anywhere but inside the Netlify account directly, though i'm trying to change that. I tested previewing though it worked! But otherwise just keep in mind it might take a few minutes for a change to show up, feel free to ping me if you want status updates or to coordinate QA.

**Comment by desigonz** [comment]
QA passed and looks amazing! 🎉
