### ISSUE TITLE
Remove options section from info page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3072]
**Describe the bug**
There is an options section on information pages, but it doesn't actually produce options in Janis. Seems like it's actually just the ability to add rich text block via streamfields. 

**Acceptance criteria**
- [ ] For now, let's remove the options section. (We can decide to add it later if we find the need for it)
- [ ] We need to make sure no production pages are using the options section; if they are, switch this content to "Write any additional content describing the service"

**URL**
options: 
![image](https://user-images.githubusercontent.com/5839508/65806048-8022b380-e14d-11e9-8095-12227bcc3650.png)

Janis preview: ![image](https://user-images.githubusercontent.com/5839508/65806038-76994b80-e14d-11e9-9b71-b970838755e2.png)

**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by briaguya** [comment]
Note if we want to add them back in the future: in order to use Janis to produce options in ways similar to "steps with options," we need to have both the "option name" and "option description" as opposed to just a rich text block.

This means we won't be able to benefit from doing a "let's just hide this field from authors, so when we want it back it's really straightforward" plan.

**Comment by briaguya** [comment]
@desigonz this is on joplin staging now

**Comment by desigonz** [comment]
This looks good. I just went through Joplin prod and put any content that was entered via the "options" section into the "Write additional content" section.
