### ISSUE TITLE
Only first of multiple contacts are visible on Information page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3079]
**Describe the bug**
In preview mode, only the first contact selected is showing up on the right side of the information page

https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNzMw

**To Reproduce**

1. Go to 'Job search help at neighborhood cneters'
2. Notice multiple contacts selected
3. Click on 'preview'
4. See only the top contact selection shown on the preview page.

**Current behavior**

There are two contacts for the information page 'Job search help...". After assigning both neighborhood centers as contacts, I preview the page and see only the first selected contact on the preview page.

**Expected behavior**

I expected to see both contacts listed stacked on the right side in the order of selection.

**Screenshots**

**Selection in the editor**
![Screen Shot 2019-09-30 at 3.04.47 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/b20e7f75-06ad-4909-9e90-470019c3cc69)
**What I see on the preview page**
![Screen Shot 2019-09-30 at 3.05.14 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/b6e7fec8-4705-4c90-92c1-8645609ef8fe)
**Device**

Mac Laptop

**Browser**

Chrome

**Additional context**

**Comment by desigonz** [comment]
Assigning @chasechenevert to pull a quick mock together for this. Per our conversation, we'll make email not required, and pull in the address + collapsed hours.

These are the pages that will need multiple contacts:
    - [ ] [Free health services...](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxNzYw) 
    - [ ] [Get a copy of your immunization...](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxODYx)
    - [ ] [Neighborhood centers help...](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODYz)
    - [ ] [Job search help...](https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToxODM4)

If it's helpful, you can log into Joplin prod and look at how the contact info is entered for these pages.

**Comment by chasechenevert** [comment]
XD Prototype: https://xd.adobe.com/spec/f81c5f2d-3350-4720-79ff-cd73881cf143-8e2d/

- [ ] Display order is now: LocationName, Address, Hours, Phone, Email. This is a universal change to the component. This is to make the list of locations easier to scan by using the LocationName as a label.
- [ ] Spacing between location details is 20px
- [ ] Spacing between last location detail and the rule line is 30px
- [ ] Rule line is 2px, `#C6CACE`
- [ ] Hours is now collapsed behind a dropdown, and displays the current day and hours. I’m not sure what the right term is, but it should open in the way that an accordion does (where content below moves down, instead of overlaying like dropdowns typically are).

**Comment by desigonz** [comment]
We fixed this in #3127
