### ISSUE TITLE
Janis/Joplin - make guide previews

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3082]
looks like we never really implemented this at all, sounds like we should do that.

**Comment by briaguya** [comment]
@desigonz this is up here: https://deploy-preview-553--janis.netlify.com/en/preview/guide/UGFnZVJldmlzaW9uTm9kZToxNjgw

this is on the same branch as https://github.com/cityofaustin/techstack/issues/2473 and can be tested with it.

Super not-fleshed-out QA checklist:
- [ ] The link ^ looks good
- [ ] On staging: Guide previews work

**Comment by desigonz** [comment]
Looks great! Here's the QA list from guide browser testing—we can test against this.
- [x] Intro block—all the following appear
  - [x] Title
  - [x] Description
  - [x] Image
- [x] Content
  - [x] Contact information displays contact name, phone number, and email
  - [x] Section headings
  - [x] Content within each section
    - [ ] Clicking "View this page..." opens in a new tab (note: in order for this to work, each individual page needs to be assigned a topic or a department page in Joplin)
- [x] Table of contents
  - [x] When user opens guide on mobile/tablet, a table of contents (ToC) button appears on bottom of screen
  - [x] When user taps ToC button, menu opens and initially overlays onto the page within the bottom two-thirds so that a user can see content behind the menu overlay

@briaguya The one thing I can't verify is '"View this page..." opens in a new tab.' Let's check that when it's on staging?

**Comment by briaguya** [comment]
@desigonz the "view this page" on staging plan works for me,

That could balloon out of scope though, as the links will be to published URLs instead of drafts.

I think that might need to spin off into another issue if we want to support using draft URLs for each sub page of a guide.

**Comment by briaguya** [comment]
live on staging

**Comment by desigonz** [comment]
QA complete! Looks great.
