### ISSUE TITLE
Assessment of Residential Site Content and content structure

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#312]
Will be moving forward with DSD instead of EMS
Needs to be broken up. @courtneyjacinic. 

List of questions that each discipline needs to answer.

**Comment by courtneyjacinic** [comment]
Currently working on structure with @cthibaultatx. Keeping content the same for now, because any changes will need DSD approval.

**Comment by cthibaultatx** [comment]
@courtneyjacinic we talked about what to do with glossary items but didn't document. They are going to be challenging in future content, at least in the interim, because of need to have approved by legal for certain subject areas. The ones in permittingatx have already been approved so we'll build those in?

**Comment by amenity** [comment]
Duplicate of #457
