### ISSUE TITLE
Guide Pages are not español  friendly

### ISSUE THREAD

**Issue by robbobfrh84** [cityofaustin/techstack#3163]
**Describe the bug**
When toggling English to Español  in Guide pages, we see it does not...
-1- convert the language to español 
-2- headings are invisible. 

**To Reproduce**

1. Go to https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide
2. Click on `Español`
3. Scroll down to...
4. See error(s)

**Expected behavior**
- [x] When in español, Janis-hardcoded `Contact information` section header should read `Información de contacto`
- [x] When there is no Spanish section header entered in Joplin, Janis should default to the English section header

**Screenshots**

English...
<img width="414" alt="Screen Shot 2019-10-11 at 1 52 34 PM" src="https://user-images.githubusercontent.com/15821138/66678755-38625880-ec32-11e9-8688-8540a3582567.png">

Español...
<img width="392" alt="Screen Shot 2019-10-11 at 1 53 12 PM" src="https://user-images.githubusercontent.com/15821138/66678791-4b752880-ec32-11e9-9cc7-3ac664fe7163.png">

**Comment by desigonz** [comment]
Thanks @robbobfrh84 for reporting this! With our current translation model, when there's no Spanish content in Joplin, Janis will default to the English, so we should just follow that same convention for now.

Sarah's made an issue for translating mobile food vendor content, but you pointed out some other super important bugs. I've updated the acceptance criteria above.

**Comment by robbobfrh84** [comment]
Thanks for the clarification and putting acceptance criteria on this @desigonz.

**Comment by chiaberry** [comment]
@desigonz  okay, its finally ready for QA: 
The joplin branch is here: https://joplin-pr-3163-guide-pages.herokuapp.com/admin/pages/3/
The janis branch is here: https://janis-3163-guide-espanol.netlify.com/es/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/

I added a contact so we can see *Contact Information* switch to spanish. I also translated "Learn and Prepare" to "Aprenda y prepare" since the other spanish headings seemed to have disappeard

**Comment by desigonz** [comment]
@chiaberry looks great! QA complete.
