### ISSUE TITLE
Guide page for style guide

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3172]
We have a guide content type. Let's write up a style guide section for it.

**Comment by srigdon** [comment]
Reviewed! I added comments and made edits inline. @ablangworthy27

**Comment by srigdon** [comment]
Whoops, forgot to add this info: 

> What does a content strategist need to know to write a guide?
> 
>     

- a fully researched, fact checked service blueprint (map of the service end to end, with every event in the resident's experience and in the front line staff's experiences and processes)
- >     a list of everything a resident must do to achieve the goal (permit, license, etc.)
- >     copies of all of the forms a resident must complete and submit in order to achieve the goal
- >     will we be digitizing any or all of these forms? (or see forms workshop)
- >     enough availability from subject matter experts and front line staff who administer the service, not necessarily all but a staff member that touches each part of the process, so that a content strategist can fact-check the guide with them
- >     who will approve the content for it to be published

>
