### ISSUE TITLE
Janis mocks for single place page content type

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3195]
- [ ] Comp for Janis single place page content type

For MVP we'll be displaying:
- Phone
- Fax
- Email
- Hours
- Physical address

**Comment by chasechenevert** [comment]
The mocks contained in this document go beyond MVP, but when looking at these the MVP on the Place page is that first block/section.

XD: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/

- **Option 1**: labels with icons: desktop, tablet, mobile
- **Option 2**: icons, no labels desktop
- **Option 3**: labels, no icons desktop

- **First block contains MVP details**, and the last two cluster “services available” and “accessibility features” that we can continue to iterate as we think about standardizing this information.
- **Visually contained sections**: general details, “services offered”, “accessibility features”.  Previously details were left-aligned, and weren’t contained which created too much whitespace in the layout. Since this page doesn’t need a rail, and contact information tends to be lots of short lines, I wanted to try a mobile-friendly centered two-column layout 
- **Location image** is available within the “Location” subsection
- **Hours, additional information**: surface details related to availability like: appointment only, walk-ins, and additional hours
- **Services offered**: bullet list additional services that don’t have Alpha pages, and link to service or information pages that are on Alpha (like a topic collection). Optional way to surface important service access information for the user.
- **Accessibility features**: ability to attach images and link to alpha pages in subsections, and an idea for featuring bus routes

**Comment by chasechenevert** [comment]
Pushed the update here: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/

Over to you, @desigonz

**Comment by chasechenevert** [comment]
Pushed the update here: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/

Over to you, @desigonz

**Comment by desigonz** [comment]
Consolidated into #3400, will flesh out further there!
