### ISSUE TITLE
Formstack styling

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3196]
Going to take a look at creating a Janis theme for formstack using custom css within formstack.

**Comment by desigonz** [comment]
After that cross-team Formstack meeting we had a few sprints ago, @Niicck created a simple Formstack theme based on the Day Labor Form. You can view it here. And it doesn't show the title!! 🎉

https://cityofaustin.formstack.com/forms/ni_request_day_laborer 

What we need from design is more fleshed out specs in #3008—closing this one since it's a dupe
