### ISSUE TITLE
There is no scrollbar indicator of where you are on a page in Janis

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#3205]
PR: https://github.com/cityofaustin/janis/pull/600
Testing link: https://janis-3205-scrollbars.netlify.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide

Managed to fix this in a way that makes sure the main guide page scrollbar appears but the nav scrollbar is hidden.

Tested in:
Chrome (mac) ✅
Chrome (win10) ✅
Edge (win10) ✅
IE 11? (win10) the whole guide page is kinda struggling there

**Describe the bug**

Check any page in Janis, no scrollbar appears as you scroll up and down the page.

**URL**

for example: https://alpha.austin.gov/en/health-safety/healthcare-prevention

**To Reproduce**

1. Go to any page in Janis
2. Scroll
3. See error

**Current behavior**
There is no scrollbar.

**Expected behavior**
- [x] A scrollbar appears as you scroll. 

**Browser**
Chrome does not have it, unsure behavior in other browsers. 

**Additional context**

`_base.scss` currently contains the following:
```
// Hides the main scrollbar in chrome on windows 10
::-webkit-scrollbar {
  width: 0 !important;
}
```
It appears to hide the scrollbar on chrome in mac as well.

**Comment by briaguya** [comment]
@desigonz want to make sure we have a solid understanding of how scrollbars should behave in different browsers. As per our discussion in https://github.com/cityofaustin/techstack/issues/2937 we wanted to hide scrollbars everywhere apparently, but decided against it because it's a lot of looking for browser specific scrollbar css etc. Is the new plan to just bring back scrollbars everywhere? If not we probably need to resize this one.

**Comment by desigonz** [comment]
Let's bring back scrollbars everywhere.

**Comment by briaguya** [comment]
@desigonz bringing them back everywhere means we have them on our guide TOC (2 scrollbars on the guide page), any chance we have more specific requirements?

**Comment by desigonz** [comment]
@briaguya Looks great! QA done.
