### ISSUE TITLE
Update contacts to reflect style guide's punctuation standards

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3219]
We have established an [editorial style convention for number and time ranges](https://app.gitbook.com/@cityofaustin/s/digital-style-guide/write-with-service-oriented-language/make-content-easier-to-read#time). This means we need to update the auto-generated punctuation in hours within contacts.

**Acceptance criteria**
- [x] For hours in a contact snippet, use an en dash "–" (instead of the hyphen "-" we're currently using) 
![image](https://user-images.githubusercontent.com/5839508/67118432-80d9c300-f1aa-11e9-9da4-9d11861b6eda.png)

**Comment by chiaberry** [comment]
@desigonz  ready for QA

Go here https://janis-3219-en-dash-contacts.netlify.com/en/police-oversight/: to see the hours listed. The dash is a en dash instead of a hyphen. En dashes are slightly longer than hyphens but shorter than em dashes. You can highlight the punctuation and google search it to confirm its an en dash.

**Comment by chiaberry** [comment]
@desigonz  *now* it is ready for QA. 

https://joplin-pr-3163-guide-pages.herokuapp.com/ here is a connected joplin if you want to add contacts, change something. 

Go here https://janis-3219-en-dash-contacts.netlify.com/en/police-oversight/: to see the hours listed. The dash is a en dash instead of a hyphen. En dashes are slightly longer than hyphens but shorter than em dashes. You can highlight the punctuation and google search it to confirm its an en dash.

I changed the time on the linked joplin to have monday start at '12pm' to test that it comes across as noon instead of 12pm. I also updated the spacing, it should be '5 pm' not '5pm'

**Comment by chiaberry** [comment]
@ablangworthy27 if you wanna take a peek too, here it is

**Comment by desigonz** [comment]
@chiaberry Looks great! QA passed
