### ISSUE TITLE
Timezone for janis previews dosen't match rest of site

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3230]
PR: https://github.com/cityofaustin/janis/pull/596

Testing notes: See that [preview](https://janis-3230-contact-hours.netlify.com/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMTQ0?CMS_API=https://joplin-pr-brians-janis-testing.herokuapp.com/api/graphql) and [live](https://janis-3230-contact-hours.netlify.com/en/police-oversight/how-we-store-and-use-your-data/) contact hours look the same.

Hours on Janis previews reflect a GMT timezone, not Central. 

Hey! This would probably be a really simple thing to have a unit test for.

**Comment by Niicck** [comment]
Unless the missing :30 mark is due to my logic here:
```
  formatTime(time) {
    let style;
    // Only include minutes in display if there are minutes
    if (moment(time).minutes()) {
      style = "h:mma";
    } else {
      style = "ha";
    }
    
    return moment.utc(time).format(style);
  }
```

**Comment by briaguya** [comment]
on the joplin side of things, we're already getting the same times for preview and live. This needs to be fixed in Janis.

https://joplin-pr-brians-janis-testing.herokuapp.com/api/graphiql#query=%7B%0A%20%20pageRevision(id%3A%20%22UGFnZVJldmlzaW9uTm9kZToyMTMz%22)%20%7B%0A%20%20%20%20asInformationPage%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%20%20contacts%20%7B%0A%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20contact%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20hours%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20startTime%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20endTime%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20allInformationPages(id%3A%22SW5mb3JtYXRpb25QYWdlTm9kZToyOA%3D%3D%22)%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20contacts%20%7B%0A%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20contact%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hours%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20startTime%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20endTime%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=null&operationName=undefined

**Comment by desigonz** [comment]
QA done!
