### ISSUE TITLE
Requirements for "hours" Joplin interactions

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3235]
As an author I want to be able to accurately reflect open times for a physical location.

- [ ] Discontinuous multiple hours per day (9am-12:00pm, 1pm - 5pm)
- [ ] holidays
- [ ] Special hours (ie, closing early on a particular day, like New Year's Eve)
- [ ] unplanned closings due to emergencies or other one-offs
- [ ] special event hours

**Comment by desigonz** [comment]
Surfacing this one post today's dev-design sync. We'll need to develop requirements for the refactored hour interactions in Joplin.

**Comment by desigonz** [comment]
- [ ] @desigonz to compile requirements
- [ ] @toribr to research what else is out there
- [ ] discuss in design pin-up

**Comment by desigonz** [comment]
Post-MVP: a way to share or copy hours. Ex. WIC hours are somewhat consistent.

**Comment by desigonz** [comment]
## Requirements for MVP
- [ ] Authors are able to select time using 12 hour clock in Central Time zone
- [ ] Authors can select discontinuous hours within the same day. 
  - Ex. 9am – 12pm, 1pm – 5pm
  - [ ] **Design:** Need requirements for how this displays on the Janis side of things
- [ ] Authors can indicate monthly/bimonthly extra opening hours or closures
  - Ex. 1st and 3rd Saturday of the month: 8am – 12pm
  - Ex. Closed 2nd Wednesday of each month
  - [ ] **Design:** Need requirements for how this displays on the Janis side of things
- [ ] Authors can indicate that a service/department/location is closed on all City of Austin holidays
  - [ ] **Design:** Need requirements for how this displays on the Janis side of things. (For MVP, could display with hours: "Closed on all [City of Austin holidays](/x)" with a link to a page with closures. When we get to designing calendar of events, could also sync with that)
  - [ ] **Design:** What would this look like on the author side of things? A simple checkbox "closed on City holidays" could be nice!
- [ ] **Maybe**: Ability to add string text for special holiday hours or closures that don't have a pattern. We could potentially use this for unplanned closings due to emergencies or other one-offs.
  - Ex. Closing at 2pm on New Years Eve (for a place that might close at 5 regularly) 
  - [ ] **Design and content:** Need requirements for how this displays on the Janis and Joplin side of things. What does this look like to a resident? What guidance do we provide on 
## Post-MVP
- [ ] Seasonal hours—ability to indicate sets of hours for certain date ranges
  - ex. [Barton Springs winter vs. summer hours](http://www.austintexas.gov/department/barton-springs-pool)
- [ ] Ability to copy or share hours (to make it easier when entering a lot of locations with same/similar hour patterns

**Comment by desigonz** [comment]
I consolidated this into #3400, we'll continue the conversation there!
