### ISSUE TITLE
Error handling for feedback module

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3240]
- [x] When submitting fails, copy should say: "Sorry, we had trouble receiving your feedback. Please try again or email feedback@austintexas.gov."
- [ ] see design below

**Comment by chasechenevert** [comment]
Added a section for the error message state near the bottom: https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/

Since this form only has a system error messages (no user error messages) it didn't feel appropriate to use the pattern we use in forms where the input borders to red, help text, and fieldset area are all changed to various shades of red. I'll probably want to fine tune this at some point down the line, so if we can easily change the styling (background color, text color, borders, etc.) that'd be great.

- [ ] Implementation matches mocks
- [ ] border-top: 1px solid #DBDBDB;
- [ ] Icon: `error_outline` in the Material icon set, color: `#D63E04`

**Comment by chiaberry** [comment]
deployed link to QA: https://janis-3240-feedback-error.netlify.com/

Every time you submit feedback, it will error.

**Comment by desigonz** [comment]
QA passed!
