### ISSUE TITLE
Top links for existing topics

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3259]
In #3188, we're making it so that a Joplin user needs to assign pages as "top links" for a topic in order to appear on the card on a parent topic collection page. A topic can have up to four topic collections. 

@briaguya will take care of adding the top links within Joplin, but let's make decisions about which should be the top links. 

For each of the following topics, choose at least one and up to four pages as a top link.

**[Household waste](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste)**
1. (required)
2. (optional)
3. (optional)
4. (optional)

**[Compost and food waste](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/compost-food-waste)**
1. (required)
2. (optional)
3. (optional)
4. (optional)

**[Recycling and reuse](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/recycling-reuse)**
1. (required)
2. (optional)
3. (optional)
4. (optional)

**[Birth and death certificates](https://alpha.austin.gov/en/health-safety/health-records-certificates-2/birth-death-certificates)**
1. (required) Get a birth or death certificate
2. (optional)
3. (optional)
4. (optional)

**[Disease prevention](https://alpha.austin.gov/en/health-safety/healthcare-prevention/disease-prevention/find-free-condoms)**
1. (required) 
2. (optional)
3. (optional)
4. (optional)

**[Police oversight](https://alpha.austin.gov/en/health-safety/police-oversight-2/police-feedback-and-records)**
1. (required) File a complaint about an Austin police officer
2. (optional) Thank an Austin police officer
3. (optional) Official complaint and discipline documents

**Comment by ablangworthy27** [comment]
I looked through these links, and it turns out this decision is pretty simple because none of the topics have more than 4 links. I think for now, we should just include all of them. There will be a point where further discussion is necessary but not yet. 

Household waste
(required) Look up your trash, recycling, and compost pickup days
(optional) Get ready for curbside compost
(optional) Get your bulk items collected
(optional) Drop off household hazardous waste and other recyclables

Compost and food waste
(required)Get ready for curbside compost
(optional)Set out your leaves, grass, and branches for pickup
(optional)
(optional)

Recycling and reuse
(required) Look up your trash, recycling, and compost pickup days
(optional) Pick up free paint and other household items
(optional)
(optional)

Birth and death certificates
(required) Get a birth or death certificate
(optional)
(optional)
(optional)

Disease prevention
(required) Get immunizations for you and your family
(optional) Find free condoms and learn other ways to prevent HIV
(optional) Measles in Austin
(optional)

Police oversight
(required) File a complaint about an Austin police officer
(optional) Thank an Austin police officer
(optional) Official complaint and discipline documents

**Comment by desigonz** [comment]
great, thanks @ablangworthy27! I dropped a link to your list in @briaguya's issue. Closing this.
