### ISSUE TITLE
Location page -  MVP models/author interface

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3295]
- Make a location page content type (joplin design links?)
 - Make a service_location_hours content type with:
   - Hours (model reqs TBD)
   - Additional information (use side door etc.)
   - location as parentalkey (see topic page top pages for example)
   - page as ForeignKey (see topic pages top pages for example) - only allow choosing service/dept
 - Do all hours editing from location pages (select services/depts)
 - Remove location information from contacts

## Joplin: location page (sprint 44)
- [ ] Location content type matches mocks

Mock: https://xd.adobe.com/spec/d3fea86b-184d-4652-48b2-48ce78dcb3ae-a5cf/

**Comment by toribr** [comment]
@briaguya Don't know where you want to put this, but additionally "locations" will need to be removed from the left hand nav. (Eventually also "map" once we get locations sorted, too, because it'll be redundant.)

**Comment by desigonz** [comment]
- [ ] By end of sprint 44, an author can add all of their location data. 
- [ ] Hours MVP will be the same as now, with a plain text box to add irregular hours as a string.

**Comment by easherma** [comment]
MVP spec for Janis: 
https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/

**Comment by desigonz** [comment]
New MVP spec for Joplin: https://xd.adobe.com/spec/d3fea86b-184d-4652-48b2-48ce78dcb3ae-a5cf/

**Comment by easherma** [comment]
@toribr to clarify, the hours in the mock appear to be hours that would already be related to the related service page? so we are not adding hours for the location directly/separate from already predefined hours for a service?

**Comment by desigonz** [comment]
@easherma  Ahh I think that's an oversight on the mock—@toribr, can you confirm? We should have some sort of "standard" facility hours, per the Janis mocks, PLUS the service-specific hours.

**Comment by toribr** [comment]
We do need hours per location as well - But since hours are currently embedded in contacts, and we are still exploring how hours get assigned to services, then my assumption is that this same widget would get implemented for both cases. It's still a bit TBD what that widget is, and how it works. From a user standpoint I think using a modal to contain that functionality would allow the clearest flow, otherwise we are stuck with creating an Hours snippet, where a user must go create the hours, and then assign the hours to the location. We should discuss which method we can implement first as it may influence the design.

**Comment by easherma** [comment]
I agree that hours is probably a bigger issue overall. 

There are a few main routes I see:
* based on this mock, I can explore how hard it is to get existing data from a related page to display on this page. Or, in this case, if we have related page selected, can we also display snippets related to this page and display specific fields of that data with a link to edit them. I don't think this is impossible, and wouldn't be a bad thing for us to learn how to do. 
* we can also implement new hours fields directly on on the location page, leaving hours in place for contacts for now, which keeps it backwards compatible with whats already being used. This would easily make those fields part of the page model, so no need to click around or create stuff separately. 
* just add the existing contact snippet chooser to location pages as well (use the same, existing contact snippet)

Looking _just_ at the joplin mock, my instinct would be to go down the first route first. 
However, if I check the janis mock, and therefore what @Niicck will need for the frontend, then I'd prioritize having hours for location page.

Of course, we could just use the pre-existing contact snippet for location page the same way we do for service page. I'm not sure what the downside is there, other than that we don't like the UX flow and all the steps it takes to add something vs create inline.

**Comment by toribr** [comment]
@easherma @desigonz 

I've updated the current mocks to show the functionality that hours (for location and services) should include. I did this fairly quickly, so the UI itself is not necessarily final, but I think these mocks pretty clearly show where we need to go eventually, and allow for the edge cases that we'll need to accommodate. Not every detail is worked out (ie, where "holiday" hours are set) but I think we'll be able to have a better conversation about how to get here if we all know where we're going. :)

https://xd.adobe.com/view/751c15ab-a5c9-4ec5-57e9-add1f71e332f-032d/

**Comment by easherma** [comment]
@toribr @desigonz 
Given that potential new hours stuff is being fleshed out, and the implementation of that would be pretty complicated, I split the difference at least for now:
* I made the Day & Time selections be in a row so they take up less vertical space/are easier to scan
* I added an 'Exceptions' textbox similar to the first version of the mocks, so for MVP we have a way of collecting those exceptions and displaying them in Janis

I made these changes to the Contact snippet as well, and re-used the same days and hours component for each: 
On a location page:
https://joplin-pr-3296-location-mvp-mv.herokuapp.com/admin/pages/266/edit/#tab-content
On a contact snippet
https://joplin-pr-3296-location-mvp-mv.herokuapp.com/admin/snippets/base/contact/1/

![exceptions](https://user-images.githubusercontent.com/10539855/69378576-4618ee00-0c74-11ea-9831-839018eaf099.png)

Open to any thoughts/feedback!

**Comment by desigonz** [comment]
Hi y'all! I'm finally catching up on this thread, sorry about the delay.

@easherma, great work on this! The location hours for MVP look good to me. For this issue, sounds like we're getting close to MVP—aka "can authors enter in all of the data they need for the location content type MVP?". Anything else, like the improvements (switching from 24 hour to 12 hour and tightening up the space), we can make issues for next sprint. 

The one thing that's missing is entering service hours. Based on research and dev-design syncs in the past, we've determined that an author needs to be able to enter service hours on a per-location basis, because service hours might differ from location to location. @toribr, in your comments above, it sounds like you're suggesting:
- [ ] When a user adds a related service to a location page, they then have the ability to edit the hours for that particular service by clicking something like an "edit page" button
- [ ] Clicking "edit page" opens a modal that allows a user to set the hours 
  - This modal can use the same hours UX pattern that we're currently using
Does that sound right?

**Comment by toribr** [comment]
![Locations](https://user-images.githubusercontent.com/3790067/69553221-6f33ca00-0f65-11ea-8b5f-c5c18bc2f01c.png)

Not really. 
We do want to add hours per service, and the users should be able to add hours by clicking a button "Edit hours", which should open a modal.

Given that the modal has to be created for this to work, then the "location" hours should be removed from the page (which is terribly cumbersome) and embedded in the modal as well, so that editing hours works the same way in both instances.
![Screen Shot 2019-11-25 at 9 34 51 AM](https://user-images.githubusercontent.com/3790067/69554079-db62fd80-0f66-11ea-84fe-932a7b019f4f.png)

**Comment by easherma** [comment]
Can be QA'ed here:

https://joplin-pr-3296-location-mvp-mv.herokuapp.com/admin/pages/add/locations/locationpage/3/

**Comment by desigonz** [comment]
Hi Eric—this is looking great. Let's just get these two addressed to get us to MVP, and let's get folks on code review for this.

- [ ] Match the copy on the mocks. (We discussed today that some of the fields have changed—don't worry about matching that copy, we'll do another pass next sprint on that)
- [ ] In both of the address fields, there is a field for "Country"—we don't need that. It will be confusing for authors because that won't appear on Janis anyhow. Can we get rid of that? What size would that be?

**Comment by easherma** [comment]
@desigonz 'country' was just a holdover from the location snippet, I can remove that and take a pass at updating copy by EOD today

**Comment by desigonz** [comment]
Awesome, thank you!

**Comment by desigonz** [comment]
Is this ready for second round QA?

**Comment by desigonz** [comment]
Ready for second round QA (@desigonz). 

@chia will do a second code review, then @easherma to incorporate code review feedback.

**Comment by desigonz** [comment]
Hi @easherma! Thanks for making these changes and apologies for the delay in QA, this slipped from my radar.

Just a few more copy edits, outlined in the images below. If any of these are more than a size 1, let me know and we can discuss.
- [ ] remove all the colons
- [ ] lowercase where specified on the screenshots
- [ ] Add period at the end of "Use this to show the exterior..."
- [ ] For "Location alternate name," can this helper text display like all other helper text, i.e. not hidden under the question mark?

![image](https://user-images.githubusercontent.com/5839508/70191899-dcf79880-16bf-11ea-9537-ee5d0d2ec60e.png)
![image](https://user-images.githubusercontent.com/5839508/70191943-f993d080-16bf-11ea-918e-75a803a17d15.png)
![image](https://user-images.githubusercontent.com/5839508/70192064-352e9a80-16c0-11ea-9cf4-8ca7c0a3abb4.png)
![image](https://user-images.githubusercontent.com/5839508/70192158-7fb01700-16c0-11ea-8a2f-c2828c8cc996.png)

**Comment by easherma** [comment]
I'm trying to see if we've run into this colon problem before; but it might be a bit more intractable to solve:
https://github.com/wagtail/wagtail/issues/130

**Comment by desigonz** [comment]
Sigh. Okay let's keep the colons but maybe make the case to the Wagtail folks about it.

**Comment by desigonz** [comment]
Looking good. Can you add a period at the end of `Use this field if the building has a second name, or is inside a larger facility` and then lowercase "hours" in `Location hours` and then it's good to go!

![image](https://user-images.githubusercontent.com/5839508/70267543-47faab00-1764-11ea-8944-498394857c2b.png)
![image](https://user-images.githubusercontent.com/5839508/70267548-4b8e3200-1764-11ea-9cf9-49bfc784aa85.png)

**Comment by desigonz** [comment]
Actually why is pages in the left? Want to make sure that doesn't get merges.

![image](https://user-images.githubusercontent.com/5839508/70268009-32d24c00-1765-11ea-819a-a015a4b6400d.png)

**Comment by desigonz** [comment]
@easherma Per our conversation, let's:
- [ ] Hide the `Pages >` in the left nav
- [ ] Hide the filter `Locations index page`

and then let's merge!

**Comment by desigonz** [comment]
Looking good for the `Pages >`

Still have a small `(1)` in the page types filter
![image](https://user-images.githubusercontent.com/5839508/70278492-ffe68300-1779-11ea-934f-25522c9bbfd0.png)
That's because there was a locations index page that Eric created for testing purposes on the branch, won't be there on staging or prod. We'll verify it isn't there on staging.

**Comment by desigonz** [comment]
Looks great in staging! QA done
