### ISSUE TITLE
Better build logs

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3298]
### As someone doing QA, I want to know when a PR app build is done, so that I can know that I can keep QAing.

**Is your feature request related to a problem? Please describe.**
Might become less relevant one we're at incremental builds, but it would be nice!

**Describe the solution you'd like**
Some log I can check to know when my build is done.

**Describe alternatives you've considered**
not sure

**Additional context**
none

**Comment by easherma** [comment]
This probably will require reaching out to Netlify support, their integration isn't acting the way we expect, and it may have to do with the fact that we build a new site every time instead of opening a branch build. 

We can also set up a Slack webhook for notifications.

It would also be great to use Github webhooks to update relevant issues or PRs with the build url.

**Comment by desigonz** [comment]
from @easherma in #3357

> Including: 
> 
> * Easier to parse logs/slack notification
> * Better parsing/explanation of GraphQL errors and other Janis build stuff.

**Comment by Niicck** [comment]
We're going to loop this into post-mvp publisher UX.
