### ISSUE TITLE
Review place page content type microcopy

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3332]
Let's review the microcopy in the new place content type! 
https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/64aa180d-e5d8-470f-a53b-9fc814a37d57/Option-1-tablet-icons-and-labels

**Comment by desigonz** [comment]
We should probably work together with @chasechenevert to determine what's MVP copy, and which copy is hard-coded in Janis (vs. manageable in Joplin)

**Comment by ablangworthy27** [comment]
One thing that I noticed, that I have brought up recently in another issue, is punctuation in microcopy. For example, The 1st slide shows no punctuation in the Language Access section. BUT the 5th slide's identification section does have punctuation. We just need to make a decision. (@srigdon @Jo-Dwyer)
![Screen Shot 2019-11-01 at 9 23 40 AM](https://user-images.githubusercontent.com/29933958/68031657-18024880-fc8a-11e9-8ec1-104482297f7f.png)

![Screen Shot 2019-11-01 at 9 22 58 AM](https://user-images.githubusercontent.com/29933958/68031555-eb4e3100-fc89-11e9-9f25-006ac93876cb.png)

**In the meantime, I'd like to swap out:**
This location accepts appointments only. To make an appointment call 512-000-000
**with**
This location does not accept walk-ins. To make an appointment call (512) 000-000

**Please change the punctuation of this sentence:**
Some services  are offered at specific times, please check the times of the services you'd like to receive
**so it looks like**
Some services  are offered at specific times. Please check the times of the services you'd like to receive

**Getting here** 
Shouldn't the elevator just be under "moving around the space"?




**I also have a few notes about conventions that are now in style guide.**

### **Time**
This mock isn't currently following the conventions we have for time. 
_Always use numerals for time. Do not include “:00” for times on the hour. Lowercase “am” and “pm” and do not use periods. There is always a space between the numeral and “am” or “pm.” To indicate a time range, always use the en dash with no spacing instead of "to." Use “noon” instead of “12 pm.” 

**Do:**
9 am–5 pm
9:30 pm
Noon
**Avoid:**
9:00 a.m. – 5:00 p.m.
9 am – 5pm
9 am to 5pm
9:30 P.M.
12 p.m._

### Phone numbers

One of the phone numbers on the mock is correct, but the other is not.

**Do:** “Call the Help Desk at (512) 974-4357.”
**Avoid:** Letters for words, like “To call the Help Desk, call (512) 974-HELP.”

### Addresses
When writing addresses, spell out street names. However, abbreviate states when spelling out a full address.

**Do**
5100 North Lamar Boulevard
1520 Rutherford Lane
Austin, TX 78754
**Avoid**
5100 N. Lamar Blvd.
1520 Rutherford Ln
Austin, Texas 78754

**Comment by Jo-Dwyer** [comment]
I say that shouldn't have a period since is a header. It may be clearer to change from a postpositive adjective to a prepositive, unless the intention is that it should be read as a sentence. 

Ex.

"Identification required for services"
Becomes 
"Required identification for services"

Or as a complete clause:

"Identification is required for services"

**Comment by ablangworthy27** [comment]
I just updated my recommendations in the original comment

**Comment by desigonz** [comment]
@ablangworthy27 Some additional microcopy questions for you:
![image](https://user-images.githubusercontent.com/5839508/68344809-99584180-00b5-11ea-9f23-97a5981337e5.png)

1. How should the addresses display—on two lines, or on one?
2. Thoughts on the headings "Facility hours" and "Standard hours"? Do we need both? 
3. In hours, colons after days of the week? 

![image](https://user-images.githubusercontent.com/5839508/68344898-bb51c400-00b5-11ea-9066-6560a83cf270.png)
4. "Services offered"—does this heading look good?
5. "See more hours" and "Close hours"—do those look good?
6. "Service information" label—thoughts?
7. All of the copy in "Accessibility features"—please approve or change 'em
![image](https://user-images.githubusercontent.com/5839508/68345064-197ea700-00b6-11ea-8e41-16e7feb5adda.png)

**Comment by ablangworthy27** [comment]
1. How should the addresses display—on two lines, or on one?
_two lines_

2. Thoughts on the headings "Facility hours" and "Standard hours"? Do we need both?
_The only reason that I would see for keeping standard hours would be if there were cases with non-standard hours, like maybe on holidays or during special events. I think keeping standard does communicate that there might be discrepancies in unusual circumstances. _

3. In hours, colons after days of the week?
_Let's remove these. We don't have a standard set for this yet in the guide, but I looked at google and other places that list hours and I think it looks better without._

4. "Services offered"—does this heading look good?
_Yes, looks good._

5. "See more hours" and "Close hours"—do those look good?
_See more hours is fine, but i think we should use "Hide hours" instead of "Close hours"_

6. "Service information" label—thoughts?
_I think this is good._ 

7. All of the copy in "Accessibility features"—please approve or change 'em

_-I brought it up with the other content folks and we have decided to remove the header "Accessibility Features". I think there is a chunk of people who will know what that means and will be looking for those features. However, I also think there are people who might be looking for those features but not understand the heading. Additionally, we'd like to start normalizing these features and removing the "Accessibility" term might help with that._

_We're not totally sure what to change it to and might need to suggest some research.  For MVP, we'd like to suggest replacing "Accessibility Features" with "Getting to and around the space"_

_-I can only see the "Getting Here" section, but I know there are others. Because we need to change the header above it, we'd like to change the titles of each feature to be more informational than actionable. For "Getting Here" we'll go with "Travel"_

_-"Buses servicing this area" is good_

**Comment by desigonz** [comment]
Thanks @ablangworthy27! @chasechenevert, assigning you to incorporate the copy changes outlined [here](https://github.com/cityofaustin/techstack/issues/3332#issuecomment-548809340) and [here](https://github.com/cityofaustin/techstack/issues/3332#issuecomment-551190425) in the places mock. Thank you!

**Comment by desigonz** [comment]
- [ ] Remove hyphen in "E-mail address" (should read "Email address")

**Comment by chasechenevert** [comment]
Pretty sure I got everything, but there's a lot so just let me know if anything's incorrect or missing.

Places MVP spec: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/
