### ISSUE TITLE
Location content type in create content modal

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3417]
We're going to have a new content type! #3400 

We need:
- [ ] Icon for what it looks like in the create content modal
- [ ] All the relevant copy

![image](https://user-images.githubusercontent.com/5839508/68876290-d5992c80-06c9-11ea-9c3b-ed55b8197e6c.png)

**Comment by ablangworthy27** [comment]
Hi @toribr, here is the microcopy:

**Title:** Location Page
**Description:** Provides service, travel, and contact details for a location

**Comment by toribr** [comment]
@ablangworthy27 Thanks!
Can you edit this second part, please and thank you?

![create_location](https://user-images.githubusercontent.com/3790067/69163005-1ec6f300-0ab3-11ea-8a1a-3ba07c249f09.png)

**Comment by ablangworthy27** [comment]
@toribr This looks great. My only note is that in other content types, the third bullet is slightly different. It looks like this:

_You don’t need to worry about including your department’s name in the title._

I actually think your version is better and clearer. How do you feel about changing the other content types that have this bullet about department names to match?

**Comment by toribr** [comment]
Resolved: 

https://xd.adobe.com/spec/d3fea86b-184d-4652-48b2-48ce78dcb3ae-a5cf/

**Comment by desigonz** [comment]
Added this to the acceptance criteria for #3295 (cc @easherma). Closing this issue!

**Comment by ablangworthy27** [comment]
@desigonz @toribr as discussed during content pin-up, we do need to revisit this microcopy at some point because there are departments that will be locations (which would actually make the last bullet either unnecessary or totally different with more context)

Also, I am making a new issue to change the copy for the bullet about not needing department names for the other content types to reflect the copy in this example because it is a bit more clear.

**Comment by desigonz** [comment]
@ablangworthy27 For any changes to the location content type in the create content modal, please add as a comment in XD and ping @toribr about it. And thanks for the new issue!
