### ISSUE TITLE
Wheelchair accessibility in location content type

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3421]
Mocks for Janis and Joplin sides

**Comment by desigonz** [comment]
Is this issue ready to go to dev?

**Comment by chasechenevert** [comment]
## Notes from design pin-up: 
For MVP we're thinking of a simple input to indicate basic wheelchair access, but long-term we know that residents need a lot more detail to determine whether a location is truly accessible based on the resident's condition.

- **Should we display a message on the front end if a location isn't wheelchair accessible?** 
We think it should so that it's unambiguous to the resident whether they'll be able to access the building, but we know that we'll need to expand on what it _means_ to be accessible. Can a resident using a wheelchair independently get into the building (opening doors), or would they need to call ahead for assistance?
- **How might we expand the definition and criteria for accessibility features?** 
We're going to reach out to David to understand more about ADA compliance in the city.
- **How might we help departments evaluate their physical accessibility features**
This might be a good project for SDL since there doesn't seem to be a lot of structure or guidance for how city staff might determine whether their buildings are accessible, and how to go beyond general information such as "this location is wheelchair accessible" that might not be very helpful for residents (for example, measuring door frame widths, wheelchair ramp height, taking pictures of these features, etc.). 

Beyond physical access, we want to expand across other accessibility features:
- Language access: translation services available on-site, or can be arranged upon request, braille
- Mobility access: ramps, elevators, handicap parking spaces
- Transportation access: accessible by city bus routes, bike, scooter, sidewalk, transit centers, bus stops, rail stops

**Joplin side**
- We discussed other input patterns if we always want to display a message on Janis (yes/no this location is wheelchair accessible).

**Janis side**
- This information will live under a new H2 in the "Getting here" block. 
- We also have a question for team content about reintroducing the label "Accessibility features", as we think the keyword "Accessibility" is important for residents, and SEO.

## Resources
- **Accessibility icons** 
https://graphicartistsguild.org/downloadable-disability-access-symbols/
- **Wheelmap**
https://wheelmap.org/

**Comment by chasechenevert** [comment]
**Wheelchair access**
Per our discussion about wheelchair access during pin-up it seems like wheelchair access isn’t really a single yes/no, but a multitude of accessibility features/criteria that must be in place to be able to define a location as “wheelchair accessible”:
- **Door types and frame widths** at least 36 inches wide
- **Wide hallways** at east 36 inches wide
- **Step-free path to entrance** and no stairs are required to enter
- **Ramps** that are at least 4.8 degrees slope, or one foot of wheelchair ramp for each inch of rise, minimum of 36 inches of clear space across the ramp
- **Ramp handrails** between 34 and 38 inches in height on both sides 
- **Elevators** door frame width at least 36 inches wide, and elevator car depth that’s at least 52 inches deep
- **Disabled parking**

I’m referencing a lot of different sites to find this, but it’s pretty much all here: https://www.access-board.gov/guidelines-and-standards/buildings-and-sites/about-the-ada-standards/ada-standards/doj-s-2010-ada-standards

Thoughts about breaking this out by individual criteria? It would look like the sketches shared awhile ago of the future state of the “Accessibility features” block.

**Comment by toribr** [comment]
Relevant snippet:
![Screen Shot 2019-12-09 at 10 32 48 AM](https://user-images.githubusercontent.com/3790067/70453996-57813900-1a6f-11ea-9faf-dc946f617222.png)

Dev link (hour implementation is different): https://xd.adobe.com/view/751c15ab-a5c9-4ec5-57e9-add1f71e332f-032d/

**Comment by chasechenevert** [comment]
https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/337903d1-685c-4b92-99d9-ac2d0af115b5/Artboard-2/

**Comment by chasechenevert** [comment]
I think we might've closed this out before giving @desigonz a heads-up. 

Updated the Location spec to include the wheelchair accessibility side for Janis. You can click on the block in any view to see the redlines. 

https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/

**Comment by desigonz** [comment]
Hi team! Sorry for being so slow on reviewing this issue. A few questions/outstanding things:
1. We need microcopy for the Janis side of things for when a location is wheelchair accessible; @ablangworthy27, can you offer a suggestion?
2. We also need Janis mocks with microcopy for what the interface looks like when an author selects "No, this building is not wheelchair accessible" in Joplin. @chasechenevert, can you make a mock, and @ablangworthy27, can you author some copy?
3. @toribr, re: your question about requiring this field, I'm inclined to not require it right now, because then we always either have to show that a site is wheelchair accessible or not, with no ability to leave room for gray areas; seems like a bigger policy hole we might end up falling into.

**Comment by ablangworthy27** [comment]
Is this going to be a checkbox? I'm inclined to also include room for authors to add a small amount of custom microcopy that provides any details (elevators, which side of the building to enter for a ramp, who to call for assistance, etc...)

It would also be great if there was a prompt to guide authors to include these types of details.

**Comment by toribr** [comment]
@desigonz What do you think about adding a text field for these details? MVP or not?

**Comment by desigonz** [comment]
Adding a text field should be easy from a dev standpoint. I think the bigger question is whether y'all feel ready for the kind of content governance this will entail.

**Comment by toribr** [comment]
@desigonz @ablangworthy27 If content decides to proceed then I'll need instructional text for this text field, ie, "Add any notes that may be relevant to accessing this building like directions to an elevator, ramps, or other handicap affordances."

**Comment by desigonz** [comment]
@ablangworthy27 and I talked it over via Slack, and we're going to try out the text field and see how it works.

- [ ] @ablangworthy27 to share instructional text microcopy

**Comment by toribr** [comment]
@chasechenevert Take note of Janis implications of above!

**Comment by ablangworthy27** [comment]
**Accessibility instructional text**
**Checkbox:** This location is wheelchair accessible
**- Text box microcopy:** Provide fact-checked details about wheelchair accessibility, including the location of ramps and elevators or contact info for residents seeking access assistance.

**Janis Microcopy** (let's keep it simple)
This location is wheelchair accessible 
-with optional details provided by author below.

This location is not wheelchair accessible.

**Comment by toribr** [comment]
@ablangworthy27 We had previously discussed make this optional, and using a radio button with this copy:
Yes, this location is wheelchair accessible 
No, this location is not wheelchair accessible

At the moment I can't remember why @desigonz preferred the "no" option... so I'll let her pipe in.
I'll assume that the no copy (provided we still want yes/no) would read as above. (When using two options, I recommend retaining the Yes/No keyword start, as it makes it easier to grok.)

**Comment by ablangworthy27** [comment]
@toribr Understood. I am on board with the radio buttons, plus the optional option to add details.

**Comment by toribr** [comment]
Looks like this:
![Screen Shot 2020-01-02 at 2 38 09 PM](https://user-images.githubusercontent.com/3790067/71691641-88524680-2d6d-11ea-99d2-3f3b90762a39.png)

**Comment by desigonz** [comment]
Thanks team, I appreciate it!

- [ ] @chasechenevert to add the Janis microcopy for yes/no wheelchair accessibility to the Janis mocks.

**Comment by chasechenevert** [comment]
Changes posted. 
<img width="816" alt="Screen Shot 2020-01-05 at 12 10 06 PM" src="https://user-images.githubusercontent.com/7027270/71784034-57b01e00-2fb4-11ea-8873-9152f362ed8a.png">

**Comment by desigonz** [comment]
#3785 is the implementation issue, closing this
