### ISSUE TITLE
Adjust language in pool drafts

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#3450]
I have done [some research](https://docs.google.com/document/d/1kcMnxo-4X93mZwVHl_ICiL00aTmwLWzNW_xzVYT_AYE/edit) into how other cities and states are referring to pools. Currently Austin uses pools, spas, public interactive water features & fountains and the acronym PWIFF specifically for public interactive water features and fountains. This is way too long and complicated and I would like to shorten  it. To accomplish that, the following needs to happen:

1.  - [ ] Decide on the best alternative. Options I am currently considering are in the research doc.
2.  - [ ] Get this approved with APH.
3. - [ ] Go through all the guide content and replace as necessary
4. - [ ] Add to learn and prepare pages (for example, the definitions page), so that users have a solid understanding of everything that the guide encompasses. We want them to understand that when we say "pools" we also mean splash pads. 

Not sure yet if it would be best to do #3 and #4 first and then see what APH says or if it is better to talk it through ahead of time. @desigonz @srigdon @Jo-Dwyer @annieszot  what do you think? Looping you all in for your opinions because you have worked with the department or on guides.

**Comment by desigonz** [comment]
Interesting! Is "Pools, spas, and fountains" another possibility? (Still too long?)

More data, though not terribly useful because we don't have a lot of it: CPIO recently set up austintexas.gov analytics to capture site search data. So for users who used to CoA search to land on the pools and spas page, here are the terms they used:
![image](https://user-images.githubusercontent.com/5839508/69280160-616bf680-0bab-11ea-96c5-2d5211a9459e.png)

I have a feeling getting approval to change the way they've been working could be difficult...if that's the case, we could share the data you've found and propose conducting user research to understand what makes most sense to your target audience.

**Comment by annieszot** [comment]
@ablangworthy27 I recommend talking it through with Austin Public Health ahead of time since that can save you time even if you need to go back and rewrite your drafts. They'll appreciate you wanting clarification and showing you're putting effort towards understanding. 

You may get pushback from public health on synonymizing pools and splash pads. They are not the same thing, and public health officers see splash pads as insufficient to provide the recommended daily amounts of exercise.
