### ISSUE TITLE
Review pagination implementation

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3502]
- How should we handle width of pagination when there aren't enough pages to match that width of the document(Currently, It's left aligned) .
  - *See Image below

- How should we handle mobile implementation going forward? I don't think there's a clear answer. Maybe after playing with it a bit we can figure something out. 

![Screen Shot 2019-11-26 at 6.47.13 PM.png](https://images.zenhubusercontent.com/5d6e8e8463924520788459ad/7414eddc-f8c2-49ee-b862-f631bdfc0d20)

**Comment by robbobfrh84** [comment]
- It would also be nice for "Pagination" to be an abstract component.
- And, test it with a different pagination content. 
- Also, the structure of the files and naming conventions could be re-thought.

**Comment by chasechenevert** [comment]
This looks great, and I'm happy to see it in action already!

- [ ] Let's center the component, and allow it to expand up to the width of the body content which is `.col-md-8` and has `flex-basis: 66.66667%` `max-width: 66.66667%` (in the event that there are a lot of pages)

Re: truncation I'm seeing the truncation sometimes but not always, and I'm not sure if that's due to a bug, the threshold we've set, or something else. Could we connect about this when we're both in the office together?

**Comment by desigonz** [comment]
- [ ] @chasechenevert and @robbobfrh84 to pair up and look at truncation together.

**Comment by chasechenevert** [comment]
We think we've got a viable solution! The biggest issue here were small phone sizes and not being able to fit an ellipsis on both sides of the current page view. We think we can shift the back and forward buttons to above and below the row of numbers so that we can fit 7 in a row on the smallest phone size we have available (iPhone 5s). Will spec this out today.

**Comment by desigonz** [comment]
Thanks @chasechenevert! Where are we on this spec?

**Comment by chasechenevert** [comment]
The spec: https://xd.adobe.com/spec/aed4d8fc-6ddb-4576-65e2-4125fdb42e8a-d8e5/ was updated before the break started and after dev/design sync. we talked through the issue with the team, but I neglected to post the notes here. 

- [ ] selected state #0049C7
- [ ] hover #D9E8F6
- [ ] remove spacing between items to fit more on mobile
- [ ] ellipsis shouldn't function as a button, so they shouldn't have a border, hover, or selected state
- [ ] the interactive example in the spec shows where the ellipsis should fall and when

**Comment by desigonz** [comment]
I added these to various issues in the epic #3584
