### ISSUE TITLE
Add supporting example to the Style Guide on department- and division-oriented language

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#3565]
In her mobile food vendor guide edits, Annie made a good point about whether to capitalize or lower case the EHSD division name with the rationale to reduce dept-oriented language wherever possible. I totally agree with this, and I'd add a sentence or two to the style guide to expand on this because it's a common situation: as an author, I have to talk about the division or department because that's who/what the resident has to interact with to access the service or learn the key information. A good rule might be: if part of the action a resident has to do is call, email, go to, or otherwise interact with a department or division, use the name (and initially capitalize is the style to use here, it's a proper noun). If it's not necessary to use the name, rewrite it to focus on the action required or other key information, not the dept. or division.

**Comment by ablangworthy27** [comment]
Can you give an example of when to avoid it?

**Comment by ablangworthy27** [comment]
Found the comment history in the mobile food guide:

_Talked to Annie just now, and the rationale is great: reduce dept-oriented language wherever possible. I totally agree with this, and I'd add a sentence or two to the style guide to expand on this because it's a common situation: as an author, I have to talk about the division or department because that's who/what the resident has to interact with to access the service or learn the key information. A good rule might be: if part of the action a resident has to do is call, email, go to, or otherwise interact with a department or division, use the name (and initially capitalize is the style to use here, it's a proper noun). If it's not necessary to use the name, rewrite it to focus on the action required or other key information, not the dept. or division._
