### ISSUE TITLE
Multi-page form design

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3572]
For OPO's new commission application (#3531), we're going to make a multi-page form in Formstack (due by mid-January). Let's review the form theming for multi-page forms and make design issues for anything that needs to be considered/developed.

**Comment by desigonz** [comment]
- [ ] @desigonz to share example forms from OPO
- [ ] @toribr's thinking we need to review:
  -  getting a confirmation with responses (questions you were asked and that you answered)
  - next/prev pagination
- [ ] identify anything we want for MVP and post-MVP

**Comment by toribr** [comment]
Suggest this as requirement:
- [ ] Repress feedback form on all form pages as it's pulling focus from task at hand.

**Comment by chasechenevert** [comment]
Reviewed:
https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test 

## Suggestions
Continue button is occasionally cutoff in the iframe, see below:
<img width="1229" alt="Screen Shot 2019-12-16 at 12 49 07 PM" src="https://user-images.githubusercontent.com/7027270/70934226-12c34800-2003-11ea-8ea9-90e0fb8cc41c.png">

Dropdowns don't have any kind of field label, so the user has to open the dropdown to learn what information it's asking for:
<img width="396" alt="Screen Shot 2019-12-16 at 12 49 45 PM" src="https://user-images.githubusercontent.com/7027270/70934477-9c731580-2003-11ea-88bd-746aa93e9aec.png">

The calendar icon could use a label so that it's clear that this is actually a button as opposed to a field label, maybe something like "view calendar"

"Continue" buttons should be styled in the primary styling as opposed to secondary since it's a progressive action (background-color: #0050D8, font-color: #FFF)

**Comment by desigonz** [comment]
Also adding to this list: calendar picker styling
![image](https://user-images.githubusercontent.com/5839508/71681213-b4f86500-2d51-11ea-9e16-7a66e874b5cc.png)

**Comment by desigonz** [comment]
Thanks team for your awesome work on this!

Okay, so for MVP multipage forms, we have the following issues, all logged under epic #3659:
- #3660: Button styling for multi-page forms
- #3631: Form pages - don't show feedback module

I've backlogged everything else in issues #3661.
