### ISSUE TITLE
OPO reports

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3593]
The Office of Police Oversight is about to release two PDF reports (end-of-the-year report, and one on racial profiling) that are super important to them to share with the public. We'd like these to live on the OPO site. On our call, we determined that using the official document content type would be an expedient and more accessible. 

### to do
- [x] Create a new official document page for OPO, with a name like “Police Oversight Reports” (will also need to author a description for the page)
- [ ] Author summaries for those two reports (within the character count of the content type)
- [ ] Get this content approved by Mia.
- [ ] Add this new page to the information architecture and to the OPO department page (maybe make it a top link)
- [ ] Send for translation into Spanish (can be post-MVP)

### Timeline
- Approvals will go through Mia; send content by end of day **Tuesday, December 17**
- We plan to publish the two PDF reports (end-of-the-year and racial profiling) by **Wednesday, December 18**

**Comment by ablangworthy27** [comment]
This issue has changed due to OPO's changing timeline. The following is done:

-[New Page](https://alpha.austin.gov/en/police-oversight/office-of-police-oversight-official-reports/#1) has been created 
-The End of year review has been uploaded with a description
-PDF link has been provided to Mia for the press release

The following is NOT done yet, and awaits a followup request from Mia:

-Uploading Racial profiling analysis 2015-2018 doc 
-Get approval on doc description
-Make the Police oversight reports and recommendations page surfaceable on the site by adding a topic collection
