### ISSUE TITLE
Create <PhoneNumberInput/> component

### ISSUE THREAD

**Issue by juliazbyron** [cityofaustin/techstack#364]
Should accept:
1234567890
123-456-7890
(123)456-7890
(123) 456-7890
123.456.7890

**Comment by mateoclarke** [comment]
@cthibaultatx @toribr, I should've asked this in our design review yesterday but how do we want the phone input to work? 

The optimal thing seems like we would users freedom to input numbers 10 number separated by any variety of punctuation like the ways Julia listed above. Then we try to autoformat it with javascript so they are all consistently in a format like `123-456-7890`. This might be buggy. We would need error messaging on top of that if they have more or less than 10 numbers or if they include letters.

Or we could provide error messaging so that if a user types something out of format, they have good instructions on how to fix it in the format we want.

It seems like Julia preferred the 1st option based on this issue, but wanted to consult with y'all before I work on it in depth.

More info: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel
>  it's quite difficult to provide a one-size-fits-all client-side validation solution for phone numbers.

**Comment by cthibaultatx** [comment]
I also prefer option A @mateoclarke Is it possible? Should we make it v2?
