### ISSUE TITLE
Review location hours display

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3739]
Let's review the design of hours here. 
- alignment of day of week with time when time breaks to two lines
- Is it weird how the hours break onto two lines?

![image](https://user-images.githubusercontent.com/5839508/72273822-ab43ec80-35f0-11ea-8bcc-2c052a3c6e65.png)

**Comment by chasechenevert** [comment]
Spec updated: https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/ 

This may need to be split out into a separate issue, I'm not sure, but I had to consider both things when trying to fix the hours display, and this issue is linked into "hours exceptions". 
 
"hours exceptions" on the location and service card were developed independently, so when I needed to consider the issues with the "hours exceptions" implementation it had a cascade effect, and I needed to be consistent, which ultimately meant moving the hours exception below the hours listing but I think this implementation is better because of it. 

- Hours are now able to run the width of the component, so we don't have two columns
- mobile view: force a line break after the comma to stack these vertically
- I know that I'm showing a very weird time as the example, but that's intentional to consider edge cases where any unit of time (start, stop) might have a total of 8 spaces (ex: 00:00 am)

<img width="923" alt="Screen Shot 2020-01-15 at 3 28 24 PM" src="https://user-images.githubusercontent.com/7027270/72473434-4df49a80-37ac-11ea-89af-47ec0e5afe72.png">

**Comment by desigonz** [comment]
Logged criteria in #3840, closing this
