### ISSUE TITLE
Meet with Animal Center staff to review process page mocks

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/techstack#378]

**Comment by cthibaultatx** [comment]
Met with Lorian and Erin on 5/29/18, gathered feedback on foster process mocks and foster form.

- Want to remove some of the 'Add additional information' elements from foster form
- Want to use Overview page image gallery to market fostering. Because photos of pets ready for foster are often not great they'd prefer to put in good photos that don't have to be managed as closely or often.
- Asked if there is a way to search within foster service?
- Asked what the flow would be for someone who is in the middle of filling out the form to navigate to the foster service/process. Talked about breadcrumbs being a primary path, there's also menu. Are there other paths we haven't considered?
- Asked how someone would print this information if they wanted or needed to and presented scenarios where that's important @courtneyjacinic you've explored print tools before. Let's review those next week if possible!
- Asked if photos could be included with quotes
