### ISSUE TITLE
Text runs past options margin

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3826]
## QA Notes
PR App: https://janis-3826-step-option-lists.netlify.com/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMTE0
PR: https://github.com/cityofaustin/janis/pull/700

## Describe the bug
These bullet points run over the edge of the options box.
![image](https://user-images.githubusercontent.com/5839508/73009536-63824980-3dd6-11ea-9788-55b0eb041c0f.png)

## URL
Janis preview: https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMTE0
Joplin side: https://joplin.herokuapp.com/admin/pages/349/edit/#tab-content

## To Reproduce
Steps to reproduce the behavior 
example: 

## Current behavior
See screenshot

## Expected behavior
- [ ] @chasechenevert to specify acceptance criteria

**Comment by chasechenevert** [comment]
**The basic answer to what we need is that text doesn't flow outside of the** `accordion panel`. I didn't get to a solution, but I uncovered a few things that might be contributing to the issue that might help a dev get to a solution faster.

- **Content related/non-dev**: `steps with options` were intended to only display instances where a resident needs to choose between methods of delivery for a service (in person, online, by phone, by mail; ex: https://alpha.austin.gov/en/health-safety/health-records-certificates-2/birth-death-certificates/birth-and-death-certificates-test/), but not be used as a method of organization for required items. We may need a new issues to address the style guide, and to understand more about content authors needs around formatting on service pages.  
- A `ul` is being nested within another `ul`, as opposed to a single `ul` with two `li`. On the Joplin side the list is formatted as it should appear (with a secondary bullet style for the secondary list level), but on the front-end it's nesting another list for the secondary bullets instead of list items <img width="944" alt="Screen Shot 2020-01-27 at 10 21 13 AM" src="https://user-images.githubusercontent.com/7027270/73192515-c2093980-40ee-11ea-9523-47ca66282103.png">
- It appears that the `<span>` is longer than the `accordion panel`, which could be contributing to the overflow?
- Accordion panels have 20px of padding around all sides, and `ul` has `20px` of margin around top, left, and bottom sides which is more space than we need. We need accordions to have `margin: 20px` because `p` elements can exist here, and they don't have `20px` around all sides. So what do we do with `ul` when they need to be indented when they're displayed in the context of body copy, but we don't need the `ul` margin if they're within an accordion panel _without_ any `p` elements (and thus don't require indentation)?

**Comment by briaguya** [comment]
made this a 3 because we might have some kinda wonky css in there

**Comment by chasechenevert** [comment]
This looks good, @briaguya. I'm seeing the nesting that I'm expecting the `ul`, and I don't see the overflow in any of the responsive sizes 👍

**Comment by desigonz** [comment]
yay!!! qa passed.

**Comment by briaguya** [comment]
@desigonz this is live in staging now https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozMDIw (open the top option that says "test")

**Comment by desigonz** [comment]
double yay!
