### ISSUE TITLE
Staging Janis build failed

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3841]
### When did this happen?
2pmish

### Where did this happen?
- [ ] Production
- [x] Staging
- [ ] On a branch: *list the branch here*

### What were you trying to do when this happened?
Made a new test page on joplin http://joplin-staging.herokuapp.com/admin/pages/347/edit/ tried to publish

### Screenshots
![image](https://user-images.githubusercontent.com/5839508/73100319-f42e5780-3eb2-11ea-8394-c8a78cf16817.png)

**Comment by easherma** [comment]
https://s3.amazonaws.com/janis-austin-gov-staging/_reserved/logs/910e60d2b6ddd65d58b5b42766b8fa558b44d2a4c688f3c167882abe36f8da02.txt

**Comment by easherma** [comment]
According to the logs, it looks like the page may not have published because there are no steps. 

More specific things to test. 

I looks like steps may have been selected but  not filled? Does the same error happen if they don't exist at all? Does the error go away if at least one step is entered?

This page is related to a department. Does the build fail if steps are empty, but the page is related to another page? Will it not fail if the relation goes away but steps are still empty?

**Comment by easherma** [comment]
Still broke with no steps selection at all but with related department and topics still attached. 

Trying a build right now just adding a single step.

**Comment by briaguya** [comment]
https://janis.austintexas.io/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyOTEy

link to failing preview with step missing

**Comment by briaguya** [comment]
this is old (pre v3, pre publisher) so I'm closing it
