### ISSUE TITLE
Data migration for department permissions

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3934]
### As a product team member, I want pages to be associated with appropriate department groups, so that we can have all of the new department permissions working while also maintaining “offered by” department relationships.

We'll need to retroactively add users/pages to departments so that all of our great department permissions stuff works.

**Comment by briaguya** [comment]
Thoughts: This can be automatic for pages once we associate dept pages with departments (blocked by pages being able to be assigned to depts in the first place), for users, we’re probably better off just doing it manually.

1. Make sure we can add pages to departments (permissions wise)
2. Add all department pages to departments (permissions wise)
3. Write script to add any page that has a related department (page) to the associated department (permissions)

Questions: since we allow multiple related departments, do we need to support a page belonging to multiple departments from a permissions stand point? If not, should we make it so we can only have one related department on a page?

**Comment by desigonz** [comment]
I'd be interested in hearing what @Niicck would say, as well as what the UX implications of that might mean. In the permissions model, we discussed making it so that users can belong to multiple department (in case we want this affordance later), even though on the Joplin for now we're going to limit the ability to add a user to one department for now. I'm wondering if we'd want to do something similar for the page model. We definitely DON'T want it so that you can only have one related department per page. 

Happy to discuss more in person!

**Comment by briaguya** [comment]
## Acceptance criteria testing I've done
### Pages are associated with appropriate department groups
1. Logged in to https://joplin-pr-3813-department-grou.herokuapp.com/admin/login/ as admin@austintexas.io
2. Navigated to the hidden departments as groups view (https://joplin-pr-3813-department-grou.herokuapp.com/admin/groups/)
3. Clicked on "Austin Public Health" (https://joplin-pr-3813-department-grou.herokuapp.com/admin/groups/7/) and scrolled down to see a bunch of pages with associated edit rights

**Comment by desigonz** [comment]
This is looped into the PR branch associated with #3813. More notes in this document: https://docs.google.com/document/d/1FY-enbU7mTFXR8vX2rG7FqnySRqsAFoB8Op1f_--v14/edit# Closing this issue!
