### ISSUE TITLE
Feedback component needs margin-top

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#4062]
## Describe the bug
Lack of top margin on the feedback component is causing the component to stack beneath `services offered` block.
## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to https://alpha.austin.gov/en/location/far-south-austin-clinic/
2. Scroll down to the `feedback` component
3. See error

## Current behavior
```
.coa-UserFeedback {
margin-top: 0px;
}
```

## Expected behavior
```
.coa-UserFeedback {
margin-top: 80px;
}
```
## Screenshots
**Before**
![Screen Shot 2020-02-28 at 3.57.22 PM.png](https://images.zenhubusercontent.com/5b7b6eae2bc79a5e7d4f874c/f98d147e-7392-4b83-a238-bbe0d49776ab)

**After**
![Screen Shot 2020-02-28 at 3.54.20 PM.png](https://images.zenhubusercontent.com/5b7b6eae2bc79a5e7d4f874c/49c1526e-7458-4768-a678-536ed1b1cf35)

**Comment by briaguya** [comment]
@chasechenevert instead of margin top on the feedback component I added a margin-bottom to the content (so if we decide to not use the feedback component at any point a la https://github.com/cityofaustin/techstack/issues/3717 we won't run into an issue of the footer stacking)

I added a quick 2rem margin to the content on location pages for now, but I think this could be a bigger issue for making sure our content -> feedback/footer spacing is correct for:
* Every page type
  * On mobile
  * On tablet
  * On desktop

**Comment by desigonz** [comment]
Assigning @chasechenevert to add thoughts re: the above

**Comment by chasechenevert** [comment]
@briaguya that makes sense, and I'm remembering we talked about this over Slack last week. I've gone in and added the feedback component to all mobile and desktop page types, and I'm working to add tablet sizes with feedback component across all page types. I'll post the update when I have that done.

**Comment by desigonz** [comment]
@chasechenevert We're closing this issue for now since the bug is fixed for short-term, but please create an issue with long-term specs.
