### ISSUE TITLE
Service pages: Apply for a deferral

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4066]
Defendants can ask for a deferral in judgement depending on what kind of crime that they've been charged with. If they can successfully complete the terms of their deferral, the case will be dismissed. 

- [x] Is it true? Yes.
- [x] Is it readable? **The current page is at a grade 9-10 level and uses unusual terms and jargon.**
- [x] Is it actionable. **Yes, the necessary information to fill out and submit this document is in the PDF and supporting information is on the current page.**
- [ ] Send for review by @srigdon, @ablangworthy27 or @Jo-Dwyer

### Disqualifiers:
You are not eligible for a deferred disposition on a moving violation if you:

- Are charged with:

    - Leaving the scene of a collision.
    - Passing a School Bus.
    - Received your citation while driving in a Construction Zone when workers were present.
    - Have a commercial driver license even if the violation occurred while you were driving a private vehicle. 

- If you request a deferral via email or mail and are not eligible, you will be notified, in writing, to select another option to handle your case.

### Payment
Organize as a step with options with an option for each offense type.
Fe differs by offense, information about this is in each pdf. 

### Understand the terms of your deferral
Organize as steps with options. 

### Submission methods 
Organize as step with options.
Mail or in person. Payment must be made by check or money order. Defendants may contact the court if they can't pay immediately.

You **must** appear at court to request a deferred disposition if:

- You are a juvenile (under the age of 17). As a juvenile, you must appear in person at the date and time assigned by the court prior to requesting a deferred disposition.  Keep your address updated with the Court because notices will be mailed.

- You are charged with a code violation (violation other than traffic, parking, red light camera, “no insurance”, no driver license or driving with license invalid, seat belt).  You may contact the court to determine if you are required to attend an appearance docket.

There are six deferral forms that will not be transitioned yet. Upload them to Joplin and link to the PDF.
[Moving violations deferral](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/DeferredDisposition_MovingViolation01_2020_Revised.pdf)
[Bicycle violations deferral](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/DeferredDisposition_BicycleViolation01_2020_Revised.pdf)
[No insurance deferral](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/DeferredDisposition_NoInsurance01_2020_Revised.pdf)
[No license deferral](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/DeferredDisposition_NoDriverLicense01_2020_Revised.pdf)
[Disabled parking deferral](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/DeferredDisposition_DisabledParkingViolation01_2020_Revised.pdf)
[Water violation deferral](http://www.austintexas.gov/sites/default/files/files/Municipal_Court/DeferredDisposition_WaterSafetyActViolation01_2020_Revised.pdf)

### Current page
[Deferred disposition](http://www.austintexas.gov/department/deferred-disposition-0)

**Comment by ablangworthy27** [comment]
This time[ I drafted in Word](https://cityofaustin-my.sharepoint.com/:w:/g/personal/amanda_langworthy_austintexas_gov/Ebd0uffPHj1EiFvX-BR1tOgBzaqMabjhKU2eE5jG-erjIg?e=Itz7F9) because I was working on this without internet at times.

@Jo-Dwyer there are some questions for SMEs in the comments.

**Comment by gabrielaperezdelaosa** [comment]
I moved this draft over to Joplin, updating some things in conversation with Amy.
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo2MjY=

**Comment by gabrielaperezdelaosa** [comment]
just recording some fact-finding here:

1. Can we link to cycling / boat / driver’s safety courses? no because they don't want to be driving business to any one company

2. How often can someone apply for a deferral? technically once a year for each kind of deferral but right now it is not enforced because the case management system doesn't allow it

3. I know deferral fees vary, but can we provide a range?  you can apply for a deferral even when your ticket is way way overdue and has a bigillion late fees, so deferrals can be anywhere from $1XX-thousands of dollars.

4. What is the difference between "Request to take Driving Safety Course" and "Request a deferred disposition for a moving violation"? (this one is complicated) 

Request to take a driving safety course is built into the statue. A judge cannot turn down the request if the conditions are met. And the fee is cheaper ($144) ($169 if violation was in a school zone) . The conditions are: 
- does not have a commercial driver's license (this applies to both) 
- has a charge for a MOVING violation (this also applies to anyone taking Driving Safety school, but there are other deferral options for non-moving traffic violations)
- has a Texas driver's license (there is a military exception)
- has insurance
- has not taken a Driving Safety Course in the past 12 months (proven with a copy of your driving record)
- request must be placed BEFORE their initial appearance date

The ideal from my perspective would be for the "Request a deferral" formstack to have logic that guides users down one of these two paths. However, because the Request to take a Driving Safety Course form requires a notary, temporarily waved during Covid, they are not sure whether that form will continue to exist in Formstack and don't want to do this. So for MVP, I am making a service page that explains the distinction between these two.

**Comment by srigdon** [comment]
@gabrielaperezdelaosa Reviewed! Got it down to a Grade 6 reading level. Edits are in Joplin, notes are in the notes tab.
