### ISSUE TITLE
Draft service page: Get information about a parking ticket and pay online

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4077]
### You can find information about your parking ticket online. You can use this online case search to pay a ticket or to find out a judge's decision.

This online tool will only find cases handled by the City of Austin Municipal Court. If you got a ticket outside of Austin or if it was written by anyone other than a City of Austin enforcement officer, you can't lookup your case or pay a ticket using this tool. 

To look up a parking ticket you'll need:
- your license plate number
- the vehicle identification number OR
- case number 
    - case number can be found by calling the municipal court or by looking it up using one of the other pieces of information.

https://www.austintexas.gov/AmcPublicInquiry/search/vclsearch.aspx

**Comment by gabrielaperezdelaosa** [comment]
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTo2NjA=

I changed it so that the service considers all the options you have for resolving a parking ticket (not just pleading guilty and paying). Otherwise we'd need to do a guide with this service embedded in addition to requesting a hearing or proving you no longer own a vehicle.

**Comment by Jo-Dwyer** [comment]
@gabrielaperezdelaosa this is well done. Does this still need to be reviewed?

**Comment by gabrielaperezdelaosa** [comment]
Amanda reviewed it under #3222
