### ISSUE TITLE
migration tests are not working

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#4083]
Not sure when this started, but our migration test is running into some problems parsing output while dumping/loading data.

Debugging this is a little tricky, but here are problems:
There is a depreciation error getting printed to stout again. Our existing script should strip that; I haven't found a good way to put an debug endpoint in to verify that it is or isn't working. 
Either way, https://github.com/cityofaustin/joplin/tree/4083-migration-test fixes the depreciation error. I think this change would need to be pushed to our docker image to be resolved on the migration test, though. 

However there is no evidence that that is causing the problem directly. 
This is one error you'll get running things
```
Pulling datadump from Production
 ›   Warning: heroku update available from 7.33.1 to 7.35.1.
Running python ./joplin/manage.py dumpdata --exclude=wagtailcore.GroupCollectionPermission --indent 2 --natural-foreign --natural-primary on joplin... up, run.8960 (Standard-1X)
parse error: Invalid numeric literal at line 76027, column 6
#### Deleting intermediate temp datadump
#### Shutting down containers safely
```

If you comment out the jq line, you get a deserialization error:
```
 line 73, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError: Problem installing fixture '/app/joplin/db/system-generated/tmp.datadump.json': 
1
```
When I tried doing the heroku datadump locally, I didn't get expected behavior. My hunch is that the dump itself may be timing out.

**Comment by Niicck** [comment]
jq is used to parse json. It expects a json object. That line of jq looks for "model": "users.user" . It then changes the “password” field for that json object to “pbkdf2_sha256$150000$GJQ1UoZlgrC4$Ir0Uww/i9f2VKzHznU4B1uaHbdCxRnZ69w12cIvxWP0=“, which is a hash for “x”. This sanitizes our prod output, because we don’t want people’s production passwords to be stored on github.
jq needs a json object as its input.
Exhibit A: good.json
```[
{
  "hello": "wurlt"
}
]```
is a valid json object.
Exhibit A: bad.json
```blah blah blah
[
{
  "hello": "wurlt"
}
]
blah blah blah
```
is not a valid json object. This is a txt file that has a json object within it and log output from heroku before and after it.
So before running our jq command on our datadump, we pipe that invalid json text through a cleaner-upper function called ./scripts/remove_logs_from_json_stream.py. This function looks at the text being streamed to it, but skips everything before the [ character, which signifies the start of our json object that we want to save.
start_of_json_pattern = re.compile("^\[") : we’re looking for a line of text that is simply “[”
for line in fileinput.input(): : we iterate through every line of text
elif start_of_json_pattern.match(line) : If we reach “[”, now we know that we’re started our json object!
sys.stdout.write(line) so we can write that line to standard output and it can be piped into our jq operation.
Before remove_logs_from_json_stream:
```blah blah blah
[
{
  "hello": "wurlt"
}
]```
After remove_logs_from_json_stream:
```[
{
  "hello": "wurlt"
}
]```
But there is a problem with remove_logs_from_json_stream! When I wrote it, I only expected dumb console logs from heroku to appear at the beginning of the datadump output. But now we’ve got logs at the end of it as well. So now the function has to get rid of logs at the end as well.
Frequently Asked Questions:
Q: How did you get that output?
A: I ran that line of migration-test.sh directly on my terminal
export APPNAME=joplin
heroku run -xa $APPNAME python ./joplin/manage.py dumpdata --exclude=wagtailcore.GroupCollectionPermission --indent 2 --natural-foreign --natural-primary -- > derp.json
Q: That’s dumb. Why would heroku add stupid console logs when you request a “dumpdata”?
A: idk. Maybe because I’m streaming the output -- . There could be something else I could do to eliminate those non-json messages.
Q: Is there a better way to test that our migrations work on existing production data and creating updated datadumps?
A: One day many moons ago when I was new on the Joplin team, Brain sat us down and walked us through his process of testing new migrations. It was a nightmare manual process that took like an hour to complete each time. So I recreated that process in an automated way using 3 different docker containers. It is convoluted. But it solves our problems of:
Making sure our migrations will work on existing production data. In the past, we had terrible bugs in production, so Brian’s manual process was created to ensure production did not break again due to migration issues.
Having test production data to play with locally and on PRs. If you have a running joplin instance locally, and that instance has new migrations, you can’t then load in production data that is running off an older migration. Joplin will break and reject the datadump.
Perhaps there is a better solution to these 2 problems! My solution was a massive step up from the manual process. But a fresh pair of eyes could look at my solution and find a even simpler solution that does not compromise on our requirements.
And now I’ll get back to fixing our datadump by removing those trailing messages.
Fin.
