### ISSUE TITLE
Secure graphql endpoint

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4129]
- [ ] our /graphql endpoint should not be public
- [ ] our /graphiql endpoint should also not be public

They should be secured with an API token or some other security strategy for janis builds. Maybe you need to be logged in as an admin in order to even reach the /graphiql interface.

**Comment by chiaberry** [comment]
https://www.howtographql.com/graphql-python/4-authentication/

Also from the link above: 
"Unfortunately, the GraphiQL web interface that we used before does not accept adding custom HTTP headers. From now on, we will be using the Insomnia desktop app. You can download and install it from here."

**Comment by easherma** [comment]
Another option(depending on our security goals/concerns) could be using something for persisted queries:
https://github.com/flavors/django-graphql-persist

Which would a) improve performance for site builds and b) allow us to block queries that don't match a given list of valid queries. 

We could also put the api behind a nginx proxy. Not only would this help build performance, it would also allow us the ability to block requests by IP or otherwise throttle requests. 

Also, since we don't have any endpoint for mutations, I'm not sure if there is much risk of data being manipulated through the public endpoint, though I could be wrong there.

These options could help reduce the risk of DOS attacks and also improve our performance/management of the API, so seems like a win-win to me. We'd probably want these measures in place even if we _did_ implement authentication, in case that authentication got hijacked or compromised.

**Comment by chiaberry** [comment]
@Niicck @robbobfrh84 should our graphiql endpoint be available only to admins, or anyone with a joplin account?

**Comment by Niicck** [comment]
Admins, if possible

**Comment by chiaberry** [comment]
See issue #4763 and issue #
