### ISSUE TITLE
Add Kids & Family Theme

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4514]

**Comment by gabrielaperezdelaosa** [comment]
![image.png](https://images.zenhubusercontent.com/5ecd5c4a1cb98b2a16b27154/75d20cba-1b0b-4c39-be3b-258aacc33112)

User story
_As a mom I access a wide variety of city services. Storytime at public libraries, breastfeeding support, WIC, park ranger type programs at parks, Splash Pads and pools, vaccines. If we have a whole section devoted to pets, why can't we have one for kids/families? 

Also, some of these services, such as breastfeeding support and WIC, are housed under a category "Health and Prevention," that I would never think to click on when trying to feed my perfectly healthy kid. 

Yes, we could add a Kids and Family subtopic to Health and Safety, but why would Kids and Family fall under that when really it covers so much more?

Lastly, please note the lower right hand corner of the Megamenu that's shining like a beacon of prime available real estate. :-)_

**Comment by gabrielaperezdelaosa** [comment]
Outcomes of our pinup discussion:
- Design expressed that for now megamenu is not priority since that is not the way most people are landing on our pages.
- There is interest in doing tag-based persona hubs that might connect various services with a kids and families audience
- This prompted me to do a little bit of research into how other cities were handling this
[Slide Deck](https://docs.google.com/presentation/d/13tKoSGq_979Jxec6qDA2oFKnubqxfJHylXKIsDcC9iw/edit?usp=sharing)
[Audit](https://docs.google.com/spreadsheets/d/1Xmw4M8-Jw3Xk_hYTAkyKl3mwZ3LCJbmE4vZFL8r0BI4/edit?usp=sharing)
- I will think about and compile a list of services that might in the future go under such a theme before closing (backlogging?) this issue. 
- For now there will be a kids + family topic collection under "Health and Safety"

**Comment by gabrielaperezdelaosa** [comment]
Here are my thoughts on things that could be under a kids and families theme or a hub page in the future:
**Financial Support**
WIC
CCMS
Free Vaccinations
Austin Children’s Shelter

**Parks and Rec**
Pools and Splash Pads
Playgrounds
Youth Programs
Afterschool Programs
Swim Lessons

**Places and Events**
Library Programming
Nature & Science Center
Austin Children’s Garden
