### ISSUE TITLE
Organize all services pages

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4516]

**Comment by gabrielaperezdelaosa** [comment]
![image.png](https://images.zenhubusercontent.com/5ecd5c4a1cb98b2a16b27154/5309da51-bc11-4df7-8b97-e2aaef0e4a9d)
On a page like [Health and Prevention](https://alpha.austin.gov/en/health-safety/health-prevention/disease-prevention) the "All services" list is pretty unmanageable, and includes info pages. 

How can we better organize this page so that users can get to something like the information on Cripto and other waterborne diseases without having to wade through everything associated with mobile food permits?

**Comment by gabrielaperezdelaosa** [comment]
At Content Pinup we decided that we would handle this by:
1. Creating new topics/collections to better distribute the information
2. @toribr will ask the dev team if we can get it where the guide is what surfaces instead of all the pages associated with it.

**Comment by srigdon** [comment]
Previously, I had assigned both the guide and all of its information and service pages to the Disease prevention topic page, which made that page look crowded. So I took that topic off all the information and service pages. Now just the guide page is assigned to that topic. 

The guide is also assigned to Food business permits (polyhierarchy, whut!), and all of the info and service pages are, too. Since nothing else is on that topic page, yet, it looks fine, but this is an issue for every guide we make. Assign the guide's info and service pages to topics or not? For now, let's not. 

We'll also return to re-organizing topic and topic collection pages on an ongoing basis as we transition more content.
