### ISSUE TITLE
Put visual design guidelines info into the style guide

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4525]
As a City of Austin content author, I want to know what colors, fonts, and design choices I can make in order to create consistently accessible and recognizable content.

**Comment by toribr** [comment]
@Jo-Dwyer I don't understand this issue. Joplin controls all these things. What are you wanting to clarify?

**Comment by srigdon** [comment]
Notes during planning: The Digital Style Guide is being used by authors across the city, and they need design guidelines, too. This isn't necessarily related to the content Style Guide, though. It could be its own guide. 

@chase-vert @toribr and @Jo-Dwyer were talking about putting out our design conventions because right now there are no guidelines for folks across the city.

**Comment by toribr** [comment]
@srigdon @Jo-Dwyer 

Ah, ok. There is a new issue #4545 that design is going to start working on this next sprint. 

I'm seeing this as a start on a bigger document that folks across the city could use, which would also include the style guide as well.

See issue for more detail, and if you don't mind, add your thoughts over there.
