### ISSUE TITLE
"Open in a new window" option for linking in Joplin

### ISSUE THREAD

**Issue by InaraFernandez** [cityofaustin/techstack#4537]
### As a content author, I want to have the option to direct hyperlinked content to a new tab/window. 

**Is your feature request related to a problem? Please describe.**
Currently on Joplin, when I put up a link on a page, it opens in the same window. Some of our content (particularly forms,) are hosted on external pages and this means that the user is directed away from our website (see [Feedback Page](https://alpha.austin.gov/en/feedback/)). This can cause issues because:
- the user might not be done with their session after filling out a form, they might want to hit the "back" button and may get confused about whether or not their responses went through. 
- the user might feel like they need to open the window and start over

**Describe the solution you'd like**
Options for where to open the link- either on the same page or in a new window.

**Comment by srigdon** [comment]
Considerations: 
- Opening in a new tab on mobile is a jarring experience.
- Still, can we responsively open a link in a new tab if desktop and not if mobile?

**Comment by toribr** [comment]
From a UX perspective, the guideline is to never automatically take an action that a user normally does themselves. Opening a new browser window is one of those things. Currently, if we're opening a new window (like for a pdf) we include an icon that indicates that. We don't want to create this affordance in Joplin because that'll then residents won't know which pattern is used. 

I would need research to disprove that this functionality is necessary.
