### ISSUE TITLE
See all pages under a given department in Joplin

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4623]
### As a content creator/strategist I want to be able to see all of the pages under a given department so that I can 1) make sure they're all a part of the IA and 2) do "housecleaning" on my pages as necessary--i.e. check whether there is duplicate or outdated content. 

**Is your feature request related to a problem? Please describe.**
With multiple people drafting pages, it is easy for duplicate work to happen or for a page to "fall through the cracks." 

**Describe the solution you'd like**
I would like a filterable column on Joplin that tells me what department the page is associated with.

**Describe alternatives you've considered**
A list of all pages associated under a given department's page. 

**More context:**
This would also help when browsing Joplin to quickly know who owns the content on a certain page.

**Comment by gabrielaperezdelaosa** [comment]
related to #4544

**Comment by toribr** [comment]
@gabrielaperezdelaosa
As an admin, you are seeing all content. If you were signed in as an author or publisher, you would only see the pages in your department. Since this is the future of Alpha, ie, ODD won't be responsible for all pages, but instead the distributed model will be taken up. Therefore, I'm not convinced an additional column is needed, as it would be work that would only benefit admins. 

In the meantime, as an admin, you can make yourself an additional user name and role, and assign yourself a department which will then show you only that dept.'s pages.

**Comment by gabrielaperezdelaosa** [comment]
Thanks for the solution @toribr !
