### ISSUE TITLE
Create a page for expunging a record

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4630]
- [x] Get a criminal record expunged 
Information pulled from PDF: Expunction Information - Adult
Spanish is available, just gotta put it up

- [x] Get a juvenile criminal record expunged
Information pulled from: Expunction Information - Juvenile
How do you pay the fee? 
Link to requesting a hearing
Add: 
if I still have something on my record and need to get it off, I need to know how to ensure the court expunged it. 
I don’t have to pay a $30 fee if it was for missing school. 
Move missing school to the bottom. 
Maybe the next step is: call the court for verifying your criminal record. Research and ask Amy.

**Comment by gabrielaperezdelaosa** [comment]
Per Amy, this cannot be a formstack because they way they handle formstacks is that the formstack produces a PDF that they then attach to a case in their case manager system. That PDF has a certain look (Field: Entry) that is not customizable. This form needs to look the way it does as a Court petition and not in a Field:Entry format because it goes to other departments.

**Comment by ablangworthy27** [comment]
Here are my edits for:
Get a non-adult criminal record expunged
(edits made in Joplin)

**Change step 1, option 2:**
To expunge the offense of "Possession, Purchase, Consumption, or Receipt of Cigarettes or Tobacco Products By Minors," you must complete a tobacco awareness program or tobacco related community service, and submit a sworn statement to the effect.

Multiple convictions may be expunged.
There is no age requirement.
**to:**
There is no age requirement to have records expunged relating to the: 

- Possession 
- Purchase 
- Consumption 
- Receipt 

of cigarettes or tobacco products by a minor.

You must complete a tobacco awareness program or tobacco-related community service, and submit a sworn statement to the effect.

Multiple convictions may be expunged.

**Did this to lower the reading-level, make it scannable, and to mirror the structure/order of information in the previous option.**

**change in 3rd option of 1st step:**
- Penal Code-Class C misdemeanors
**to**
- Penal Code Class C misdemeanors

- Health and Safety code offenses 
**to** 
- Health and Safety Code offenses

**Step 2, Option 2 change:**
Add phone link. Also, is there any piece of information the caller needs to have handy for reference?

Step 2, Option 3
**Change:**
Mail a check or money order to Municipal Court, P.O. Box 2135, Austin, Texas 78768. Include your case number (found through the case portal) and contact information in your correspondence.
**to:**
Mail a check or money order to Municipal Court, P.O. Box 2135, Austin, Texas 78768. Include your contact information and case number (found through the case portal).

**This simplifies and lowers reading level**

**Step 3 - how are they notified or both the receipt and later the judgement?**

**Comment by ablangworthy27** [comment]
@gabrielaperezdelaosa check out this [preview for Get a criminal record expunged.](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxMTgz) Its separate from your draft because I wanted to play around with formatting.

**Comment by ablangworthy27** [comment]
@gabrielaperezdelaosa check out my updates to [your existing Joplin draft](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxMTg2)

There are a couple questions I noted below that you may want to address, but I left that up to you.

**Change:**
You may be entitled to have the records and files relating to your arrest expunged if:

- you were declared not guilty and/or acquitted after a trial
- OR your case was dismissed over 180 days prior
**To:**
You may be entitled to have the records and files relating to your arrest expunged if either of the following is true: 

- You were declared not guilty and/or acquitted after a trial or if your case was dismissed over 180 days prior.
- Your case was dismissed over 180 days prior.

**See the[ list section of the style guide](https://app.gitbook.com/@cityofaustin/s/digital-style-guide/focus-on-the-public-and-their-needs/make-content-easier-to-read#lists)**

**Change:**
Make sure that you include:

- all of your personal information and any aliases that you are aware of
- all information about your arrest (may be a non-custodial arrest a.k.a “a ticket”) such as:

-the date
-arresting agency
-address at time of arrest
-and location of arrest

- all information about the charges arising from the arrest

-the Court involved
-cause numberthe disposition of the charge(s)
-a copy of the final disposition showing the dismissal or acquittal
**To:**
Make sure that you include:

- All of your personal information and any aliases that you are aware of
- All information about your arrest (may be a non-custodial arrest a.k.a “a ticket”) such as:

-Date of arrest
-Arresting agency
-Home address at time of arrest
-Location of arrest

- All information about the charges arising from the arrest, including:

-The Court involved
-Case number
-The disposition of the charge(s)
-A copy of the final disposition showing the dismissal or acquittal

**re: _All information about your arrest (may be a non-custodial arrest a.k.a “a ticket”_)
I didn't make this edit, because I wasn't sure if there was a reason to keep as-is. But, would it be ok to just say _All information about your arrest or ticket_**

**Add email link to court@austintexas.gov**

**Add courthouse locations**

**Add phone number link**

**Re:** 
A hearing will be scheduled for you. At the hearing, the judge will rule on the expunction petition. You may attend the hearing, but it is not required.

**How are they notified of ruling or hearing date?**

**Comment by gabrielaperezdelaosa** [comment]
Has to say non-custodial arrest. I'm asking about how they hear about the hearing date or ruling.
