### ISSUE TITLE
How do we conduct research at ODD needs to be updated on the research sign-up page because of COVID-19 needs.

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#4688]
The content for the research happening online because of COVID 19 needs to be updated on the https://alpha.austin.gov/en/feedback

E.g: Because of Covid-19 all our research is happening remotely, we don't need to meet in-person to participate in research.

- [x] Re-write feedback paged to shorten, be clear about requirements for participation and let people know that we are conducting research remotely. [See here](https://docs.google.com/document/d/17l5YoVVzySpxeA1ZxgtkJW8izp-0GpFCTS3Jjtd6BPg/edit?usp=sharing)
- [x] Revisit questions on questionnaire 
@toribr to put this issue on your radar and tagging @InaraFernandez, here incase if she has the bandwidth to update the content during this sprint

**Comment by toribr** [comment]
@InaraFernandez I leave this to you to decide if you want to tackle this this sprint.

**Comment by InaraFernandez** [comment]
I can pick this up this sprint, I think it's important. @anukandimalla, we should touch base at some point this week. Here are some user stories that might drive some updates: 
- "I don't speak English, can I still participate in user research?"- I know this information is on the form but it might be worth mentioning it on the feedback page as well
- "I don't have an internet connection at home, can I still participate in user research?"
- " I don't have a desktop or laptop computer, can I still participate in user research?"
- COVID disclaimer- how do we want to write this into the page so that we can adjust it once in-person meetings are safe without having to change a lot of content in the page?

**Comment by anukandimalla** [comment]
Thanks @InaraFernandez , these are really valid questions. As you mentioned let's have a meeting.

**Comment by Jo-Dwyer** [comment]
@anukandimalla and @InaraFernandez is this meeting happening this sprint? this is a valuable initiative.

**Comment by InaraFernandez** [comment]
@Jo-Dwyer , I think it can happen early next week. I do know that Anu is also revising some of the questions in the form and migrating it to formstack. I think a bulk of the work can be done this sprint but it might spill into the week after that.

**Comment by sammodabber** [comment]
@InaraFernandez and @anukandimalla Explore breaking this up into multiple issues

**Comment by InaraFernandez** [comment]
@anukandimalla [This is my draft ](https://docs.google.com/document/d/17l5YoVVzySpxeA1ZxgtkJW8izp-0GpFCTS3Jjtd6BPg/edit?usp=sharing)for the page content revision, can you please confirm that this is factually correct?

**Comment by InaraFernandez** [comment]
@Jo-Dwyer , this is ready for review. Then we can close.

**Comment by Jo-Dwyer** [comment]
@InaraFernandez and @anukandimalla this looks good! do you need me to make an issue for the alert re: remote testing?

**Comment by anukandimalla** [comment]
Please correct if I am assuming this, we decided to go for page banner instead of page alert for "Due to COVID 19, we are currently conducting all research remotely."
