### ISSUE TITLE
Department page doesn't need scheduled publish/unpublish

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4780]
As a department admin, I want to remove/block the ability to publish/unpublish so that I don't accidentally unpublish my department page. @toribr and @Niicck 

Probably not a bug.

**Comment by toribr** [comment]
@Jo-Dwyer Scheduling doesn't work with any page currently, so your intent for this issue is not clear. Admins have certain capabilities - that's what makes them admins. We can't design a system in which people don't make careless errors. Perhaps you mean that the future scheduling feature should only apply to certain page templates?

**Comment by toribr** [comment]
Because the scheduling UI is getting removed as part of another issue, I'm going to close this.
