### ISSUE TITLE
Official docs: PDF content styling

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4787]
## Background
Trying to address the question: how should extracted PDF content look like on a page?
- Wrap all "quoted" content in a container with a fill color to distinguish it from editorial content elsewhere on the site
- Provides a disclaimer about the representation of the information. We'd need to figure this out on the Joplin side.

### Files
- Abstract branch: https://share.goabstract.com/3e6222b2-2c49-4431-a7bd-1693c19036cc
- Dev criteria collection: https://share.goabstract.com/d753d0f0-61c1-435f-ad45-33e58f7d8400

### Text block anatomy
- [ ] Heading
  - [x] English: "`PDF content`"
  - [x] Español:
- [x] `Disclaimer text` 
  - [x] English
    >The following text was extracted from the PDF file to make this document more accessible. This machine-generated content may contain styling errors due to redactions. In some instances, text may not load if the original file is a scanned image or has not been made searchable. For the full version of the document, please view the PDF.
  - [x] Spanish
    > El siguiente texto fue extraído de un documento PDF para hacerlo más accesible. Este contenido generado por máquina puede contener errores de formato. El texto se mostrará en el idioma original del documento. En algunos casos, el texto no se cargará si el documento original es una imagen escaneada o si el texto no tiene capacidad de búsqueda. Para mirar la versión completa, favor de ver el documento PDF.
- [ ] `Quote` sets the information within a `div` that has a background fill, and some padding (see below in `quote`)

### Responsive behavior
- [ ] The content within the `quote` object should `overflow-wrap` as the container changes between breakpoints.

### Quote
- [ ] Desktop and tablet
  - [ ] Padding: `40px`
- [ ] Mobile
  - [ ] Padding: `16px`

**Comment by toribr** [comment]
Original issue: #4751 also placeholder for any joplin impact.

**Comment by chiaberry** [comment]
The following text was extracted from the PDF file to make this document more accessible. This machine-generated content may contain styling errors due to redactions. In some instances, text may not load if the original file is a scanned image or has not been made searchable. For the full version of the document, please view the PDF.

El siguiente texto fue extraído de un documento PDF para hacerlo más accesible. Este contenido generado por máquina puede contener errores de formato. El texto se mostrará en el idioma original del documento. En algunos casos, el texto no se cargará si el documento original es una imagen escaneada o si el texto no tiene capacidad de búsqueda. Para mirar la versión completa, favor de ver el documento PDF.

PDF Content: Contenido PDF

**Comment by chiaberry** [comment]
https://janis-v3-4787-pdf-content.netlify.app/police-oversight/2020-08-17-3/ deployed site

**Comment by jairPineros** [comment]
@chiaberry everything looks good on the english version, but when I switch to Spanish I get a 404
