### ISSUE TITLE
Phase 1 pages for Community Gardens

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4820]
Bonus: come up with a name for phase 1
[Recruit people for your garden](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyNjAy)
[Choose a site for a community garden](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNzQ3)
[First community garden check-in](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyNjAz)
[First community garden permit check-in form container](https://alpha.austin.gov/en/preview/form/UGFnZVJldmlzaW9uTm9kZToxNzgw)

**Comment by gabrielaperezdelaosa** [comment]
@ablangworthy27 thanks for reviewing!

**Comment by ablangworthy27** [comment]
**Recruit people for your garden**
-In step 1, I clarified who the leaders would be communicating with and changed the lead-in to the bulleted list. I also capitalized all bullet items.
-In step 3, I restructured the list. 
-In step 4, I added "These groups may be interested in assisting..." because I found that sentence a bit confusing without the context.

**Choose a site for a community garden**
-I edited step 1 to give more instruction on how to read the map. I actually think it could use more, but didn't want to go overboard. Please double-check that this step is still factually accurate. 
-In step 1, I also prompted the reader to scroll down to read more about private property gardens.
-In step 3, I capitalized all the bullets
-I restructured the more information section and fixed the bullet format

**First community garden check-in**
-Changed the title to make it actionable, because it is a service page. Now it is "Apply for your first community garden check-in"
-In step 1, I capitalized the bullets 
-In step 2, I added an email link to make it easier for the reader to reach out. I also removed the extra spacing. @gabrielaperezdelaosa one thing that I think is missing is the download link for the pdf?
-I didn't change anything here, but we need more details about what the check-in is. Is it strictly a phone conversation or is it scheduling in-person time?

**Comment by ablangworthy27** [comment]
**For the form:**
I don't think I can make the edits myself, but here is my take.

If possible, add a rule so that it doesn't allow user to enter less than 10 plots? What if someone enters 9, should that disqualify them? Or does the gardens team still want to receive the requests and deal with them on a case by case basis?

It also still lets you submit even if you select 'No' for having called 811. I think this might actually be an issue with Formstack (if I remember correctly), so maybe we can remedy that by having an additional line of text in the confirmation message reminding them that their application will not move forward without the info from that phonecall? 
      -Same thing if they DO call 811 but discover there are utilities.

Can you also add an email link to the confirmation message for users to reach out with more questions/follow-up?

**Comment by ablangworthy27** [comment]
Hey @gabrielaperezdelaosa I actually just realized that we should be using 1st and 2nd for first and second. which means some basic changes need to be made across the pages. See the guide entry on that here:
https://app.gitbook.com/@cityofaustin/s/digital-style-guide/focus-on-the-public-and-their-needs/make-content-easier-to-read#numerals

Also you could do this for the titles of the phases:

Get ready for your 1st community garden check-in
Get ready for your 2nd community garden check-in OR Get ready for your follow-up community garden check-in.
