### ISSUE TITLE
Phase 3 for community gardens

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4822]
Bonus: come up with a name for phase 3
[Design a community garden](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyNjAw)
[Get a site plan or site plan exemption](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToxNzY3)
[Final permit application](https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMDc1)

**Comment by ablangworthy27** [comment]
**Design a community garden**
-Changed step one to utilize options
-capitalized bullets and fixed a couple typos
-Just need to remember to add the missing link before publishing, otherwise everything looks good.

**Get a site plan or site plan exemption**
I didn't make any changes to this, but there is no info on how to submit the docs. No address or anything. I am not sure if this falls under something we must resolve for a fast-track migration, but something to definitely make content debt out of.

**Final permit application**
Looks good. just removed some extra spaces

**Comment by ablangworthy27** [comment]
@jo when you are back, can you let me know if you know who the contact would be at DSD for community garden permitting? I think there are details/facts we need to get from them on **Get a site plan or site plan exemption**

**Comment by ablangworthy27** [comment]
@gabrielaperezdelaosa I updated the steps to be a bit more specific. I am not gonna wait to hear back from DSD to close this issue.
