### ISSUE TITLE
Municourt youth services page

### ISSUE THREAD

**Issue by gabrielaperezdelaosa** [cityofaustin/techstack#4876]
- [x] get in touch with a SME
- [x] create a version of this page for alpha: http://austintexas.gov/page/youth-services-juvenile-program

**Comment by gabrielaperezdelaosa** [comment]
These three pages are ready for review:
https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyNDA5 

https://alpha.austin.gov/en/preview/information/UGFnZVJldmlzaW9uTm9kZToyMzA4

https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZToyMzUx

(please check out the associated forms/form containers as well)

**Comment by gabrielaperezdelaosa** [comment]
Thanks @ablangworthy27! I am especially interested in your input on the DACC page since that overlaps a lot with homelessness so any lessons about best language choices there please put on my radar.

**Comment by ablangworthy27** [comment]
**Participate in teen court**

- Made a few very minor punctuation edits.

- City Hall has the same issue with hours that we were talking about re: Great Jones

- @gabrielaperezdelaosa Can you remove the title from the top of the formstack form? I don't have access. We don't put a title or description in the formstack form itself because we do that in Joplin.

- There is some logic that needs to be added to the form:
-Make it so the form prevents user from inputting disqualifying age. It let me submit age 10, which should bring up a disqualifying message.
-There wasn't any info after submitting about what happens next. I also haven't received an email. I know the service page includes it, but it is best practice to include something on the form as well. 
-This form is fairly simple, but we may want to have Jair QA it.

**What to expect as a juvenile at Municipal Court**
Looks good, make a slight tweak to one of the bullets

**DACC page**

- I made a few simple edits to clarify and lower reading level.

- The first hyperlink goes to a map of jurisdictions but should go to something related to electronic devices.

- Step 5 is a bit confusing to me. Does this happen at a later date? How do you know you will have to do this?

- I updated the more information section to make it more scannable. Language is fine, but I wanted to make it easier for people who are stressed to find the bits and pieces of info that they need. Let me know if I created any issues by doing this.
