### ISSUE TITLE
CMS - Edit Page Styling

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#533]
- [x] components (existing)
 - [x] Steps component will stay WYSIWYG
 - ~Style guide sidebar will be present #467~
 - ~help text w/ scroll to links to corresponding style guide section~
- [x] secondary informational headers
- [x] add question mark icons, move style guide links to icon click

**Comment by toribr** [comment]
![screen shot 2018-07-18 at 5 30 36 pm](https://user-images.githubusercontent.com/3790067/42911492-c5973868-8ab0-11e8-8063-732ce1cb96cd.png)
 There is an additional secondary informational header here which is intended to let the user know how this component appears to the resident.

**Comment by toribr** [comment]
**Character limits and counting (SEO and elsewhere)**
While we know the SEO component won't come into play for a while, we do know from previous usability testing that we'll probably need to encourage the user to write more. The arbitrary minimum we have set for now is 150 characters. 

Additionally, due to design constraints on the front end, we may have need to limit characters of certain fields. For instance, we may need to limit service page titles.

1) Can we create the pattern now for min and/or max for fields? 
2) Ideally, in some instances this should manifest as a active character count (see attached image for example.)
![screen shot 2018-07-02 at 4 17 05 pm](https://user-images.githubusercontent.com/3790067/42912102-48dadfac-8ab3-11e8-8fde-59562b5fa90e.png)

**Comment by mateoclarke** [comment]
@toribr, we're going to separate the character limit stuff to a separate issue. Not sure if you intended for it to be part of MVP but we can discuss that.

**Comment by mateoclarke** [comment]
@toribr, can we chat about where all we should add the section headers?

**Comment by toribr** [comment]
![screen shot 2018-08-06 at 8 45 40 am](https://user-images.githubusercontent.com/3790067/43720220-7f883972-9955-11e8-8169-5d73b12c5b6a.png)
For all page types, there is no need for that page type name to be rendered. The word Edit followed by the page name will suffice.
