### ISSUE TITLE
Joplin Alpha - SEO fields on Service Page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#617]
Sketch file: https://drive.google.com/open?id=1S5Ida1oIhDDf9R0RGe_sXbdDllkr8Pju

![edit page updated](https://user-images.githubusercontent.com/3790067/43971094-78fd28fe-9c95-11e8-8220-5a1c4234b55d.png)

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] What happened to the SEO tab?
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://desi1.aha.io/features/RT-246

**Comment by ifsimicoded** [comment]
Currently SEO content is being hidden. @toribr at one point your mocks had the SEO content at the bottom -- this is possible -- if that's still the tested preference.
Sample code for how to accomplish SEO fields in the content panel in this [demo PR](https://github.com/cityofaustin/joplin/pull/153)

**Comment by toribr** [comment]
@ifsimicoded 

Let's just unhide the tabs for now. My thought is that these sections need particular styling to make them obviously different, and rather than add styling issues to the edit page, it seems safer to just leave them on a tab for now.

My thought was to include them, even though I am aware that their content won't be used in any meaningful way anytime soon because the SEO component and the tag component both gave users pause. So the earlier we implement them, the earlier we can begin to learn how to improve usability for users. @amenity I could be talked out of making this MVP, however.

**Comment by amenity** [comment]
I agree that implementing them early is good for learning, but to keep the MVP scope tight I'm leaving this as Alpha.
