### ISSUE TITLE
Design Department Page v1

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#636]
Continue to flesh out and design Department Ppage. 

- [Celine's last file](https://files.slack.com/files-pri/T04KZA1MB-FC83W0TC4/alpha_4.0_l_department.png
) 
- [Content model](https://docs.google.com/document/d/1v0SWKBJJU7hkAQ9sJ-KsaRrDOTcgM-t9vWC6FpxQa80/edit#)
- [Sample content to start with](https://docs.google.com/document/d/1LNk5SsdbxvvW_f38lux2Chg49tjrm6NZUhUtNxrDb3M/edit?usp=sharing)

### MVP 
1. Department Page Title
2. Banner Image
3. Dept name
4. Contact Information
6. What we do here
8. Mission block
10. Popular services
11. Social media links

### Future releases
7. Places - any locations associated with that dept
9. Highlight block - seasonal
12. News blocks
13. Director block
14. Article/blog
15. Gallery
16. News/press release

**Comment by amenity** [comment]
From 8/23 sprint review: Should divisions have their own pages, too? E.g. Parks and Rec has divisions that do very different things.

**Comment by chasechenevert** [comment]
# Pin-up 1
with: @toribr @benguhin

Prototype with comments: [department pages_2018-08-28_2.1](https://xd.adobe.com/view/87c57f51-8153-4c9d-79a6-64a5ba2e80ac-f1f4/screen/de435906-873f-42f1-ad83-118236946b2b/Department-Austin-Public-Health-iteration-1-1)

## Follow-up items
- [ ] Content block: which contact is the primary contact for a given office? Especially those with multiple divisions...
- [ ] Director block: what other type of content will be here? Bio, or more leadership?
- [ ] In an optional component, are all fields required?
- [ ] Spaces: better to bundle these with service pages
- [ ] Design: create and propose a lightweight graphic pattern for backgrounds

## Feedback
**Header**
- It’s on departments to update these images, and we can’t trust that they will abide by quality standards especially where overlays are concerned. Maybe divorce the banner from the header block.
- Height might be an issue, try something smaller.
- Eyebrow is good, helps to distinguish the action from the department name (helping users locate where they are)

**Contact**
- Questions around which contact information is listed here
- Edge case: different hours per days of the week
- Add in icons
- Responsive: where would it go in mobile

**Mission and Vision blocks**
- Curation and legibility issues with overlays. Try solid colors or patterns and other visual treatments without images
- Stacking these blocks may help with balance if one section has more copy than another
- Spaces
- Lots of questions about whether this is a good place to put this content. Current ideas are to cluster these locations within service pages.
- Divisions are going to be a big issue, but they will need to be hosted here.

**Services**
- Higher up on page
- Search component instead of pull down
- Remove second row, just top 4 (death certificate, birth certificate, food safety, …)

**Director**
- Feels a little lonely here: maybe other content (bio)? Visual style (pattern)?
- Border around content block (tray)?

**Article feature**
- Try more “blog post” style here
- Doesn’t need the CTA button, a text link to “read more” is more appropriate

**News**
- Move “view all news” to bottom of list, matching “press releases”
- Check last rule spacing

**Comment by chasechenevert** [comment]
# Pin-up 2

September 4, 2018
**Attending**: @amenity, @LauraTrujillo, @courtneyjacinic, @toribr 

Link to prototype: department pages-2.4

## Summary
Overall the group is excited about the refinements. The topic of how far to explore came up with the support that things are easier to change earlier, especially where variables are concerned within the stylesheet. I’m staying mindful of stakeholders outside of this team who may have strong opinions about visual design, but also being diligent to explore where I have the opportunity and responsibility, and ensure that I’m building on top of previous work and documenting decisions and changes as we go.

Prepare for Thursday sprint review. Pay attention to defending changes (especially around color) as there is expected to be a lot of attention and opinions on the visual design.

## Follow-up
- [ ] draft 2.5 for Thursday
- [ ] prep for Thursday

## Feedback
**Header**
- [ ] Nix “learn more about” eyebrow on mobile? Team likes it on desktop, but as a way to cut down space, potentially hide on mobile.
- [ ] Subnav (new)
- [ ] Add a sub nav for “contact”, “services”, and “news” to make it easier for frequent visitors to go right to the content they need, especially if there’s the potential that these pages could run long. 

**Contact**
_No feedback at this time_

**Mission**
_No feedback at this time_

**Services**

- [ ] Change title to, “Find a public health service”
- [ ] Remove search for now
- [ ] Add “See all services”

**Director**
- [ ] Shorter body copy
- [ ] Show edge case of multiple directors and their bios
- [ ] Article feature: “Read more” should be styled as a link

**News**
- [ ] Labels for categories
- [ ] Text link styling for “view all news”
- [ ] correct “Press Release” link text to “View all press releases”
- [ ] Consider adding “Public Health” to “Latest News” title
- [ ] Link-out icon

**Comment by chasechenevert** [comment]
A quick note from Tori re: Latest News and Press Releases:
> I think it's better if we can keep Press Releases and Latest News visually distinct, as I think they'll each have their own content model. So think about how they would work if only one was present, or both, and also not necessarily grouped (ie, the authors will have the ability to move each optional content block to the order they prefer.)

I'll update the notes and get this reflected in the next iteration.

**Comment by amenity** [comment]
First draft is 👌 👌 👌  . Now paring down to MVP in #669.

**Comment by chasechenevert** [comment]
Mockup 2.5 for presentation today. It contains the original sketch, MVP, and future release.
[](https://xd.adobe.com/view/0bd95529-38e5-4b65-51f0-413e21e68486-7de8/
)

**Comment by chasechenevert** [comment]
### Addition: department-specific jobs link
This came from a question during Content's presentation to the Public Health managers last week.

**Comment by toribr** [comment]
**### Addition: department-specific jobs link**

Because this block contains only bits that are implemented elsewhere, this component has been moved to MVP and should be added to the comp. Note that the MVP version of this component allows for only one director to be added.

**Comment by toribr** [comment]
Addition: social media icons
-[ ] Needs youTube icon

**Comment by amenity** [comment]
Adding the tasks above to #739
