### ISSUE TITLE
Joplin Alpha: Implement Department Page content model

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#664]
Update Department model/API endpoint/Author interface to match spec: https://docs.google.com/spreadsheets/d/1ZkH93F4tJ0_Zjx4t8k6k6TgwSlOh8u8ejWmegE6WqH0/edit?ts=5c3e0a70#gid=1814414513

**Comment by amenity** [comment]
@briaguya - would you please size? 🙏

**Comment by briaguya** [comment]
@amenity could you link me to info on the department page? Can't size it without knowing what's going into the page.

**Comment by amenity** [comment]
@briaguya mock link added!

**Comment by chasechenevert** [comment]
Here are the most up-to-date specs I have. Please be in touch as this gets implemented. This is my first hand-off on this team, and I know we're using XD for the first time among other small changes. I want to make sure that dev feels supported, and that if you don't have exactly what you need I can fix things on my end.
# Specs
- [janis_department MVP_october 2018](https://xd.adobe.com/spec/ffbf056a-0669-41e7-443d-6c75219a7211-898e/#access_token=eyJ4NXUiOiJpbXNfbmExLWtleS0xLmNlciIsImFsZyI6IlJTMjU2In0.eyJpZCI6IjE1NDAyMjY2NTk0MDBfNTM0MTM0YzMtOGQwYi00NjI3LWEzMTUtOGUxNzlmOGUwMzM0X3VlMSIsImNsaWVudF9pZCI6IkNvbWV0V2ViMSIsInVzZXJfaWQiOiIxNzM5NEYzMDRFODNGMDdCMEE0OTBENDVAQWRvYmVJRCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcyI6Imltcy1uYTEiLCJmZyI6IlMzWkFWUE42WFBQMzdYRzYyNEJRQUFBQVJFPT09PT09Iiwic2lkIjoiMTUzNzg4MzQ3MTM4OV84NWFmYjExMC1iNzJlLTRlMTQtYmVjMC1iNTY4OGM4OWFkMDZfdWUxIiwibW9pIjoiODAyOGVlYjMiLCJjIjoiY2gySGx5WEJ0RGJGcnBNd2oySGtrZz09IiwiZXhwaXJlc19pbiI6Ijg2NDAwMDAwIiwic2NvcGUiOiIiLCJjcmVhdGVkX2F0IjoiMTU0MDIyNjY1OTQwMCJ9.GoESRkNlGwPN_1uS3VOWrtj0nkjXmTNCz8UGCmKHA8P3uIHHEtNgO7kMK1pyhX4SPCXvJiTqLVBR0FHE0yQNKmTI379KCInkU9mzQS4iPCFKBdltxxnf9C-sn-Y_SJGnn0hEJnssOFB878XmMeBefiSONI963LnTzYXcRFg6YpJTH8obX5jFBAmhyeO4OL0mirRl0uGCmudkxv9AAKJY_2fOyv1lbH7MnZJoLFhzr3ENuVP5iQebUAC5RiMmKeOIW9H2ivacmvlFcpOiswjiKpxJO9-tTHcvIRs4e7zQkKLqiO38nG7WBv0xB1RWQPQf1xaVwP1NIaPcu4neUbVgAA&token_type=bearer&expires_in=86399993) XD Spec
- Doc: [Spec supplement](https://docs.google.com/document/d/1TtX4fJoQfvwdJnPmUpYI1Fzyqf2rmC6CJsEKnfqCYhE/edit#) (I'll paste the notes below)

## Spec notes
**Typography**
*Please note that I am using IBM’s open source Plex typeface for testing purposes, but you don’t need to switch over the stylesheet for this typeface yet since I’m considering many options.

**Spacing**
- Reference: [USWDS v2 Spacing Units](https://v2.designsystem.digital.gov/style/spacing-units/)
I’m using consistent spacing based on the USWDS v2 spacing units so that spacings between elements is consistently applied. The mockups have been annotated with the spacing units in both pixel and token labels.

### Components
**Service Tile**
```
Corner-radius: 4px;
Padding: 40px;
Border-bottom: 4px;
```
**Steps**
- Bullets distance from text should be 18px

Options
```
Background: #F3F3F3;
Padding: 30px;
Border: 4px 0px 4px 0px;
```
**Related Services**
```
Width: 1348px;
Height: 540px;
Padding: 80px;
Background-color: #F0F0F0;
Font-size: 48px; (heading, H3)
```
Service tile (an individual service)
```
Width: 278px;
Height: 223px;
Background-color: FFFFFF;
Border-bottom: 8px; 
Border-color: #0066D7;
Font-size: 20px; (heading, H6)
```
**Contact**
```
font-size: 20px; (heading, H6)
Font-size: 16px; (body 1)
Map preview size: width: 313px; height: 292px;
```
