### ISSUE TITLE
Refine Service Page design

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#671]
Updating design system as we go, refine Service Page design. 

Current mockup: https://xd.adobe.com/view/cfb1ac5a-4640-4832-4d44-ad95b6fac902-b980/

See #650.

**Comment by amenity** [comment]
@chasechenevert current mockup: https://xd.adobe.com/view/0bd95529-38e5-4b65-51f0-413e21e68486-7de8/

**Comment by chasechenevert** [comment]
I want to get into a habit of sharing more frequently, likely at the end of each day so that the progress is a lot more visible. This is where I'm stopping today: I'm prioritizing the mobile interface of the service pages, then extending to desktop. I know there are a number of things here that progress a few components, so I'm well aware that I may need to scale this back for MVP, but I think it's worth seeing a more fully fleshed out idea and pulling back where necessary. 

![service_mobile_v2 2_alternate 2](https://user-images.githubusercontent.com/7027270/46106192-aeb62900-c19d-11e8-9a3c-e119d02e62b3.png)

**Comment by chasechenevert** [comment]
## v2.3 design progression
There's been a lot of development here since the last post. I'll round up the updates under here soon!

## Pin-up notes
- [ ] Remove “SERVICE” label for MVP
- [ ] Replace “Section Title” with “Related Services”
- [ ] Remove text bolding 
- [ ] Remove “view more” from mobile
- [ ] Expand one of the options 
- [ ] Show an option with a banner image (since it’s noted in the Content Model)

![service-death certificate_web-collapsed_v2 1 4](https://user-images.githubusercontent.com/7027270/46364132-88c7d300-c63a-11e8-88ca-9b7f0ba0ca33.png)
![service_mobile_v2 2_alternate 2 8](https://user-images.githubusercontent.com/7027270/46364133-88c7d300-c63a-11e8-95fb-d1d88f9a7d1f.png)

**Comment by chasechenevert** [comment]
![service page v2 3_deliverable](https://user-images.githubusercontent.com/7027270/46479354-7d98b280-c7b4-11e8-9dfe-e96979af53b3.png)
![service_mobile_v2 3_alternate 2 8](https://user-images.githubusercontent.com/7027270/46479355-7d98b280-c7b4-11e8-8fff-d2b6c7f948a0.png)
