### ISSUE TITLE
Database Backups

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#731]
- [ ] Investigated good interface and workflow for manual and automated backups
- [ ] Implement decent management

Ability to apply database backs to review apps, staging, and productions.
Figure out database rollbacks for production and how this connects to production code rollbacks.

**Comment by briaguya** [comment]
Slack convo from 9/26 about how to handle data model changes/migrations

Simi Damani [14 hours ago]
@sergio @brian since all our fixture data loading happens as part of a migration, when we create new migrations the fixtures will load before the new migrations are run. This seems really problematic.


Simi Damani [14 hours ago]
We'll need to manually update that load fixture code -- and manually move it to the latest migration file. this seems not ideal. What do y'all think?


Sergio Garcia [3 hours ago]
It makes sense, the whole idea was to deprecate yml files and move towards direct database entries.


Sergio Garcia [3 hours ago]
The fixtures data has all been put into a django migration file: 0030_auto_20180924_1554


Sergio Garcia [3 hours ago]
I do think this may be problematic if the models change dramatically, I think the same will happen with existing data that is persisted in postgres.

Simi Damani [1 hour ago]
Yea, I'm already dramatically changing the models - and we can expect this to be the case i think for the short term



Simi Damani [1 hour ago]
So is there a way we can put this fixture loading into a separate load script that runs after all migrations are run?


Simi Damani [1 hour ago]
That way our data models are up to date before we try to insert fixtures?


Simi Damani [1 hour ago]
And we're not trying to hunt down a random migration file to change when we want to change how fixtures are loaded?


Simi Damani [1 hour ago]
@sergio sorry for the barrage. I'm also open to other ways of loading our existing data. Whether as fixtures or not -- there's a lot of existing page data we have that needs to be loaded and stored by the db.


Sergio Garcia [1 hour ago]
No problem at all! :slightly_smiling_face:


Sergio Garcia [1 hour ago]
I am open for this, ideally we should not need fixtures though, because we need to be able to deal with live data once it pours in.


Sergio Garcia [1 hour ago]
We would have to get rid of migration id 0030_auto_20180924_1554, and incorporate the loadcontent script. What is your opinion @brian?


Brian Smith [1 hour ago]
I think this is a good exercise in how we need to be able to manage loading backups etc.
For example: we have a backup from a week ago before we implemented a model change. We want to diagnose an issue and load that data from a week ago into a branch. We should be able to load that DB backup and then run the rest of the migrations to get back to the model we're on now


Brian Smith [1 hour ago]
Ideally, we should replace the fixtures/loadcontent etc. with a DB backup. Then just hydrate that and run the rest of the migrations on any given instance.


Brian Smith [1 hour ago]
That relies on our postgres all the things issue though


Sergio Garcia [44 minutes ago]
Agreed, I am a couple days away from that. I will try to get that sorted out during the weekend.


Sergio Garcia [43 minutes ago]
In the mean time @Simi, I think you should be able to undo the latest migration for base


Sergio Garcia [42 minutes ago]
ie ./joplin/manage.py migrate base 0029...


Sergio Garcia [42 minutes ago]
or delete 0030 (locally) and rebuild


Sergio Garcia [42 minutes ago]
then run ./manage loadcontent <list of yml files>


Simi Damani [41 minutes ago]
not sure I 100% understand. I commented out what I needed to, to update the steps. But I'm not sure now how to put that data back in?


Simi Damani [40 minutes ago]
so I should delete migration 0030 ... and then ... ?


Brian Smith [39 minutes ago]
@sergio is there a reason that model changes would make it so migration 30 is breaking things?


Simi Damani [39 minutes ago]
i have migrations already in place after 30

Brian Smith [39 minutes ago]
shouldn't the DB be able to handle that data changing with later migrations?


Brian Smith [38 minutes ago]
@Simi if you don't change migration 30, does everything still load up properly but we just don't have the steps?


Simi Damani [38 minutes ago]
right.


Simi Damani [38 minutes ago]
I commented out the line that loads steps tho


Brian Smith [38 minutes ago]
in 30?


Simi Damani [38 minutes ago]
yes


Sergio Garcia [37 minutes ago]
30 is simply seed data directly from the yml files


Brian Smith [37 minutes ago]
can you try reverting the line in 30 so it still loads steps?


Brian Smith [37 minutes ago]
@Simi I know that won't make them work with the new format, but we should at least see that it doesn't break that way


Brian Smith [36 minutes ago]
if it doesn't break, then we should have broken data around steps in our service pages, which is a good thing


Simi Damani [36 minutes ago]
ah k, i'll give that a go


Brian Smith [35 minutes ago]
then we have a couple of options, ideally, we should have it so we can back up the data in a DB and then just save a new backup with the reformatted steps data


Brian Smith [35 minutes ago]
that might take a bit to implement though


Brian Smith [34 minutes ago]
a second option would be to figure out a way to write a manual data migration from the old steps model to the new steps model, which is a pattern we should figure out as we start having more and more data in the DB and start making model changes in the future


Brian Smith [33 minutes ago]
and a third option (my least favorite) - is to just make another data migration script after we do the model migrations that loads the steps data into the new format


Brian Smith [33 minutes ago]
I think working towards option 2 is the best plan


Sergio Garcia [31 minutes ago]
any model changes will require the loadcontent script to be updated anyway, I envisioned the 3rd option to be the new way forward so we could track when those changes happened (edited)

Brian Smith [30 minutes ago]
we really shouldn't be using the loadcontent script



Sergio Garcia [29 minutes ago]
Agreed, my vision was for the database backup tool could make sure certain migration ids are in place before trying to import


Sergio Garcia [28 minutes ago]
** to make sure the receiving app is compatible


Sergio Garcia [26 minutes ago]
@Simi let me know if there is anything I can do to help you run loadcontent to the containers


Brian Smith [24 minutes ago]
@sergio I'm not sure I follow. I was thinking:
1. Hydrate DB from backup (this includes data that matches a schema)
2. Run migrations that are in codebase but not in DB
3. Boot up app


Brian Smith [24 minutes ago]
There shouldn't be any reason to check on what migration versions any given app is running


Brian Smith [23 minutes ago]
we should simply be able to run forward migrations on any DB and keep our data intact (or modify it to match it if we make model changes)


Sergio Garcia [19 minutes ago]
Hmm, I see. That makes sense, I under the impression the db tool would only run the 1st step and not the migration process.


Sergio Garcia [19 minutes ago]
Gotcha, I am gonna give it some thought to it


Brian Smith [12 minutes ago]
Really we need to think about how to handle this with live data too - when we update the data model we need to make sure we can migrate our data to the new model. We're talking thousands of pages eventually so we need to make sure we have scripts that can handle that, we can't rely on keeping the model the same forever


Brian Smith [11 minutes ago]
so being able to run migrations on the DB should get the model AND the data to where it needs to be
