### ISSUE TITLE
Default image for service page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#744]
Service pages all need a banner, yet we don't want to require the user to have to add one in order to publish. Therefore we need to provide a default banner image that's already in place when the page is created. For now, this image will need to work for all service pages, so should be generic in nature.

At a later date, the service pages should have a default image that's relevant to the department.

The default image should render on the preview along with title and topic upon creation. The user may delete the default image and supply another image.

**Comment by chasechenevert** [comment]
Some food for thought: 
- Do different banner images for different types of users enhance their experience? It can help tie the service to the relative department, but potentially leaves open the question of what happens for services that are owned by more than one department...
- Is it important to distinguish services from each other? What about services from processes? 

I definitely want to have a discussion about this with content and design, and potentially get this idea up in front of users once we're stable enough to look into it. I'm very open to either option, and eager for feedback.

My initial thinking is that service pages remain hyper-focused on the steps and the information, and try to remove any other visual "accents" that don't clarify or focus on the content. I like the idea of services having a consistent look (i.e. not distinguishing themselves by department, since we know that users aren't really thinking in this way about services). In a wider view of the experience across the site once it's at volume, I like the idea of topic clusters and departments having these nice rich images, but keeping the services narrowly focused on the steps.

<img width="1279" alt="screen shot 2018-10-10 at 1 35 46 pm" src="https://user-images.githubusercontent.com/7027270/46758105-96600700-cc91-11e8-8dc9-d4a03cc16a7a.png">
<img width="1323" alt="screen shot 2018-10-10 at 1 35 52 pm" src="https://user-images.githubusercontent.com/7027270/46758106-96600700-cc91-11e8-8f60-ac5a2a617128.png">

**Comment by toribr** [comment]
These are all great points. Additionally - if the image doesn't add any real value, and is merely decoration, then we are increasing download times unnecessarily. Also, there's the editorial issue of finding suitable images, as well as legibility of page title over images.

I vote for no images. I wonder, though, about the possibility of adding some sort of service graphic or icon as a way to identify or relate service pages to one another.

**Comment by amenity** [comment]
@courtneyjacinic @LauraTrujillo @ashleecoa @wilhitem - how do you feel about forgoing banner images? 
If we did default images, we'd have a few options like the hands-on-keyboard, Austin nature scene, skyline...Tori pointed out that once we're going to default images, what's the point?

**Comment by ashleecoa** [comment]
I'd vote to keep banner images. I think authors will be upset if the system is so restrictive that they can't choose images that are specific to their service. But I'm open to discuss @amenity

**Comment by amenity** [comment]
Since we are designing Janis to serve residents, I don't think the preferences of City staff should determine its design. 

That said, I talked to @toribr and @chasechenevert about my concern the site might feel too cold without images. We had a good conversation, and ultimately I'm comfortable forgoing them for now.

For posterity, main considerations in this decision are:
- Fewer images/assets = better performance for residents
- More consistency site wide - e.g. resident doesn't go from service page to dept page and have banner element disappear
- Nixing images reduces overall staff workload since it removes the editorial task of identifying and curating images
- In general, we should be defaulting to the most simple design and extending/embellishing it if and when we need to.
