### ISSUE TITLE
Janis 2.0: Implement Service Page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#815]
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/ce9e7492-b75b-472c-9dab-98d7bd1843ba/Service-MVP-Web/

**Comment by chasechenevert** [comment]
Here are the most up-to-date specs I have. Please be in touch as this gets implemented. This is my first hand-off on this team, and I know we're using XD for the first time among other small changes. I want to make sure that dev feels supported, and that if you don't have exactly what you need I can fix things on my end. Also, if there's any opportunity to let me pair/shadow with the dev implementing these changes I would love to since I'm brushing up on my front-end chops and want to be able to dive in more with helping to update the CSS. 
# Specs
- XD Spec: [janis_department MVP_october 2018](https://xd.adobe.com/spec/ffbf056a-0669-41e7-443d-6c75219a7211-898e/#access_token=eyJ4NXUiOiJpbXNfbmExLWtleS0xLmNlciIsImFsZyI6IlJTMjU2In0.eyJpZCI6IjE1NDAyMjY2NTk0MDBfNTM0MTM0YzMtOGQwYi00NjI3LWEzMTUtOGUxNzlmOGUwMzM0X3VlMSIsImNsaWVudF9pZCI6IkNvbWV0V2ViMSIsInVzZXJfaWQiOiIxNzM5NEYzMDRFODNGMDdCMEE0OTBENDVAQWRvYmVJRCIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJhcyI6Imltcy1uYTEiLCJmZyI6IlMzWkFWUE42WFBQMzdYRzYyNEJRQUFBQVJFPT09PT09Iiwic2lkIjoiMTUzNzg4MzQ3MTM4OV84NWFmYjExMC1iNzJlLTRlMTQtYmVjMC1iNTY4OGM4OWFkMDZfdWUxIiwibW9pIjoiODAyOGVlYjMiLCJjIjoiY2gySGx5WEJ0RGJGcnBNd2oySGtrZz09IiwiZXhwaXJlc19pbiI6Ijg2NDAwMDAwIiwic2NvcGUiOiIiLCJjcmVhdGVkX2F0IjoiMTU0MDIyNjY1OTQwMCJ9.GoESRkNlGwPN_1uS3VOWrtj0nkjXmTNCz8UGCmKHA8P3uIHHEtNgO7kMK1pyhX4SPCXvJiTqLVBR0FHE0yQNKmTI379KCInkU9mzQS4iPCFKBdltxxnf9C-sn-Y_SJGnn0hEJnssOFB878XmMeBefiSONI963LnTzYXcRFg6YpJTH8obX5jFBAmhyeO4OL0mirRl0uGCmudkxv9AAKJY_2fOyv1lbH7MnZJoLFhzr3ENuVP5iQebUAC5RiMmKeOIW9H2ivacmvlFcpOiswjiKpxJO9-tTHcvIRs4e7zQkKLqiO38nG7WBv0xB1RWQPQf1xaVwP1NIaPcu4neUbVgAA&token_type=bearer&expires_in=86399993) 
- Doc: [Spec supplement](https://docs.google.com/document/d/1TtX4fJoQfvwdJnPmUpYI1Fzyqf2rmC6CJsEKnfqCYhE/edit#) (I'll paste the notes below)

## Spec notes
**Typography**
*Please note that I am using IBM’s open source Plex typeface for testing purposes, but you don’t need to switch over the stylesheet for this typeface yet since I’m considering many options.
- I do want to update the site-wide typescale and use a token system for ease of use. So far this is where I'm at on building that out: [typescale google sheet](https://docs.google.com/spreadsheets/d/1aSeJhXNhECYmyU4NWxGGlE_Z4Ou5OfIM2mpNSPC6IcA/edit?zx=6jb1ms321p8t#gid=0)

**Spacing**
- Reference: [USWDS v2 Spacing Units](https://v2.designsystem.digital.gov/style/spacing-units/)
I’m using consistent spacing based on the USWDS v2 spacing units so that spacings between elements is consistently applied. The mockups have been annotated with the spacing units in both pixel and token labels.

### Components
**Service Tile**
```
Corner-radius: 4px;
Padding: 40px;
Border-bottom: 4px;
```
**Steps**
- Bullets distance from text should be 18px

Options
```
Background: #F3F3F3;
Padding: 30px;
Border: 4px 0px 4px 0px;
```
**Related Services**
```
Width: 1348px;
Height: 540px;
Padding: 80px;
Background-color: #F0F0F0;
Font-size: 48px; (heading, H3)
```
Service tile (an individual service)
```
Width: 278px;
Height: 223px;
Background-color: FFFFFF;
Border-bottom: 8px; 
Border-color: #0066D7;
Font-size: 20px; (heading, H6)
```
**Contact**
```
font-size: 20px; (heading, H6)
Font-size: 16px; (body 1)
Map preview size: width: 313px; height: 292px;
```

**Comment by amenity** [comment]
@chasechenevert - I think these are the most current mocks, yes? https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9055635c-de21-497d-b8fb-631c3e39c802/Department-MVP-web-23/

**Comment by amenity** [comment]
Duplicate of #876
