### ISSUE TITLE
Alerts/notices about Austintexas.gov transition to Austin.gov 

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#82]
Verbiage and UI elements to take users between Austintexas.gov and Austin.gov. This includes:
 - Notice on Austintexas.gov page that the content exists on Austin.gov and an invitation to visit it
 - Notice on Austin.gov page that the content is newly transitioned from Austintexas.gov and a link to original content

Aha! Link: https://desi1.aha.io/features/RT-345

**Comment by amenity** [comment]
From Sara Hall / Phila.gov in the Municipal Design Slack

> Hey @here I just posted in the #general channel but I'm the Product Manager for the City of Philadelphia. We've been developing a new website in parallel to the existing at beta.phila.gov (building out the platform and migrating content) and are ready to make the jump to have our new site's homepage the City's homepage (some content will still live on the old platform but everything will be phila.gov/_____).  I'd love it anyone had any insight or thoughts on the following:
>
> - Does anyone have any tips on how to ease the situation with users who have never visited beta?
A bit more context: We've used a modal on the existing phila.gov page to ask users if they want to go to the new site or stay on the old. Many folks have said 'No. stay on the old." and have not seen the modal since (we save it as a cookie). Next week we're replacing the current modal and resetting cookies with a "This is changing" modal, in hopes to let people know.
>
>- Does anyone have good examples of how to orient users once the change occurs? We're removing the beta-ness from beta.phila.gov but are thinking of ways this has been done well. For example: a modal letting users know of the change, some type of on-boarding (that's a bit overboard in my mind though)
