### ISSUE TITLE
Janis v2 Design: Translation bar

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#854]
- Needs to fit 4 main languages
- Consider for both mobile and desktop

**Comment by chasechenevert** [comment]
### Sprint 18 plan: 
- [ ] Document the knowledge Tori passed about why we want to expose translation options initially
- [ ] Mockup: add translations back in

**Comment by chasechenevert** [comment]
Reverted back to what we're using before. You can view the current mockups in the Navigation collection https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCGbLONQNpzfjwfArUL3vwRc

## Change log: 
- background color so that users don't confuse the language bar as primary nav
- selected/deselected styling to reduce the visual noise 
  - removed the white box around selected languages
  - deselected languages drop to 50% opacity
