### ISSUE TITLE
Janis v2 Design: Global style refactor

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#872]
Clean up/Remove USWDS 1.0, flexboxgrid, and other style libraries and fonts used for Janis 1.1 styles.
Implement USWDS 2.0 base style modules needed for Janis 2.0 reskin.
Implement new fonts for Janis 2.0 reskin.
Set base variables/styles for Janis reskin.

**Comment by pibemillo** [comment]
I would narrow this issue to 
- [ ] Removing legacy scss variables and replacing instances with janis 2.0 style variables. Clean up effort
- Fonts have been updated, need to decided if we removing Open Sans fallback google font

**Comment by easherma** [comment]
@pibemillo where did we get with this one?

**Comment by pibemillo** [comment]
@easherma here's a quick update on the original task description. My general approach was to selectively refactor existing components and apply Janis 2.0 base styles to the existing setup — cleanup of legacy styling is still very much needed.  

- USWDS 1.0 is barely being used and can be found in `coa.scss` and is referenced and used in some Janis 1 legacy components (look for `.usa-` prefixed classes). If the decision is to upgrade/implement USWDS 2.0, I suggest adopting their grid as well and ditching flexboxgrid (will require refactoring layout and classes applied to components).
- Flexboxgrid is still active and I continued using it for laying out pages/components. 
- Fonts have been updated for Janis 2.0, although we could get rid of Open Sans since it's inactive and and probably came from Janis 1.0. 
- Legacy styles for Janis 1 need to be removed/archived, primarily inactive colors. Spacing, font, and line-height variables were updated for Janis 2.0 reskin (`_variables.scss`).
- Most base variables/styles for Janis 2.0 reskin were applied, but a design scrubbing/audit should help sort out of some inconsistencies such as color shades. Also, naming convention for styling variables should be reconsidered or updated as some of them might not be consistent.
