### ISSUE TITLE
Police Oversight form: Update mocks with final content

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#949]
https://docs.google.com/document/d/1CK7zYEN6O_2aMVJ5DiT80r2BhZ5frRAxHUpbsBo5Uhw/edit#heading=h.qrwor0hwpilb

**Comment by chasechenevert** [comment]
##  OPO Form Draft 11
- Gallery screenshots: https://gallery.io/projects/MCHbtQVoQ2HCZcMUWtlNkMhJ/files/MCHbtQVoQ2HCZf7mEMboTkeg#
- XD Prototype demo (visit the link on your phone to see it in context): https://xd.adobe.com/view/1fe1de39-00d3-49a6-748e-9637224ea18f-69d0/?fullscreen
- XD Spec for developers: https://xd.adobe.com/spec/d6588794-d589-429e-469e-188680224204-a069/
- Chart of changes from USWDS (please let me know if you see something I’ve missed): https://docs.google.com/document/d/1vkhhjDpkOj1rAai9MN1AOQ5qe_R2ra6eeV0LjVrRnh4/edit#heading=h.7rn6nehif0oa

## Changelog
-Revised content is in
-Radio buttons: Reverted back to a white background and only have a stroke (1px, #F0F0F0) so that this still remains “contained” but doesn’t confuse the user for an inactive state

Landing page
-Modified the landing to get more clarity. Still iterating on this and wondering whether “Office of Police Oversight” needs to be an eyebrow to the form title… 
-More of the options are revealed above the fold
-Removed the breadcrumb structure for now since we haven’t really fleshed out this interaction
-Light-blue background is gone in favor of white
-Accordions here now match accordions at the end

![screen shot 2019-01-15 at 3 30 23 pm](https://user-images.githubusercontent.com/7027270/51211228-85e7aa00-18da-11e9-8a8d-b9ed119c6ab3.png)
