### ISSUE TITLE
Police Oversight form: Implement deploy pipeline for form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#965]
Build in Travis, copy to AWS.

**Comment by sergiogcx** [comment]
The deployment is working for staging; nevertheless, it is not currently an "automatic" process, meaning that the build currently has to be manually triggered. 


### How it works
The way it currently works is by keeping a list of all forms to be built in a json document, it downloads the code from each repo in that list into folders, each folder is built using yarn and webpack; then, a folder with the same name is created in s3, then the newly built assets are uploaded (synced) into that folder.

### Examples
The forms are available here (staging):
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/

Officer-complaint-form:
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/officer-complaint-form

officer-thank-form:
http://police-monitor-website-staging.s3-website-us-east-1.amazonaws.com/officer-thank-form


### Code
To see how travis builds the form(s):
https://travis-ci.org/cityofaustin/forms-service-deploy

Repo:
https://github.com/cityofaustin/forms-service-deploy

**Comment by sergiogcx** [comment]
### Working smoothly on production:

** Note that this is merely a test and does not reflect the final looks, this is only meant for demonstrating the concept pipeline, build process and deployment functionality. **

Test link:
https://d1tox4tz6kpvtt.cloudfront.net/forms.html

@amenity @briaguya what do you guys think of this semi-automatic deployment process? are you ok with this sub-directory form arrangement?

**Comment by sergiogcx** [comment]
Thanks @briaguya,

This issue has been temporarily fixed by copying all fonts into the /fonts directory in both staging and production. The real fix should be implemented at the React Router level. While S3 works with relative paths now, that is affecting the fonts, I would not be surprised if other assets may not be loading.

Code:

```
function forms_sync_fonts {
  forms_change_dir "fonts"
  S3_DESTINATION="s3://${DEPLOYMENT_BUCKET}/fonts"
  echo "Syncing files from ${PWD} into ${S3_DESTINATION}"
  aws s3 sync . $S3_DESTINATION --delete
}
```

Repo:
https://github.com/cityofaustin/forms-service-deploy/blob/849375ab2452effb4239a4971bdaab3b0b354e6b/.travis/aws-helper.sh#L171

Production (not showing 404 errors any more):
https://d1tox4tz6kpvtt.cloudfront.net/police-oversight-compliment/
https://d1tox4tz6kpvtt.cloudfront.net/police-oversight-complaint/

**Comment by sergiogcx** [comment]
Ready for 2nd review @amenity @briaguya  :)
