### ISSUE TITLE
Police Oversight Form: Prepare for implementation of file uploads to cloud storage

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#991]
Probably to AWS bucket - checking with CTM to confirm. 
Email confirmation emails (#989)  will contain links so that resident and OPO staff can download media. 

This will include a proof of concept connection with [Filepond](https://pqina.nl/filepond/).

**Comment by sergiogcx** [comment]
While waiting on other things to resolve, I was putting things around in terms of large file uploads.

I was able to put a small app together:

Front-end is written in react:
https://d1tox4tz6kpvtt.cloudfront.net/fileuploads.html?case=C3D-123-9876

Where the case number has to follow that format:
[3 digit uppercase alphanumeric]-[3 digit numeric]-[4 digit numeric]

At the moment you can write any code you want without any restrictions.


## Architecture

![Untitled drawing.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c831832a-8820-458b-ab31-5e317fbe44e8)

Overall, the front end will have access to the API Backend, the backend grants permission to upload to s3. With that token, a library can be used to upload (either axios, or otherwise).

**Comment by sergiogcx** [comment]
Repo:
https://github.com/cityofaustin/form-service-largefile-upload

Demo:
https://d1tox4tz6kpvtt.cloudfront.net/fileupload.html?case=C3D-123-9876

I've managed to re-work the the app into using FilePond @briaguya :

![Screen_Shot_2018-12-21_at_1_58_42_AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f74f89e1-39f6-4baa-ad46-a941d8cd38a8)

File uploads to s3:

![Fullscreen_12_21_18__2_00_AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/20a45f50-8092-47a0-bcef-2143f9b6fb16)

**Comment by amenity** [comment]
Done, moving on to https://github.com/cityofaustin/techstack/issues/1003.
